%%{init: {'theme':'neutral'}}%%
graph TD
A[(source.rexx)] --> B[compile: rxc source]
B --> C[(source.rxas)]
C --> D[assemble: rxas source]
D --> E[(source.rxbin)]
E --> F(run: rxvme source)
F -.-> G(pack: rxcpack source)
G --> H[(source.c)]
H --> I[native compile: gcc source]
I --> J[(./source/ source.exe)]
