%%{init: {'theme':'neutral'}}%%
graph TD
A[(source.rexx)] --> B[compile: rxc source]
B --> C[(source.rxas)]
C --> D[assemble: rxas source]
D --> E[(source.rxbin)]
E --> F(run: rxvme source)
E -.-> G(link: rxlink source)
G --> H(pack: rxcpack source)
H --> I[(source.c)]
I --> J[native compile: gcc source]
J --> K[(./source/ source.exe)]
