cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED SOURCE OR NOT DEFINED WORK)
    message(FATAL_ERROR "SOURCE and WORK required")
endif()
file(MAKE_DIRECTORY "${WORK}")
file(READ "${SOURCE}/catalogue.json" original)
foreach(pass IN ITEMS first second)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DCATALOGUE=${SOURCE}/catalogue.json"
            "-DOUT=${WORK}/${pass}" -P "${SOURCE}/Generate.cmake"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Generation failed: ${output}${error}")
    endif()
endforeach()
foreach(artifact IN ITEMS ui_catalog.crexx ui-contract.ts ui-contract.schema.json CATALOGUE.md)
    file(SHA256 "${WORK}/first/${artifact}" first)
    file(SHA256 "${WORK}/second/${artifact}" second)
    if(NOT first STREQUAL second)
        message(FATAL_ERROR "Non-deterministic ${artifact}")
    endif()
endforeach()
string(JSON count LENGTH "${original}" messages)
file(READ "${WORK}/first/ui-contract.schema.json" schema)
string(JSON variants LENGTH "${schema}" oneOf)
if(NOT variants EQUAL count)
    message(FATAL_ERROR "Schema did not cover the catalogue")
endif()
# Invalid catalogues fail at generation, not during a future client build.
foreach(problem IN ITEMS version duplicate direction outcome role field_type)
    set(broken "${original}")
    if(problem STREQUAL "version")
        string(JSON broken SET "${broken}" version 1)
    elseif(problem STREQUAL "duplicate")
        string(JSON broken SET "${broken}" messages 1 name "\"ui.ready\"")
    elseif(problem STREQUAL "direction")
        string(JSON broken SET "${broken}" messages 0 direction "\"sideways\"")
    elseif(problem STREQUAL "role")
        string(JSON broken SET "${broken}" messages 0 role "\"unknown\"")
    elseif(problem STREQUAL "field_type")
        string(JSON broken SET "${broken}" messages 1 fields reason type "\"date\"")
    else()
        math(EXPR last "${count}-1")
        string(JSON broken SET "${broken}" messages ${last} success "\"ui.ready\"")
    endif()
    file(WRITE "${WORK}/${problem}.json" "${broken}")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DCATALOGUE=${WORK}/${problem}.json"
            "-DOUT=${WORK}/invalid-${problem}" -P "${SOURCE}/Generate.cmake"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0)
        message(FATAL_ERROR "Invalid ${problem} was accepted")
    endif()
endforeach()
