cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED CATALOGUE OR NOT DEFINED OUT)
    message(FATAL_ERROR "CATALOGUE and OUT are required")
endif()
file(READ "${CATALOGUE}" catalogue)
string(JSON version GET "${catalogue}" version)
if(NOT version EQUAL 0)
    message(FATAL_ERROR "Unsupported UI catalogue version")
endif()
file(MAKE_DIRECTORY "${OUT}")
set(rexx "/* Generated from contracts/catalogue.json. Do not edit. */\noptions levelg\nnamespace ui_catalog expose catalogue_entry catalogue_names catalogue_profile\n\n/** Return a catalogue definition; empty means unknown. */\ncatalogue_entry: procedure = .string\n  arg name = .string\n")
set(ts "// Generated from contracts/catalogue.json. Do not edit.\nexport interface UIResource { id: string; scope: 'local' | 'session' | 'remote'; display_name: string; readable: boolean; writable: boolean }\nexport interface UIPayloads {\n")
set(md "# UI contract v0 catalogue\n\nGenerated from [catalogue.json](catalogue.json). Names describe semantics, not a promise that every driver implements the capability. Profiles ending in `.planned` are coverage targets.\n\n| Name | Direction | Capability | Payload fields (? = optional) | Meaning |\n| --- | --- | --- | --- | --- |\n")
set(resource [=[{"type":"object","additionalProperties":false,"required":["id","scope","display_name","readable","writable"],"properties":{"id":{"type":"string","minLength":1,"maxLength":128},"scope":{"enum":["local","session","remote"]},"display_name":{"type":"string","maxLength":16384},"readable":{"type":"boolean"},"writable":{"type":"boolean"}}}]=])
set(schema [=[{"$schema":"https://json-schema.org/draft/2020-12/schema","title":"cREXX UI contract v0 standard messages","oneOf":[]}]=])
string(JSON schema SET "${schema}" "$defs" "{\"resource\":${resource}}")
set(names "")
set(event_names "")
set(effect_names "")
string(JSON count LENGTH "${catalogue}" messages)
math(EXPR last "${count}-1")
foreach(i RANGE 0 ${last})
    string(JSON entry GET "${catalogue}" messages ${i})
    foreach(key IN ITEMS name direction capability summary)
        string(JSON ${key} GET "${entry}" ${key})
    endforeach()
    if(NOT name MATCHES "^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$" OR name IN_LIST seen)
        message(FATAL_ERROR "Invalid or duplicate UI name: ${name}")
    endif()
    list(APPEND seen "${name}")
    set(definition_${name} "${entry}")
    if(NOT direction MATCHES "^(event|effect)$")
        message(FATAL_ERROR "Invalid direction for ${name}")
    endif()
    if(direction STREQUAL "event")
        string(JSON role GET "${entry}" role)
        if(NOT role MATCHES "^(input|completion|progress)$")
            message(FATAL_ERROR "Invalid event role for ${name}")
        endif()
    else()
        string(JSON mode GET "${entry}" mode)
        if(NOT mode MATCHES "^(finite|subscription)$")
            message(FATAL_ERROR "Invalid effect mode for ${name}")
        endif()
    endif()
    string(REPLACE "'" "''" rexx_entry "${entry}")
    string(REPLACE "\n" "" rexx_entry "${rexx_entry}")
    string(APPEND rexx "  if name = '${name}' then return '${rexx_entry}'\n")
    string(APPEND names "${name} ")
    string(APPEND ${direction}_names " | '${name}'")
    set(payload "{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{},\"required\":[]}")
    set(field_text "")
    string(JSON fields GET "${entry}" fields)
    string(JSON field_count LENGTH "${fields}")
    if(field_count EQUAL 0)
        string(APPEND ts "  '${name}': Record<string, never>;\n")
    else()
        string(APPEND ts "  '${name}': { ")
    endif()
    set(required_count 0)
    if(field_count GREATER 0)
        math(EXPR field_last "${field_count}-1")
        foreach(j RANGE 0 ${field_last})
            string(JSON field MEMBER "${fields}" ${j})
            string(JSON spec GET "${fields}" "${field}")
            string(JSON type GET "${spec}" type)
            if(NOT field MATCHES "^[a-z][a-z0-9_]*$")
                message(FATAL_ERROR "Invalid field name ${name}.${field}")
            endif()
            string(JSON required_type TYPE "${spec}" required)
            if(NOT required_type STREQUAL "BOOLEAN")
                message(FATAL_ERROR "required must be boolean: ${name}.${field}")
            endif()
            string(JSON required GET "${spec}" required)
            string(JSON spec REMOVE "${spec}" required)
            set(optional "?")
            if(required)
                set(optional "")
                string(JSON payload SET "${payload}" required ${required_count} "\"${field}\"")
                math(EXPR required_count "${required_count}+1")
            endif()
            set(ts_type "${type}")
            if(type STREQUAL "integer")
                set(ts_type "number")
            elseif(type STREQUAL "strings")
                set(ts_type "string[]")
                string(JSON spec SET "${spec}" type "\"array\"")
                string(JSON spec SET "${spec}" items "{\"type\":\"string\",\"maxLength\":16384}")
            elseif(type STREQUAL "resource")
                set(ts_type "UIResource")
                set(spec "{\"$ref\":\"#/$defs/resource\"}")
            elseif(NOT type MATCHES "^(string|boolean)$")
                message(FATAL_ERROR "Unsupported field type ${type}")
            endif()
            string(JSON enums ERROR_VARIABLE no_enum GET "${spec}" enum)
            if(NOT no_enum)
                string(JSON enum_count LENGTH "${enums}")
                math(EXPR enum_last "${enum_count}-1")
                set(ts_type "never")
                foreach(k RANGE 0 ${enum_last})
                    string(JSON choice GET "${enums}" ${k})
                    string(APPEND ts_type " | '${choice}'")
                endforeach()
            endif()
            string(JSON payload SET "${payload}" properties "${field}" "${spec}")
            string(APPEND ts "${field}${optional}: ${ts_type}; ")
            string(APPEND field_text "`${field}${optional}:${type}` ")
        endforeach()
    endif()
    if(field_count GREATER 0)
        string(APPEND ts "};\n")
    endif()
    string(APPEND md "| `${name}` | ${direction} | `${capability}` | ${field_text} | ${summary} |\n")
    set(envelope [=[{"type":"object","additionalProperties":false,"required":["version","direction","name","target","payload","request_id","session_id","sequence"],"properties":{"version":{"const":0},"direction":{},"name":{},"target":{"type":"string","minLength":1,"maxLength":128},"payload":{},"request_id":{"type":"string","maxLength":128},"session_id":{"type":"string","maxLength":128},"sequence":{"type":"integer","minimum":0,"maximum":9007199254740991}}}]=])
    string(JSON envelope SET "${envelope}" properties name "{\"const\":\"${name}\"}")
    string(JSON envelope SET "${envelope}" properties direction "{\"const\":\"${direction}\"}")
    string(JSON envelope SET "${envelope}" properties payload "${payload}")
    string(JSON schema SET "${schema}" oneOf ${i} "${envelope}")
endforeach()
# Every standard effect outcome must resolve to a declared event.
foreach(i RANGE 0 ${last})
    string(JSON direction GET "${catalogue}" messages ${i} direction)
    if(direction STREQUAL "effect")
        foreach(outcome IN ITEMS success failure cancel progress)
            string(JSON name GET "${catalogue}" messages ${i} ${outcome})
            if(NOT name IN_LIST seen)
                message(FATAL_ERROR "Unknown outcome ${name}")
            endif()
            set(outcome_definition "${definition_${name}}")
            string(JSON outcome_direction GET "${outcome_definition}" direction)
            string(JSON outcome_role ERROR_VARIABLE missing_role GET "${outcome_definition}" role)
            set(expected_role "completion")
            if(outcome STREQUAL "progress")
                set(expected_role "progress")
            endif()
            if(NOT outcome_direction STREQUAL "event" OR NOT outcome_role STREQUAL expected_role)
                message(FATAL_ERROR "Invalid ${outcome} event: ${name}")
            endif()
        endforeach()
    endif()
endforeach()
string(STRIP "${names}" names)
string(APPEND rexx "  return ''\n\n/** Space-separated registered standard names. */\ncatalogue_names: procedure = .string\n  return '${names}'\n\n/** Space-separated capabilities for one named profile. */\ncatalogue_profile: procedure = .string\n  arg name = .string\n")
string(JSON profiles GET "${catalogue}" profiles)
string(JSON profile_count LENGTH "${profiles}")
math(EXPR profile_last "${profile_count}-1")
foreach(i RANGE 0 ${profile_last})
    string(JSON profile MEMBER "${profiles}" ${i})
    string(JSON length LENGTH "${profiles}" "${profile}")
    math(EXPR cap_last "${length}-1")
    set(caps "")
    foreach(j RANGE 0 ${cap_last})
        string(JSON cap GET "${profiles}" "${profile}" ${j})
        string(APPEND caps "${cap} ")
    endforeach()
    string(STRIP "${caps}" caps)
    string(APPEND rexx "  if name = '${profile}' then return '${caps}'\n")
endforeach()
string(APPEND rexx "  return ''\n")
string(APPEND ts "}\nexport type UIEventName = never${event_names};\nexport type UIEffectName = never${effect_names};\nexport type UIMessage<K extends keyof UIPayloads = keyof UIPayloads> = K extends keyof UIPayloads ? { version: 0; direction: K extends UIEventName ? 'event' : 'effect'; name: K; target: string; payload: UIPayloads[K]; request_id: string; session_id: string; sequence: number } : never;\n// Integers in this wire contract are limited to the JavaScript safe integer range.\n// An empty request/session ID and sequence 0 mean an unsubmitted local message.\n")
file(WRITE "${OUT}/ui_catalog.crexx" "${rexx}")
string(APPEND ts [=[
/** Local builders only. Validate untrusted data against the schema on ingress. */
export function uiEvent<K extends UIEventName>(name: K, payload: UIPayloads[K], target = 'root'): UIMessage<K> {
  return { version: 0, direction: 'event', name, target, payload, request_id: '', session_id: '', sequence: 0 } as UIMessage<K>;
}
export function uiEffect<K extends UIEffectName>(name: K, payload: UIPayloads[K], target = 'root'): UIMessage<K> {
  return { version: 0, direction: 'effect', name, target, payload, request_id: '', session_id: '', sequence: 0 } as UIMessage<K>;
}
]=])
file(WRITE "${OUT}/ui-contract.ts" "${ts}")
file(WRITE "${OUT}/ui-contract.schema.json" "${schema}\n")
file(WRITE "${OUT}/CATALOGUE.md" "${md}")
