if(NOT DEFINED GENERATED OR NOT EXISTS "${GENERATED}")
    message(FATAL_ERROR "generated Text Inspector source is missing: ${GENERATED}")
endif()

file(READ "${GENERATED}" generated_source)
if(NOT generated_source MATCHES "options[^\n]*srcmap")
    message(FATAL_ERROR "RXPP output does not contain source-map mode")
endif()
if(NOT generated_source MATCHES "add_spec")
    message(FATAL_ERROR "RXPP did not generate logical node construction")
endif()
if(NOT generated_source MATCHES "document.open.requested")
    message(FATAL_ERROR "RXPP did not preserve the semantic Open action")
endif()
