# Compare compiler exits enabled in the normal and constrained native compilers.
set(cases compiler/tests/rexx_src/test_simple_do_subscope.crexx
    compiler/exits/signal/test_signal.crexx
    compiler/exits/fsay/test_fsay.crexx)
foreach(input IN LISTS cases)
    get_filename_component(name "${input}" NAME_WE)
    foreach(mode IN ITEMS optimized unoptimized)
        set(flags)
        if(mode STREQUAL unoptimized)
            set(flags -n)
        endif()
        foreach(kind IN ITEMS reference constrained)
            set(dir "${WORK}/${name}-${mode}/${kind}")
            file(MAKE_DIRECTORY "${dir}")
            file(REMOVE "${dir}/program.rxas" "${dir}/program.rxbin" "${dir}/run.log")
            set(exe "${REFERENCE}")
            if(kind STREQUAL constrained)
                set(exe "${COMPILER}")
            endif()
            execute_process(COMMAND "${exe}" -i "${LIBDIR}" ${flags} -o program "${SOURCE}/${input}"
                WORKING_DIRECTORY "${dir}" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
            file(WRITE "${dir}/compile.log" "rc=${rc}\n${out}${err}")
            if(NOT rc EQUAL 0)
                message(FATAL_ERROR "Compile failed: ${name} ${mode} ${kind}: ${rc}: ${out}${err}")
            endif()
            execute_process(COMMAND "${RXAS}" ${flags} -o program program.rxas WORKING_DIRECTORY "${dir}"
                RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
            if(NOT rc EQUAL 0)
                message(FATAL_ERROR "Assemble failed: ${name} ${kind}: ${out}${err}")
            endif()
            execute_process(COMMAND "${VM}" program.rxbin "${LIBDIR}/library.rxbin" WORKING_DIRECTORY "${dir}"
                RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
            file(WRITE "${dir}/run.log" "rc=${rc}\n${out}${err}")
            if(NOT rc EQUAL 0 OR NOT out MATCHES "SUCCESS")
                message(FATAL_ERROR "Execution failed: ${name} ${kind}: ${rc}: ${out}${err}")
            endif()
        endforeach()
        foreach(file IN ITEMS program.rxas program.rxbin run.log)
            execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files
                "${WORK}/${name}-${mode}/reference/${file}" "${WORK}/${name}-${mode}/constrained/${file}"
                RESULT_VARIABLE rc)
            if(NOT rc EQUAL 0)
                message(FATAL_ERROR "Compiler parity failed: ${name} ${mode} ${file}")
            endif()
        endforeach()
    endforeach()
endforeach()
# Reuse the normal compiler's invalid UTF-8 literal control, with exits enabled.
file(WRITE "${WORK}/invalid.crexx" "options levelb\n\nmain: procedure\n  say 'FFFFFF'x\n")
foreach(kind IN ITEMS reference constrained)
    set(dir "${WORK}/invalid/${kind}")
    file(MAKE_DIRECTORY "${dir}")
    set(exe "${REFERENCE}")
    if(kind STREQUAL constrained)
        set(exe "${COMPILER}")
    endif()
    execute_process(COMMAND "${exe}" -i "${LIBDIR}" -o program "${WORK}/invalid.crexx"
        WORKING_DIRECTORY "${dir}" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    file(WRITE "${dir}/compile.log" "rc=${rc}\n${out}${err}")
    if(NOT rc MATCHES "^[1-9][0-9]*$" OR NOT "${out}${err}" MATCHES "CANNOT_CAST_BINARY")
        message(FATAL_ERROR "Expected invalid literal rejection: ${kind}: ${rc}: ${out}${err}")
    endif()
    if(kind STREQUAL reference)
        set(reference_rc "${rc}")
    elseif(NOT rc EQUAL reference_rc)
        message(FATAL_ERROR "Compiler error return differs: ${reference_rc} vs ${rc}")
    endif()
endforeach()
message(STATUS "PASS: six RXC assembly, bytecode and execution comparisons; exits enabled; invalid literal rejected by both compilers")
