set(platform "Darwin")
set(provider copy_control)
set(arch "arm64")
set(engine fixture)
set(runtime_files "/tmp/crexx-package-copy-asan/a/libcopy_root_a.dylib")
set(output "/tmp/crexx-package-copy-asan/proof/missing")
