set(platform "Darwin")
set(provider copy_control)
set(arch "x86_64")
set(engine fixture)
set(runtime_files "/Users/runner/work/_temp/package-scan/a/libcopy_root_a.dylib")
set(output "/Users/runner/work/_temp/package-scan/proof/missing")
