#define ERROR                            1
#define ANYTHING                         2
#define EOS                              3
#define NEWLINE                          4
#define KW_GLOBALS                       5
#define EQUAL                            6
#define INT                              7
#define FUNC                             8
#define KW_LOCALS                        9
#define LABEL                           10
#define ID                              11
#define COMMA                           12
#define REG                             13
#define FLOAT                           14
#define CHAR                            15
#define STRING                          16
