/* This file is automatically generated by Lemon from input grammar
** source file "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 7 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"

#include <assert.h>
#include <stdlib.h>
#include <stdio.h>
#include "rxas.h"
#include "rxasassm.h"
#line 36 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef ERROR
#define ERROR                           1
#define ANYTHING                        2
#define EOS                             3
#define NEWLINE                         4
#define KW_GLOBALS                      5
#define EQUAL                           6
#define INT                             7
#define FUNC                            8
#define KW_LOCALS                       9
#define LABEL                          10
#define ID                             11
#define COMMA                          12
#define REG                            13
#define FLOAT                          14
#define CHAR                           15
#define STRING                         16
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 29
#define YYACTIONTYPE unsigned char
#define YYWILDCARD 2
#define ParseTOKENTYPE  Token* 
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
  Token* yy14;
  int yy59;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define ParseARG_SDECL  Assembler_Context *context ;
#define ParseARG_PDECL , Assembler_Context *context 
#define ParseARG_PARAM ,context 
#define ParseARG_FETCH  Assembler_Context *context =yypParser->context ;
#define ParseARG_STORE yypParser->context =context ;
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#define YYERRORSYMBOL 20
#define YYERRSYMDT yy59
#define YYNSTATE             68
#define YYNRULE              43
#define YYNRULE_WITH_ACTION  22
#define YYNTOKEN             17
#define YY_MAX_SHIFT         67
#define YY_MIN_SHIFTREDUCE   68
#define YY_MAX_SHIFTREDUCE   110
#define YY_ERROR_ACTION      111
#define YY_ACCEPT_ACTION     112
#define YY_NO_ACTION         113
#define YY_MIN_REDUCE        114
#define YY_MAX_REDUCE        156
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (209)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */    27,   65,   15,   41,  126,   45,   66,   36,   37,   44,
 /*    10 */    21,   39,   24,   38,   35,   34,   33,   40,   25,    6,
 /*    20 */   112,    1,    4,   46,   28,   52,   42,   66,   19,    9,
 /*    30 */    47,   29,   11,   36,   37,   13,   14,   39,  121,   38,
 /*    40 */    35,   34,   33,   17,   12,  114,   29,   11,   36,   37,
 /*    50 */    13,   20,   39,  129,   38,   35,   34,   33,   21,  145,
 /*    60 */    24,    3,   22,   65,  145,   51,   25,    6,   48,  146,
 /*    70 */   146,  146,   53,   13,  156,  146,  156,  146,  146,   50,
 /*    80 */   125,  125,  125,   10,  156,  155,  125,  155,  125,  125,
 /*    90 */    49,  149,  149,  149,   57,  155,  154,  149,  154,  149,
 /*   100 */   149,  115,  124,  124,  124,   43,  154,  153,  124,  153,
 /*   110 */   124,  124,   54,  148,  148,  148,   55,  153,  152,  148,
 /*   120 */   152,  148,  148,   58,  147,  147,  147,   59,  152,   60,
 /*   130 */   147,  116,  147,  147,    5,  138,   31,   52,   42,   66,
 /*   140 */   139,   61,  139,  139,   67,  142,  139,  142,  142,   13,
 /*   150 */   141,  142,  141,  141,  143,  140,  141,  140,  140,  143,
 /*   160 */   117,  140,  117,  117,   62,  151,  117,  151,  150,   18,
 /*   170 */   150,  128,   16,  120,  127,  151,  144,   63,  150,    7,
 /*   180 */    64,  144,    8,  137,  119,  118,   30,  113,   32,  122,
 /*   190 */   123,  113,  113,   56,  130,  131,  113,  113,  132,  133,
 /*   200 */   134,  113,  113,  135,   23,   26,  136,  113,    2,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    26,   27,    2,   28,    4,   23,   24,    7,    8,   28,
 /*    10 */     2,   11,    4,   13,   14,   15,   16,   28,   10,   11,
 /*    20 */    17,   18,   19,   20,   21,   22,   23,   24,    2,    2,
 /*    30 */     3,    4,    5,    7,    8,    8,    2,   11,    4,   13,
 /*    40 */    14,   15,   16,    2,    2,    0,    4,    5,    7,    8,
 /*    50 */     8,    2,   11,    4,   13,   14,   15,   16,    2,    3,
 /*    60 */     4,   25,   26,   27,    8,    7,   10,   11,    3,    2,
 /*    70 */     3,    4,   20,    8,    2,    8,    4,   10,   11,   20,
 /*    80 */     2,    3,    4,    6,   12,    2,    8,    4,   10,   11,
 /*    90 */    20,    2,    3,    4,    9,   12,    2,    8,    4,   10,
 /*   100 */    11,    0,    2,    3,    4,    7,   12,    2,    8,    4,
 /*   110 */    10,   11,   20,    2,    3,    4,   20,   12,    2,    8,
 /*   120 */     4,   10,   11,   20,    2,    3,    4,   20,   12,   20,
 /*   130 */     8,    0,   10,   11,   19,    0,   21,   22,   23,   24,
 /*   140 */     2,   20,    4,    5,    3,    2,    8,    4,    5,    8,
 /*   150 */     2,    8,    4,    5,    3,    2,    8,    4,    5,    8,
 /*   160 */     2,    8,    4,    5,   20,    2,    8,    4,    2,    2,
 /*   170 */     4,    4,    2,    4,    4,   12,    3,   20,   12,   12,
 /*   180 */    20,    8,   12,    0,    4,    4,    4,   29,    4,    4,
 /*   190 */     4,   29,   29,    6,    4,    4,   29,   29,    4,    4,
 /*   200 */     4,   29,   29,    4,    4,    4,    0,   29,    4,   29,
 /*   210 */    29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
 /*   220 */    29,   29,   29,   29,   29,   29,
};
#define YY_SHIFT_COUNT    (67)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (206)
static const unsigned char yy_shift_ofst[] = {
 /*     0 */    27,   42,    8,   56,   65,  141,    0,   26,   41,   45,
 /*    10 */    58,   77,  101,   85,  209,  209,  209,  209,  209,  209,
 /*    20 */   209,  209,   67,   78,   89,  100,  111,  122,  138,  143,
 /*    30 */   148,  153,  158,   72,   83,   94,  105,  116,  163,  166,
 /*    40 */   167,  170,  151,   34,   49,  173,  131,  135,  183,  169,
 /*    50 */   180,  181,  182,  184,  185,  186,   98,  187,  190,  191,
 /*    60 */   194,  195,  196,  199,  200,  201,  204,  206,
};
#define YY_REDUCE_COUNT (21)
#define YY_REDUCE_MIN   (-26)
#define YY_REDUCE_MAX   (160)
static const short yy_reduce_ofst[] = {
 /*     0 */     3,  115,   36,  -26,  -18,  -18,  -25,  -19,  -11,   52,
 /*    10 */    59,   70,   52,   92,   96,  103,  107,  109,  121,  144,
 /*    20 */   157,  160,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
 /*    10 */   111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
 /*    20 */   111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
 /*    30 */   111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
 /*    40 */   111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
 /*    50 */   111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
 /*    60 */   111,  111,  111,  111,  111,  111,  111,  111,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#ifndef NDEBUG
#include <stdio.h>
#include <assert.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

/* Changed for REXX Always include yyTokenName for error reporting
#if defined(YYCOVERAGE) || !defined(NDEBUG)
*/
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "ERROR",
  /*    2 */ "ANYTHING",
  /*    3 */ "EOS",
  /*    4 */ "NEWLINE",
  /*    5 */ "KW_GLOBALS",
  /*    6 */ "EQUAL",
  /*    7 */ "INT",
  /*    8 */ "FUNC",
  /*    9 */ "KW_LOCALS",
  /*   10 */ "LABEL",
  /*   11 */ "ID",
  /*   12 */ "COMMA",
  /*   13 */ "REG",
  /*   14 */ "FLOAT",
  /*   15 */ "CHAR",
  /*   16 */ "STRING",
  /*   17 */ "program",
  /*   18 */ "headers",
  /*   19 */ "functions",
  /*   20 */ "error",
  /*   21 */ "header",
  /*   22 */ "globals",
  /*   23 */ "function",
  /*   24 */ "functionDeclaration",
  /*   25 */ "instructions",
  /*   26 */ "instruction",
  /*   27 */ "instr",
  /*   28 */ "operand",
};
/* Changed for REXX Always include yyTokenName for error reporting
#endif */ /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "program ::= ANYTHING",
 /*   1 */ "program ::= headers ANYTHING",
 /*   2 */ "program ::= error",
 /*   3 */ "header ::= ANYTHING error NEWLINE",
 /*   4 */ "globals ::= KW_GLOBALS EQUAL INT",
 /*   5 */ "globals ::= KW_GLOBALS EQUAL error",
 /*   6 */ "globals ::= KW_GLOBALS error",
 /*   7 */ "functionDeclaration ::= FUNC KW_LOCALS EQUAL INT",
 /*   8 */ "functionDeclaration ::= FUNC error",
 /*   9 */ "functionDeclaration ::= FUNC KW_LOCALS EQUAL INT ANYTHING error",
 /*  10 */ "instruction ::= LABEL",
 /*  11 */ "instruction ::= ANYTHING error NEWLINE",
 /*  12 */ "instr ::= ID",
 /*  13 */ "instr ::= ID operand",
 /*  14 */ "instr ::= ID operand COMMA operand",
 /*  15 */ "instr ::= ID operand COMMA operand COMMA operand",
 /*  16 */ "instr ::= ID ANYTHING error",
 /*  17 */ "instr ::= ID operand ANYTHING error",
 /*  18 */ "instr ::= ID operand COMMA ANYTHING error",
 /*  19 */ "instr ::= ID operand COMMA operand ANYTHING error",
 /*  20 */ "instr ::= ID operand COMMA operand COMMA ANYTHING error",
 /*  21 */ "instr ::= ID operand COMMA operand COMMA operand ANYTHING error",
 /*  22 */ "program ::= headers functions EOS",
 /*  23 */ "program ::= functions EOS",
 /*  24 */ "program ::= EOS",
 /*  25 */ "headers ::= header",
 /*  26 */ "headers ::= headers header",
 /*  27 */ "header ::= globals NEWLINE",
 /*  28 */ "header ::= NEWLINE",
 /*  29 */ "functions ::= function",
 /*  30 */ "functions ::= functions function",
 /*  31 */ "function ::= functionDeclaration NEWLINE instructions",
 /*  32 */ "instructions ::= instruction",
 /*  33 */ "instructions ::= instructions instruction",
 /*  34 */ "instruction ::= instr NEWLINE",
 /*  35 */ "instruction ::= NEWLINE",
 /*  36 */ "operand ::= ID",
 /*  37 */ "operand ::= REG",
 /*  38 */ "operand ::= FUNC",
 /*  39 */ "operand ::= INT",
 /*  40 */ "operand ::= FLOAT",
 /*  41 */ "operand ::= CHAR",
 /*  42 */ "operand ::= STRING",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    17,  /* (0) program ::= ANYTHING */
    17,  /* (1) program ::= headers ANYTHING */
    17,  /* (2) program ::= error */
    21,  /* (3) header ::= ANYTHING error NEWLINE */
    22,  /* (4) globals ::= KW_GLOBALS EQUAL INT */
    22,  /* (5) globals ::= KW_GLOBALS EQUAL error */
    22,  /* (6) globals ::= KW_GLOBALS error */
    24,  /* (7) functionDeclaration ::= FUNC KW_LOCALS EQUAL INT */
    24,  /* (8) functionDeclaration ::= FUNC error */
    24,  /* (9) functionDeclaration ::= FUNC KW_LOCALS EQUAL INT ANYTHING error */
    26,  /* (10) instruction ::= LABEL */
    26,  /* (11) instruction ::= ANYTHING error NEWLINE */
    27,  /* (12) instr ::= ID */
    27,  /* (13) instr ::= ID operand */
    27,  /* (14) instr ::= ID operand COMMA operand */
    27,  /* (15) instr ::= ID operand COMMA operand COMMA operand */
    27,  /* (16) instr ::= ID ANYTHING error */
    27,  /* (17) instr ::= ID operand ANYTHING error */
    27,  /* (18) instr ::= ID operand COMMA ANYTHING error */
    27,  /* (19) instr ::= ID operand COMMA operand ANYTHING error */
    27,  /* (20) instr ::= ID operand COMMA operand COMMA ANYTHING error */
    27,  /* (21) instr ::= ID operand COMMA operand COMMA operand ANYTHING error */
    17,  /* (22) program ::= headers functions EOS */
    17,  /* (23) program ::= functions EOS */
    17,  /* (24) program ::= EOS */
    18,  /* (25) headers ::= header */
    18,  /* (26) headers ::= headers header */
    21,  /* (27) header ::= globals NEWLINE */
    21,  /* (28) header ::= NEWLINE */
    19,  /* (29) functions ::= function */
    19,  /* (30) functions ::= functions function */
    23,  /* (31) function ::= functionDeclaration NEWLINE instructions */
    25,  /* (32) instructions ::= instruction */
    25,  /* (33) instructions ::= instructions instruction */
    26,  /* (34) instruction ::= instr NEWLINE */
    26,  /* (35) instruction ::= NEWLINE */
    28,  /* (36) operand ::= ID */
    28,  /* (37) operand ::= REG */
    28,  /* (38) operand ::= FUNC */
    28,  /* (39) operand ::= INT */
    28,  /* (40) operand ::= FLOAT */
    28,  /* (41) operand ::= CHAR */
    28,  /* (42) operand ::= STRING */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) program ::= ANYTHING */
   -2,  /* (1) program ::= headers ANYTHING */
   -1,  /* (2) program ::= error */
   -3,  /* (3) header ::= ANYTHING error NEWLINE */
   -3,  /* (4) globals ::= KW_GLOBALS EQUAL INT */
   -3,  /* (5) globals ::= KW_GLOBALS EQUAL error */
   -2,  /* (6) globals ::= KW_GLOBALS error */
   -4,  /* (7) functionDeclaration ::= FUNC KW_LOCALS EQUAL INT */
   -2,  /* (8) functionDeclaration ::= FUNC error */
   -6,  /* (9) functionDeclaration ::= FUNC KW_LOCALS EQUAL INT ANYTHING error */
   -1,  /* (10) instruction ::= LABEL */
   -3,  /* (11) instruction ::= ANYTHING error NEWLINE */
   -1,  /* (12) instr ::= ID */
   -2,  /* (13) instr ::= ID operand */
   -4,  /* (14) instr ::= ID operand COMMA operand */
   -6,  /* (15) instr ::= ID operand COMMA operand COMMA operand */
   -3,  /* (16) instr ::= ID ANYTHING error */
   -4,  /* (17) instr ::= ID operand ANYTHING error */
   -5,  /* (18) instr ::= ID operand COMMA ANYTHING error */
   -6,  /* (19) instr ::= ID operand COMMA operand ANYTHING error */
   -7,  /* (20) instr ::= ID operand COMMA operand COMMA ANYTHING error */
   -8,  /* (21) instr ::= ID operand COMMA operand COMMA operand ANYTHING error */
   -3,  /* (22) program ::= headers functions EOS */
   -2,  /* (23) program ::= functions EOS */
   -1,  /* (24) program ::= EOS */
   -1,  /* (25) headers ::= header */
   -2,  /* (26) headers ::= headers header */
   -2,  /* (27) header ::= globals NEWLINE */
   -1,  /* (28) header ::= NEWLINE */
   -1,  /* (29) functions ::= function */
   -2,  /* (30) functions ::= functions function */
   -3,  /* (31) function ::= functionDeclaration NEWLINE instructions */
   -1,  /* (32) instructions ::= instruction */
   -2,  /* (33) instructions ::= instructions instruction */
   -2,  /* (34) instruction ::= instr NEWLINE */
   -1,  /* (35) instruction ::= NEWLINE */
   -1,  /* (36) operand ::= ID */
   -1,  /* (37) operand ::= REG */
   -1,  /* (38) operand ::= FUNC */
   -1,  /* (39) operand ::= INT */
   -1,  /* (40) operand ::= FLOAT */
   -1,  /* (41) operand ::= CHAR */
   -1,  /* (42) operand ::= STRING */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;
  assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yysize = yyRuleInfoNRhs[yyruleno];
    if( yysize ){
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
        yyTracePrompt,
        yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
        yymsp[yysize].stateno);
    }else{
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
        yyTracePrompt, yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
    }
  }
#endif /* NDEBUG */

  /* Check that the stack is large enough to grow by a single entry
  ** if the RHS of the rule is empty.  This ensures that there is room
  ** enough on the stack to push the LHS value */
  if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
    if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
      yypParser->yyhwm++;
      assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack));
    }
#endif
#if YYSTACKDEPTH>0 
    if( yypParser->yytos>=yypParser->yystackEnd ){
      yyStackOverflow(yypParser);
      /* The call to yyStackOverflow() above pops the stack until it is
      ** empty, causing the main parser loop to exit.  So the return value
      ** is never used and does not matter. */
      return 0;
    }
#else
    if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
      if( yyGrowStack(yypParser) ){
        yyStackOverflow(yypParser);
        /* The call to yyStackOverflow() above pops the stack until it is
        ** empty, causing the main parser loop to exit.  So the return value
        ** is never used and does not matter. */
        return 0;
      }
      yymsp = yypParser->yytos;
    }
#endif
  }

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
      case 0: /* program ::= ANYTHING */
#line 39 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{err_at(context, yymsp[0].minor.yy0, "really confused - aborted!");}
#line 1078 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 1: /* program ::= headers ANYTHING */
#line 40 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{err_at(context, yymsp[0].minor.yy0, "totally confused - aborted!");}
#line 1083 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 2: /* program ::= error */
#line 41 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{ error_f(context, 0, 0, 1, "Error completely confused - aborted!");}
#line 1088 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 3: /* header ::= ANYTHING error NEWLINE */
#line 50 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{err_at(context, yymsp[-2].minor.yy0, "invalid header directive");}
#line 1093 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 4: /* globals ::= KW_GLOBALS EQUAL INT */
#line 53 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{rxas_setglobals(context,yymsp[0].minor.yy0);}
#line 1098 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 5: /* globals ::= KW_GLOBALS EQUAL error */
#line 56 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{err_aftr(context, yymsp[-1].minor.yy0, "expecting integer");}
#line 1103 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 6: /* globals ::= KW_GLOBALS error */
#line 57 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{err_aftr(context, yymsp[-1].minor.yy0, "expecting \"={integer}\"");}
#line 1108 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 7: /* functionDeclaration ::= FUNC KW_LOCALS EQUAL INT */
#line 63 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{rxas_proc(context,yymsp[-3].minor.yy0,yymsp[0].minor.yy0);}
#line 1113 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 8: /* functionDeclaration ::= FUNC error */
#line 66 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{err_aftr(context, yymsp[-1].minor.yy0, "expecting \".locals={integer}\"");}
#line 1118 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 9: /* functionDeclaration ::= FUNC KW_LOCALS EQUAL INT ANYTHING error */
#line 68 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{err_at(context, yymsp[-1].minor.yy0, "expecting {newline}");}
#line 1123 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 10: /* instruction ::= LABEL */
#line 74 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{rxas_label(context,yymsp[0].minor.yy0);}
#line 1128 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 11: /* instruction ::= ANYTHING error NEWLINE */
#line 78 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{err_at(context, yymsp[-2].minor.yy0, "invalid label, opcode or directive");}
#line 1133 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 12: /* instr ::= ID */
#line 81 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{rxas_gen0(context,yymsp[0].minor.yy0);}
#line 1138 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 13: /* instr ::= ID operand */
#line 82 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{rxas_gen1(context,yymsp[-1].minor.yy0,yymsp[0].minor.yy14);}
#line 1143 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 14: /* instr ::= ID operand COMMA operand */
#line 83 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{rxas_gen2(context,yymsp[-3].minor.yy0,yymsp[-2].minor.yy14,yymsp[0].minor.yy14);}
#line 1148 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 15: /* instr ::= ID operand COMMA operand COMMA operand */
#line 85 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{rxas_gen3(context,yymsp[-5].minor.yy0,yymsp[-4].minor.yy14,yymsp[-2].minor.yy14,yymsp[0].minor.yy14);}
#line 1153 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 16: /* instr ::= ID ANYTHING error */
      case 17: /* instr ::= ID operand ANYTHING error */ yytestcase(yyruleno==17);
      case 19: /* instr ::= ID operand COMMA operand ANYTHING error */ yytestcase(yyruleno==19);
#line 88 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{err_at(context, yymsp[-1].minor.yy0, "expecting {operand} or {newline}");}
#line 1160 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 18: /* instr ::= ID operand COMMA ANYTHING error */
      case 20: /* instr ::= ID operand COMMA operand COMMA ANYTHING error */ yytestcase(yyruleno==20);
#line 90 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{err_aftr(context, yymsp[-2].minor.yy0, "expecting {operand}");}
#line 1166 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      case 21: /* instr ::= ID operand COMMA operand COMMA operand ANYTHING error */
#line 96 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
{err_at(context, yymsp[-1].minor.yy0, "expecting {newline} - max 3 operands");}
#line 1171 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
        break;
      default:
      /* (22) program ::= headers functions EOS */ yytestcase(yyruleno==22);
      /* (23) program ::= functions EOS */ yytestcase(yyruleno==23);
      /* (24) program ::= EOS */ yytestcase(yyruleno==24);
      /* (25) headers ::= header */ yytestcase(yyruleno==25);
      /* (26) headers ::= headers header */ yytestcase(yyruleno==26);
      /* (27) header ::= globals NEWLINE */ yytestcase(yyruleno==27);
      /* (28) header ::= NEWLINE */ yytestcase(yyruleno==28);
      /* (29) functions ::= function */ yytestcase(yyruleno==29);
      /* (30) functions ::= functions function */ yytestcase(yyruleno==30);
      /* (31) function ::= functionDeclaration NEWLINE instructions */ yytestcase(yyruleno==31);
      /* (32) instructions ::= instruction */ yytestcase(yyruleno==32);
      /* (33) instructions ::= instructions instruction */ yytestcase(yyruleno==33);
      /* (34) instruction ::= instr NEWLINE */ yytestcase(yyruleno==34);
      /* (35) instruction ::= NEWLINE */ yytestcase(yyruleno==35);
      /* (36) operand ::= ID */ yytestcase(yyruleno==36);
      /* (37) operand ::= REG */ yytestcase(yyruleno==37);
      /* (38) operand ::= FUNC */ yytestcase(yyruleno==38);
      /* (39) operand ::= INT */ yytestcase(yyruleno==39);
      /* (40) operand ::= FLOAT */ yytestcase(yyruleno==40);
      /* (41) operand ::= CHAR */ yytestcase(yyruleno==41);
      /* (42) operand ::= STRING */ yytestcase(yyruleno==42);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 25 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"
 fprintf(stderr, "0:0 - Error super completely confused - aborted!\n"); 
#line 1238 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  do{
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      yyact = yy_reduce(yypParser,yyact-YY_MIN_REDUCE,yymajor,
                        yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos >= yypParser->yystack
            && (yyact = yy_find_reduce_action(
                        yypParser->yytos->stateno,
                        YYERRORSYMBOL)) > YY_MAX_SHIFTREDUCE
        ){
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos < yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }while( yypParser->yytos>yypParser->yystack );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
#line 15 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.y"

    const char* token_type_name(int type) {
        return yyTokenName[type];
    }
#line 1494 "C:/Users/adria/CLionProjects/CREXX/assembler/rxasgrmr.c"
