#!/usr/bin/env python3
"""Bootstrap native text maps from the same retained data as rxunicode.
No running cREXX toolchain, network download or independent mapping authority.
"""
import argparse
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / 'lib/rxfnsg/unicode/data/legacy'
OUT = ROOT / 'platform/text_codec_tables.h'

def render():
    maps = [('ascii', [n if n < 128 else 0xffffffff for n in range(256)]),
            ('latin1', list(range(256)))]
    provenance = []
    for name, filename in [('windows1252', 'CP1252-2.0.0.txt'), ('ibm437', 'CP437-2.0.0.txt'),
                           ('ibm850', 'CP850-2.0.0.txt'), ('ibm1047', 'IBM1047.txt')]:
        raw = (DATA / filename).read_bytes()
        provenance.append(f' * {filename}: {hashlib.sha256(raw).hexdigest()}')
        mapping = {}
        for line in raw.decode('utf-8').splitlines():
            if name == 'ibm1047':
                match = re.match(r'^\s*([0-9A-Fa-f]{2})\s+([0-9A-Fa-f]{4})\b', line)
            else:
                match = re.match(r'^0x([0-9A-Fa-f]{2})\s+(?:0x([0-9A-Fa-f]{4})|#UNDEFINED)', line)
            if not match:
                continue
            byte = int(match[1], 16)
            scalar = int(match[2], 16) if match[2] else byte
            assert byte not in mapping and not 0xd800 <= scalar <= 0xdfff
            assert match[2] or name == 'windows1252'
            mapping[byte] = scalar
        assert len(mapping) == 256, (filename, len(mapping))
        maps.append((name, [mapping[n] for n in range(256)]))
    lines = ['/* Generated by generate_text_codecs.py; do not edit.',
             ' * Retained mapping notices: lib/rxfnsg/unicode/data/legacy/SOURCES.md.', *provenance, ' */']
    for name, values in maps:
        lines.append(f'static const uint32_t codec_{name}[256] = {{')
        for i in range(0, 256, 8):
            lines.append('    ' + ', '.join(f'0x{v:08x}u' for v in values[i:i+8]) + ',')
        lines.append('};')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = render()
    if args.check:
        if OUT.read_text() != generated:
            raise SystemExit('Native text tables differ from authoritative codec mappings')
        print('PASS native text tables match 1024 retained mappings plus ASCII/Latin1')
    else:
        OUT.write_text(generated)
