if(NOT DEFINED VM OR NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR
        NOT DEFINED CASE)
    message(FATAL_ERROR "VM, INPUT, OUTPUT, and CASE are required")
endif()

file(REMOVE "${OUTPUT}")
execute_process(
        COMMAND "${VM}" --profile-output "${OUTPUT}" "${INPUT}" ${RUNTIME_ARGS}
        RESULT_VARIABLE profile_result
        OUTPUT_VARIABLE program_output
        ERROR_VARIABLE profile_error)
if(NOT profile_result EQUAL 0)
    message(FATAL_ERROR
            "${CASE} profile failed (${profile_result})\nstdout:\n${program_output}\nstderr:\n${profile_error}")
endif()
if(NOT EXISTS "${OUTPUT}")
    message(FATAL_ERROR "${CASE} profile output was not created")
endif()
file(READ "${OUTPUT}" csv)

function(require_row pattern description)
    if(NOT csv MATCHES "${pattern}")
        message(FATAL_ERROR "${CASE}: missing ${description}\npattern: ${pattern}")
    endif()
endfunction()

require_row("summary,schema_version,5" "schema version 5")
require_row("summary,census_tracking_unavailable,0" "complete census tracking")
if(csv MATCHES ",degraded(\r?\n|$)")
    message(FATAL_ERROR "${CASE}: degraded census row was emitted")
endif()

if(CASE STREQUAL "mechanics")
    if(NOT program_output MATCHES "PASS: NR-05 Call Census")
        message(FATAL_ERROR "mechanics fixture did not report PASS")
    endif()
    require_row("census,\"call_path\",\"direct_bytecode\",,15," "15 direct bytecode calls")
    require_row("census,\"call_path\",\"external_root\",,1," "one root entry")
    require_row("census,\"arity\",\"0\",,7," "seven zero-argument calls")
    require_row("census,\"arity\",\"1\",,8," "eight one-argument calls including root")
    require_row("census,\"arity\",\"2\",,1," "one two-argument call")
    require_row("census,\"frame_disposition\",\"fresh\",,12," "12 fresh frames")
    require_row("census,\"frame_disposition\",\"reused\",,4," "four reused frames")
    require_row("return,\"placement\",\"void\",,3," "three void returns")
    require_row("return,\"placement\",\"ret_reg_move_local\",,5," "five local moves")
    require_row("return,\"placement\",\"ret_reg_copy_nonlocal\",,3," "three non-local copies")
    require_row("return,\"placement\",\"value_ignored\",,1," "one ignored result")
    require_row("return,\"placement\",\"immediate\",,3," "three immediate results")
    require_row("return,\"placement\",\"terminal_external\",,1," "one terminal return")
    require_row("mechanics,\"call_window\",\"setup_swaps\",,1," "one setup swap")
    require_row("mechanics,\"call_window\",\"normal_restoration_swaps\",,1," "one restoration swap")
    require_row("mechanics,\"call_window\",\"unclassified_swaps\",,2," "two unrelated swaps")
    require_row("mechanics,\"call_window\",\"defensive_argument_copies\",,6," "six argument copies")
    require_row("mechanics,\"call_window\",\"unclassified_copies\",,1," "one unrelated copy")
    require_row("mechanics,\"call_window\",\"attribution_degraded\",,0," "complete attribution")
elseif(CASE STREQUAL "selectors")
    if(NOT program_output MATCHES "PASS: Descriptor Selector Contracts")
        message(FATAL_ERROR "selector fixture did not report PASS")
    endif()
    require_row("census,\"call_path\",\"dynamic_bytecode\",,2," "two dynamic calls")
    require_row("census,\"callable_kind\",\"factory\",,1," "one factory call")
    require_row("census,\"callable_kind\",\"method\",,1," "one method call")
    require_row("dynamic,\"srcmethodsel\",\"attempt\",,1," "one method selection")
    require_row("dynamic,\"srcmethodsel\",\"success\",,1," "successful method selection")
    require_row("dynamic,\"srcmethodsel\",\"failure\",,0," "zero failed method selections")
    require_row("dynamic,\"srcfprocsel\",\"attempt\",,1," "one factory selection")
    require_row("dynamic,\"srcfprocsel\",\"success\",,1," "successful factory selection")
    require_row("dynamic,\"srcfprocsel\",\"failure\",,0," "zero failed factory selections")
    require_row("mechanics,\"call_window\",\"setup_swaps\",,1," "one method setup swap")
    require_row("mechanics,\"call_window\",\"normal_restoration_swaps\",,1," "one method restoration swap")
elseif(CASE STREQUAL "signal_unwind")
    if(NOT program_output MATCHES "PASS: Signal Call Mapping Unwind")
        message(FATAL_ERROR "signal fixture did not report PASS")
    endif()
    require_row("census,\"call_path\",\"direct_bytecode\",,4," "four bytecode calls")
    require_row("census,\"frame_disposition\",\"fresh\",,4," "four fresh frames")
    require_row("census,\"frame_disposition\",\"reused\",,1," "one reused frame")
    require_row("mechanics,\"call_window\",\"setup_swaps\",,6," "six setup swaps")
    require_row("mechanics,\"call_window\",\"attribution_degraded\",,0," "complete unwind attribution")
    require_row("unwind,\"signal\",\"events\",,2," "two unwind events")
    require_row("unwind,\"signal\",\"bytecode_frames_discarded\",,3," "three discarded frames")
    require_row("unwind,\"signal\",\"argument_windows_restored\",,3," "three restored windows")
    require_row("unwind,\"signal\",\"argument_slots_restored\",,6," "six restored slots")
    require_row("unwind,\"signal\",\"restoration_failures\",,0," "zero restoration failures")
elseif(CASE STREQUAL "native_unwind")
    if(NOT program_output MATCHES "PASS: Native Signal Call Mapping")
        message(FATAL_ERROR "native unwind fixture did not report PASS")
    endif()
    require_row("census,\"call_path\",\"direct_native\",,1," "one direct native call")
    require_row("census,\"callable_kind\",\"native\",,1," "one native target")
    require_row("census,\"frame_disposition\",\"no_child_native\",,1," "native no-child disposition")
    require_row("mechanics,\"call_window\",\"setup_swaps\",,1," "one native setup swap")
    require_row("mechanics,\"call_window\",\"attribution_degraded\",,0," "complete native attribution")
    require_row("unwind,\"signal\",\"events\",,1," "one native branch event")
    require_row("unwind,\"signal\",\"interrupted_native_windows_restored\",,1," "one native restored window")
    require_row("unwind,\"signal\",\"interrupted_native_slots_restored\",,1," "one native restored slot")
    require_row("unwind,\"signal\",\"restoration_failures\",,0," "zero native restoration failures")
else()
    message(FATAL_ERROR "unknown call census case: ${CASE}")
endif()
