X(INULL, 0, FMT_EMPTY, FLOW_NEXT, 0, "")
X(LOAD_REG_INT, 1, FMT_R_I, FLOW_NEXT, 0, "Load op1 with op2")
X(LOAD_REG_FLOAT, 2, FMT_R_F, FLOW_NEXT, 0, "Load op1 with op2")
X(LOAD_REG_STRING, 3, FMT_R_S, FLOW_NEXT, 0, "Load op1 with op2")
X(LOAD_REG_REG, 4, FMT_R_R, FLOW_NEXT, 0, "Load op1 with op2")
X(LOAD_REG_DECIMAL, 5, FMT_R_D, FLOW_NEXT, 0, "Load op1 with op2")
X(LOAD_INT_INT, 6, FMT_I_I, FLOW_NEXT, 0, "Load op1 with op2 (non symbolic registers)")
X(LOAD_INT_REG, 7, FMT_I_R, FLOW_NEXT, 0, "Load op1 with op2 (non symbolic registers)")
X(COPY_REG_REG, 8, FMT_R_R, FLOW_NEXT, 0, "Copy op2 to op1")
X(ICOPY_REG_REG, 9, FMT_R_R, FLOW_NEXT, 0, "Copy Integer op2 to op1")
X(FCOPY_REG_REG, 10, FMT_R_R, FLOW_NEXT, 0, "Copy Float op2 to op1")
X(SCOPY_REG_REG, 11, FMT_R_R, FLOW_NEXT, 0, "Copy String op2 to op1")
X(DCOPY_REG_REG, 12, FMT_R_R, FLOW_NEXT, 0, "Copy Decimal op2 to op1")
X(ACOPY_REG_REG, 13, FMT_R_R, FLOW_NEXT, 0, "Copy status Attributes op2 to op1")
X(NULL_REG, 14, FMT_R, FLOW_NEXT, 0, "Null (clear) op1")
X(IADD_REG_REG_REG, 15, FMT_R_R_R, FLOW_NEXT, 0, "Integer Add (op1=op2+op3)")
X(IADD_REG_REG_INT, 16, FMT_R_R_I, FLOW_NEXT, 0, "Integer Add (op1=op2+op3)")
X(ISUB_REG_REG_REG, 17, FMT_R_R_R, FLOW_NEXT, 0, "Integer Subtract (op1=op2-op3)")
X(ISUB_REG_REG_INT, 18, FMT_R_R_I, FLOW_NEXT, 0, "Integer Subtract (op1=op2-op3)")
X(ISUB_REG_INT_REG, 19, FMT_R_I_R, FLOW_NEXT, 0, "Integer Subtract (op1=op2-op3)")
X(IMULT_REG_REG_REG, 20, FMT_R_R_R, FLOW_NEXT, 0, "Integer Multiply (op1=op2*op3)")
X(IMULT_REG_REG_INT, 21, FMT_R_R_I, FLOW_NEXT, 0, "Integer Multiply (op1=op2*op3)")
X(IDIV_REG_REG_REG, 22, FMT_R_R_R, FLOW_NEXT, 0, "Integer Divide (op1=op2/op3)")
X(IDIV_REG_REG_INT, 23, FMT_R_R_I, FLOW_NEXT, 0, "Integer Divide (op1=op2/op3)")
X(IDIV_REG_INT_REG, 24, FMT_R_I_R, FLOW_NEXT, 0, "Integer Divide (op1=op2/op3)")
X(IMOD_REG_REG_REG, 25, FMT_R_R_R, FLOW_NEXT, 0, "Integer Modulo (op1=op2%op3)")
X(IMOD_REG_REG_INT, 26, FMT_R_R_I, FLOW_NEXT, 0, "Integer Modulo (op1=op2%op3)")
X(IMOD_REG_INT_REG, 27, FMT_R_I_R, FLOW_NEXT, 0, "Integer Modulo (op1=op2&op3)")
X(INC_REG, 28, FMT_R, FLOW_NEXT, 0, "Increment Int (op1++)")
X(DEC_REG, 29, FMT_R, FLOW_NEXT, 0, "Decrement Int (op1--)")
X(INC0, 30, FMT_EMPTY, FLOW_NEXT, 0, "Increment R0++ Int")
X(DEC0, 31, FMT_EMPTY, FLOW_NEXT, 0, "Decrement R0-- Int")
X(INC1, 32, FMT_EMPTY, FLOW_NEXT, 0, "Increment R1++ Int")
X(DEC1, 33, FMT_EMPTY, FLOW_NEXT, 0, "Decrement R1-- Int")
X(INC2, 34, FMT_EMPTY, FLOW_NEXT, 0, "Increment R2++ Int")
X(DEC2, 35, FMT_EMPTY, FLOW_NEXT, 0, "Decrement R2-- Int")
X(BR_ID, 36, FMT_L, FLOW_JUMP, 0, "Branch to op1")
X(BRT_ID_REG, 37, FMT_L_R, FLOW_COND, 0, "Branch to op1 if op2 true")
X(BRF_ID_REG, 38, FMT_L_R, FLOW_COND, 0, "Branch to op1 if op2 false")
X(BRTF_ID_ID_REG, 39, FMT_L_L_R, FLOW_COND, 0, "Branch to op1 if op3 true, otherwise branch to op2")
X(BEQ_ID_REG_REG, 40, FMT_L_R_R, FLOW_COND, 0, "if op2==op3 then goto op1")
X(BEQ_ID_REG_INT, 41, FMT_L_R_I, FLOW_COND, 0, "if op2==op3 then goto op1")
X(BNE_ID_REG_REG, 42, FMT_L_R_R, FLOW_COND, 0, "if op2!=op3 then goto op1")
X(BNE_ID_REG_INT, 43, FMT_L_R_I, FLOW_COND, 0, "if op2!=op3 then goto op1")
X(CALL_FUNC, 44, FMT_P, FLOW_NEXT, 0, "Call procedure (op1())")
X(CALL_REG_FUNC, 45, FMT_R_P, FLOW_NEXT, 0, "Call procedure (op1=op2())")
X(CALL_REG_FUNC_REG, 46, FMT_R_P_R, FLOW_NEXT, 0, "Call procedure (op1=op2(op3...) )")
X(DCALL_REG_REG_REG, 47, FMT_R_R_R, FLOW_NEXT, 0, "Dynamic call procedure (op1=op2(op3...) )")
X(RET, 48, FMT_EMPTY, FLOW_TERM, 0, "Return VOID")
X(RET_REG, 49, FMT_R, FLOW_TERM, 0, "Return op1")
X(RET_INT, 50, FMT_I, FLOW_TERM, 0, "Return op1")
X(RET_FLOAT, 51, FMT_F, FLOW_TERM, 0, "Return op1")
X(RET_STRING, 52, FMT_S, FLOW_TERM, 0, "Return op1")
X(EXIT, 53, FMT_EMPTY, FLOW_TERM, 0, "Exit")
X(EXIT_REG, 54, FMT_R, FLOW_TERM, 0, "Exit op1")
X(EXIT_INT, 55, FMT_I, FLOW_TERM, 0, "Exit op1")
X(RESERVED_056, 56, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_057, 57, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_058, 58, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_059, 59, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_060, 60, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_061, 61, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_062, 62, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_063, 63, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_064, 64, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_065, 65, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_066, 66, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_067, 67, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_068, 68, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_069, 69, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_070, 70, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_071, 71, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_072, 72, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_073, 73, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_074, 74, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_075, 75, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_076, 76, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_077, 77, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_078, 78, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_079, 79, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_080, 80, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_081, 81, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_082, 82, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_083, 83, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_084, 84, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_085, 85, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_086, 86, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_087, 87, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_088, 88, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_089, 89, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_090, 90, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_091, 91, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_092, 92, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_093, 93, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_094, 94, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_095, 95, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_096, 96, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_097, 97, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_098, 98, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_099, 99, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(IEQ_REG_REG_REG, 100, FMT_R_R_R, FLOW_NEXT, 0, "Int Equals op1=(op2==op3)")
X(IEQ_REG_REG_INT, 101, FMT_R_R_I, FLOW_NEXT, 0, "Int Equals op1=(op2==op3)")
X(INE_REG_REG_REG, 102, FMT_R_R_R, FLOW_NEXT, 0, "Int Not equals op1=(op2!=op3)")
X(INE_REG_REG_INT, 103, FMT_R_R_I, FLOW_NEXT, 0, "Int Not equals op1=(op2!=op3)")
X(IGT_REG_REG_REG, 104, FMT_R_R_R, FLOW_NEXT, 0, "Int Greater than op1=(op2>op3)")
X(IGT_REG_REG_INT, 105, FMT_R_R_I, FLOW_NEXT, 0, "Int Greater than op1=(op2>op3)")
X(IGT_REG_INT_REG, 106, FMT_R_I_R, FLOW_NEXT, 0, "Int Greater than op1=(op2>op3)")
X(IGTE_REG_REG_REG, 107, FMT_R_R_R, FLOW_NEXT, 0, "Int Greater than equals op1=(op2>=op3)")
X(IGTE_REG_REG_INT, 108, FMT_R_R_I, FLOW_NEXT, 0, "Int Greater than equals op1=(op2>=op3)")
X(IGTE_REG_INT_REG, 109, FMT_R_I_R, FLOW_NEXT, 0, "Int Greater than equals op1=(op2>=op3)")
X(ILT_REG_REG_REG, 110, FMT_R_R_R, FLOW_NEXT, 0, "Int Less than op1=(op2<op3)")
X(ILT_REG_REG_INT, 111, FMT_R_R_I, FLOW_NEXT, 0, "Int Less than op1=(op2<op3)")
X(ILT_REG_INT_REG, 112, FMT_R_I_R, FLOW_NEXT, 0, "Int Less than op1=(op2<op3)")
X(ILTE_REG_REG_REG, 113, FMT_R_R_R, FLOW_NEXT, 0, "Int Less than equals op1=(op2<=op3)")
X(ILTE_REG_REG_INT, 114, FMT_R_R_I, FLOW_NEXT, 0, "Int Less than equals op1=(op2<=op3)")
X(ILTE_REG_INT_REG, 115, FMT_R_I_R, FLOW_NEXT, 0, "Int Less than equals op1=(op2<=op3)")
X(SEQ_REG_REG_REG, 116, FMT_R_R_R, FLOW_NEXT, 0, "String Equals op1=(op2==op3)")
X(SEQ_REG_REG_STRING, 117, FMT_R_R_S, FLOW_NEXT, 0, "String Equals op1=(op2==op3)")
X(RSEQ_REG_REG_REG, 118, FMT_R_R_R, FLOW_NEXT, 0, "non strict String Equals op1=(op2=op3)")
X(RSEQ_REG_REG_STRING, 119, FMT_R_R_S, FLOW_NEXT, 0, "non strict String Equals op1=(op2=op3)")
X(SNE_REG_REG_REG, 120, FMT_R_R_R, FLOW_NEXT, 0, "String Not equals op1=(op2!=op3)")
X(SNE_REG_REG_STRING, 121, FMT_R_R_S, FLOW_NEXT, 0, "String Not equals op1=(op2!=op3)")
X(SGT_REG_REG_REG, 122, FMT_R_R_R, FLOW_NEXT, 0, "String Greater than op1=(op2>op3)")
X(SGT_REG_REG_STRING, 123, FMT_R_R_S, FLOW_NEXT, 0, "String Greater than op1=(op2>op3)")
X(SGT_REG_STRING_REG, 124, FMT_R_S_R, FLOW_NEXT, 0, "String Greater than op1=(op2>op3)")
X(SGTE_REG_REG_REG, 125, FMT_R_R_R, FLOW_NEXT, 0, "String Greater than equals op1=(op2>=op3)")
X(SGTE_REG_REG_STRING, 126, FMT_R_R_S, FLOW_NEXT, 0, "String Greater than equals op1=(op2>=op3)")
X(SGTE_REG_STRING_REG, 127, FMT_R_S_R, FLOW_NEXT, 0, "String Greater than equals op1=(op2>=op3)")
X(SLT_REG_REG_REG, 128, FMT_R_R_R, FLOW_NEXT, 0, "String Less than op1=(op2<op3)")
X(SLT_REG_REG_STRING, 129, FMT_R_R_S, FLOW_NEXT, 0, "String Less than op1=(op2<op3)")
X(SLT_REG_STRING_REG, 130, FMT_R_S_R, FLOW_NEXT, 0, "String Less than op1=(op2<op3)")
X(SLTE_REG_REG_REG, 131, FMT_R_R_R, FLOW_NEXT, 0, "String Less than equals op1=(op2<=op3)")
X(SLTE_REG_REG_STRING, 132, FMT_R_R_S, FLOW_NEXT, 0, "String Less than equals op1=(op2<=op3)")
X(SLTE_REG_STRING_REG, 133, FMT_R_S_R, FLOW_NEXT, 0, "String Less than equals op1=(op2<=op3)")
X(CONCAT_REG_REG_REG, 134, FMT_R_R_R, FLOW_NEXT, 0, "String Concat (op1=op2||op3)")
X(CONCAT_REG_REG_STRING, 135, FMT_R_R_S, FLOW_NEXT, 0, "String Concat (op1=op2||op3)")
X(CONCAT_REG_STRING_REG, 136, FMT_R_S_R, FLOW_NEXT, 0, "String Concat (op1=op2||op3)")
X(SCONCAT_REG_REG_REG, 137, FMT_R_R_R, FLOW_NEXT, 0, "String Concat with space (op1=op2||op3)")
X(SCONCAT_REG_REG_STRING, 138, FMT_R_R_S, FLOW_NEXT, 0, "String Concat with space (op1=op2||op3)")
X(SCONCAT_REG_STRING_REG, 139, FMT_R_S_R, FLOW_NEXT, 0, "String Concat with space (op1=op2||op3)")
X(APPENDCHAR_REG_REG, 140, FMT_R_R, FLOW_NEXT, 0, "Append Concat Char op2 (as int) on op1")
X(CONCCHAR_REG_REG_REG, 141, FMT_R_R_R, FLOW_NEXT, 0, "Concat Char op1 from op2 position op3")
X(SAPPEND_REG_REG, 142, FMT_R_R, FLOW_NEXT, 0, "String Append with space (op1=op1||op2)")
X(APPEND_REG_REG, 143, FMT_R_R, FLOW_NEXT, 0, "String Append (op1=op1||op2)")
X(TRIML_REG_REG, 144, FMT_R_R, FLOW_NEXT, 0, "Trim String (op1) from Left by (op2) Chars")
X(TRIMR_REG_REG, 145, FMT_R_R, FLOW_NEXT, 0, "Trim String (op1) from Right by (op2) Chars")
X(TRIML_REG_REG_REG, 146, FMT_R_R_R, FLOW_NEXT, 0, "Trim String (op2) from Left by (op3) Chars into op1")
X(TRIMR_REG_REG_REG, 147, FMT_R_R_R, FLOW_NEXT, 0, "Trim String (op2) from Right by (op3) Chars into op1")
X(TRUNC_REG_REG_REG, 148, FMT_R_R_R, FLOW_NEXT, 0, "Trunc String (op2) to (op3) Chars into op1")
X(STRLEN_REG_REG, 149, FMT_R_R, FLOW_NEXT, 0, "String Length op1 = length(op2)")
X(STRCHAR_REG_REG_REG, 150, FMT_R_R_R, FLOW_NEXT, 0, "op1 (as int) = op2[op3]")
X(STRCHAR_REG_REG, 151, FMT_R_R, FLOW_NEXT, 0, "op1 (as int) = op2[charpos]")
X(HEXCHAR_REG_REG_REG, 152, FMT_R_R_R, FLOW_NEXT, 0, "op1 (as hex) = op2[op3]")
X(POSCHAR_REG_REG_REG, 153, FMT_R_R_R, FLOW_NEXT, 0, "op1 = position of op3 in op2")
X(SETSTRPOS_REG_REG, 154, FMT_R_R, FLOW_NEXT, 0, "Set String (op1) charpos set to op2")
X(GETSTRPOS_REG_REG, 155, FMT_R_R, FLOW_NEXT, 0, "Get String (op2) charpos into op1")
X(SUBSTR_REG_REG_REG, 156, FMT_R_R_R, FLOW_NEXT, 0, "op1 = op2[charpos]...op2[charpos+op3-1]")
X(STRLOWER_REG_REG, 157, FMT_R_R, FLOW_NEXT, 0, "Set string to lower case value")
X(STRUPPER_REG_REG, 158, FMT_R_R, FLOW_NEXT, 0, "Set string to upper case value")
X(TRANSCHAR_REG_REG_REG, 159, FMT_R_R_R, FLOW_NEXT, 0, "replace op1 if it is in op3-list by char in op2-list")
X(DROPCHAR_REG_REG_REG, 160, FMT_R_R_R, FLOW_NEXT, 0, "set op1 from op2 after dropping all chars from op3")
X(SUBSTRING_REG_REG_REG, 161, FMT_R_R_R, FLOW_NEXT, 0, "set op1=substr(op2,op3) remaining string")
X(SUBSTCUT_REG_REG, 162, FMT_R_R, FLOW_NEXT, 0, "set op1=substr(op1,,op2) cuts off op1 after position op3")
X(PADSTR_REG_REG_REG, 163, FMT_R_R_R, FLOW_NEXT, 0, "set op1=op2[repeated op3 times]")
X(STRPOS_REG_REG_REG, 164, FMT_R_R_R, FLOW_NEXT, 0, "op1 is position of op2 in op3")
X(FNDBLNK_REG_REG_REG, 165, FMT_R_R_R, FLOW_NEXT, 0, "op1 = find next blank in op2[op3] and behind")
X(FNDNBLNK_REG_REG_REG, 166, FMT_R_R_R, FLOW_NEXT, 0, "op1 = find next next non blank in op2[op3] and behind")
X(GETBYTE_REG_REG_REG, 167, FMT_R_R_R, FLOW_NEXT, 0, "get byte  (op1=op2(op3)")
X(IAND_REG_REG_REG, 168, FMT_R_R_R, FLOW_NEXT, 0, "bit wise and of 2 integers (op1=op2&op3)")
X(IAND_REG_REG_INT, 169, FMT_R_R_I, FLOW_NEXT, 0, "bit wise and of 2 integers (op1=op2&op3)")
X(IOR_REG_REG_REG, 170, FMT_R_R_R, FLOW_NEXT, 0, "bit wise or of 2 integers (op1=op2|op3)")
X(IOR_REG_REG_INT, 171, FMT_R_R_I, FLOW_NEXT, 0, "bit wise or of 2 integers (op1=op2|op3)")
X(IXOR_REG_REG_REG, 172, FMT_R_R_R, FLOW_NEXT, 0, "bit wise exclusive OR of 2 integers (op1=op2^op3)")
X(IXOR_REG_REG_INT, 173, FMT_R_R_I, FLOW_NEXT, 0, "bit wise exclusive OR of 2 integers (op1=op2^op3)")
X(ISHL_REG_REG_REG, 174, FMT_R_R_R, FLOW_NEXT, 0, "bit wise shift logical left of integer (op1=op2<<op3)")
X(ISHL_REG_REG_INT, 175, FMT_R_R_I, FLOW_NEXT, 0, "bit wise shift logical left of integer (op1=op2<<op3)")
X(ISHR_REG_REG_REG, 176, FMT_R_R_R, FLOW_NEXT, 0, "bit wise shift logical right of integer (op1=op2>>op3)")
X(ISHR_REG_REG_INT, 177, FMT_R_R_I, FLOW_NEXT, 0, "bit wise shift logical right of integer (op1=op2>>op3)")
X(INOT_REG_REG, 178, FMT_R_R, FLOW_NEXT, 0, "inverts all bits of an integer (op1=~op2)")
X(INOT_REG_INT, 179, FMT_R_I, FLOW_NEXT, 0, "inverts all bits of an integer (op1=~op2)")
X(AND_REG_REG_REG, 180, FMT_R_R_R, FLOW_NEXT, 0, "Logical (int) and op1=(op2 && op3)")
X(OR_REG_REG_REG, 181, FMT_R_R_R, FLOW_NEXT, 0, "Logical (int) or op1=(op2 || op3)")
X(NOT_REG_REG, 182, FMT_R_R, FLOW_NEXT, 0, "Logical (int) not op1=!op2")
X(RESERVED_183, 183, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_184, 184, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_185, 185, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_186, 186, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_187, 187, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_188, 188, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_189, 189, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_190, 190, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_191, 191, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_192, 192, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_193, 193, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_194, 194, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_195, 195, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_196, 196, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_197, 197, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_198, 198, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_199, 199, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(LINKATTR_REG_REG_REG, 200, FMT_R_R_R, FLOW_NEXT, 0, "Link attribute op3 of op2 to op1")
X(LINKATTR_REG_REG_INT, 201, FMT_R_R_I, FLOW_NEXT, 0, "Link attribute op3 of op2 to op1")
X(LINKATTR1_REG_REG_REG, 202, FMT_R_R_R, FLOW_NEXT, 0, "Link attribute op3 (1 base) of op2 to op1")
X(LINKATTR1_REG_REG_INT, 203, FMT_R_R_I, FLOW_NEXT, 0, "Link attribute op3 (1 base) of op2 to op1")
X(LINKTOATTR_REG_REG_REG, 204, FMT_R_R_R, FLOW_NEXT, 0, "Link op3 to attribute op1 of op2 ")
X(LINKTOATTR_INT_REG_REG, 205, FMT_I_R_R, FLOW_NEXT, 0, "Link op3 to attribute op1 of op2 ")
X(LINKTOATTR1_REG_REG_REG, 206, FMT_R_R_R, FLOW_NEXT, 0, "Link op3 to attribute op1 (1 base) of op2 ")
X(LINKTOATTR1_INT_REG_REG, 207, FMT_I_R_R, FLOW_NEXT, 0, "Link op3 to attribute op1 (1 base) of op2 ")
X(UNLINKATTR_REG_REG, 208, FMT_R_R, FLOW_NEXT, 0, "Unlink attribute op1 of op2")
X(UNLINKATTR_INT_REG, 209, FMT_I_R, FLOW_NEXT, 0, "Unlink attribute op1 of op2")
X(UNLINKATTR1_REG_REG, 210, FMT_R_R, FLOW_NEXT, 0, "Unlink attribute op1 (1 base) of op2")
X(UNLINKATTR1_INT_REG, 211, FMT_I_R, FLOW_NEXT, 0, "Unlink attribute op1 (1 base) of op2")
X(LINK_REG_REG, 212, FMT_R_R, FLOW_NEXT, 0, "Link op2 to op1")
X(UNLINK_REG, 213, FMT_R, FLOW_NEXT, 0, "Unlink op1")
X(GETATTRS_REG_REG, 214, FMT_R_R, FLOW_NEXT, 0, "get number attributes op1 = op2.num_attributes")
X(GETATTRS_REG_REG_INT, 215, FMT_R_R_I, FLOW_NEXT, 0, "get number attributes op1 = op2.num_attributes + op3")
X(SETATTRS_REG_REG, 216, FMT_R_R, FLOW_NEXT, 0, "set number attributes op1.num_attributes = op2")
X(SETATTRS_REG_INT, 217, FMT_R_I, FLOW_NEXT, 0, "set number attributes op1.num_attributes = op2")
X(SETATTRS_REG_REG_INT, 218, FMT_R_R_I, FLOW_NEXT, 0, "set number attributes op1.num_attributes = op2 + op3")
X(SETATTRS_REG_INT_INT, 219, FMT_R_I_I, FLOW_NEXT, 0, "set number attributes op1.num_attributes = op2 + op3")
X(GETABUFS_REG_REG, 220, FMT_R_R, FLOW_NEXT, 0, "get attribute buffer size op1 = op2.max_attributes")
X(MINATTRS_REG_REG, 221, FMT_R_R, FLOW_NEXT, 0, "ensure min number attributes op1.num_attributes >= op2")
X(MINATTRS_REG_INT, 222, FMT_R_I, FLOW_NEXT, 0, "ensure min number attributes op1.num_attributes >= op2")
X(MINATTRS_REG_REG_INT, 223, FMT_R_R_I, FLOW_NEXT, 0, "ensure min number attributes op1.num_attributes >= op2 + op3")
X(MINATTRS_REG_INT_INT, 224, FMT_R_I_I, FLOW_NEXT, 0, "ensure min number attributes op1.num_attributes >= op2 + op3")
X(BTOI_REG, 225, FMT_R, FLOW_COND, 0, "Set register integer value from its boolean value")
X(BTOD_REG, 226, FMT_R, FLOW_COND, 0, "Set register decimal value from its boolean value")
X(BTOF_REG, 227, FMT_R, FLOW_COND, 0, "Set register float value from its boolean value")
X(BTOS_REG, 228, FMT_R, FLOW_COND, 0, "Set register string value from its boolean value")
X(ITOS_REG, 229, FMT_R, FLOW_NEXT, 0, "Set register string value from its int value")
X(FTOS_REG, 230, FMT_R, FLOW_NEXT, 0, "Set register string value from its float value")
X(ITOF_REG, 231, FMT_R, FLOW_NEXT, 0, "Set register float value from its int value")
X(FTOI_REG, 232, FMT_R, FLOW_NEXT, 0, "Set register int value from its float value")
X(FTOB_REG, 233, FMT_R, FLOW_NEXT, 0, "Set register boolean (int 1 or 0) value from its float value")
X(ITOB_REG, 234, FMT_R, FLOW_NEXT, 0, "Set register boolean (int 1 or 0) value from its integer value")
X(STOB_REG, 235, FMT_R, FLOW_NEXT, 0, "Set register boolean (int 1 or 0) value from its string value")
X(STOF_REG, 236, FMT_R, FLOW_NEXT, 0, "Set register float value from its string value")
X(STOI_REG, 237, FMT_R, FLOW_NEXT, 0, "Set register int value from its string value")
X(STOD_REG, 238, FMT_R, FLOW_NEXT, 0, "Convert Decimal String to Decimal Number op1=s2dec(op2)")
X(DTOS_REG, 239, FMT_R, FLOW_NEXT, 0, "Convert Decimal Number to Decimal String op1=dec2s(op2)")
X(DTOI_REG, 240, FMT_R, FLOW_NEXT, 0, "Convert Decimal Number to Integer op1=dec2s(op2)")
X(DTOB_REG, 241, FMT_R, FLOW_NEXT, 0, "Convert Decimal Number to Boolean op1=dec2s(op2)")
X(ITOD_REG, 242, FMT_R, FLOW_NEXT, 0, "Convert Integer to Decimal Number op1=s2dec(op2)")
X(FTOD_REG, 243, FMT_R, FLOW_NEXT, 0, "Convert Float to Decimal Number op1=f2dec(op2)")
X(DTOF_REG, 244, FMT_R, FLOW_NEXT, 0, "Convert Decimal Number to Float op1=f2dec(op2)")
X(SETNUMDGTS_REG, 245, FMT_R, FLOW_NEXT, 0, "Set Numeric Digits digits=op1 (>4)")
X(SETNUMDGTS_INT, 246, FMT_I, FLOW_NEXT, 0, "Set Numeric Digits digits=op1 (>4)")
X(GETNUMDGTS_REG, 247, FMT_R, FLOW_NEXT, 0, "Get Numeric Digits op1=digits")
X(SETNUMFUZ_REG, 248, FMT_R, FLOW_NEXT, 0, "Set Numeric Fuzz digits=op1 (>=0)")
X(SETNUMFUZ_INT, 249, FMT_I, FLOW_NEXT, 0, "Set Numeric Fuzz digits=op1 (>=0)")
X(GETNUMFUZ_REG, 250, FMT_R, FLOW_NEXT, 0, "Get Numeric Fuzz op1=digits")
X(SETNUMFRM_REG, 251, FMT_R, FLOW_NEXT, 0, "Set Numeric Form=op1 (1=sci,2=eng)")
X(SETNUMFRM_INT, 252, FMT_I, FLOW_NEXT, 0, "Set Numeric Form=op1 (1=sci,2=eng)")
X(GETNUMFRM_REG, 253, FMT_R, FLOW_NEXT, 0, "Get Numeric Form=op1 (1=sci,2=eng)")
X(SETNUMCAS_REG, 254, FMT_R, FLOW_NEXT, 0, "Set Numeric Case=op1 (1=lower,2=upper)")
X(SETNUMCAS_INT, 255, FMT_I, FLOW_NEXT, 0, "Set Numeric Case=op1 (1=lower,2=upper)")
X(GETNUMCAS_REG, 256, FMT_R, FLOW_NEXT, 0, "Get Numeric Case=op1 (1=lower,2=upper)")
X(SETNUMSTD_REG, 257, FMT_R, FLOW_NEXT, 0, "Set Numeric Standard=op1 (1=common,2=classic)")
X(SETNUMSTD_INT, 258, FMT_I, FLOW_NEXT, 0, "Set Numeric Standard=op1 (1=common,2=classic)")
X(GETNUMSTD_REG, 259, FMT_R, FLOW_NEXT, 0, "Get Numeric Standard=op1 (1=common,2=classic)")
X(NUMSCI_INT_INT_INT, 260, FMT_I_I_I, FLOW_NEXT, 0, "Setup Scientific Numeric digits=op1, case=op2, std=op3, fuzz=0, form=sci")
X(NUMENG_INT_INT_INT, 261, FMT_I_I_I, FLOW_NEXT, 0, "Setup Engineering Numeric digits=op1, case=op2, std=op3, fuzz=0, form=eng")
X(FFORMAT_REG_REG_REG, 262, FMT_R_R_R, FLOW_NEXT, 0, "DEPRECATED use fextr. Set string value from float value using a format string")
X(RESERVED_263, 263, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_264, 264, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_265, 265, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_266, 266, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_267, 267, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_268, 268, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_269, 269, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_270, 270, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_271, 271, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_272, 272, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_273, 273, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_274, 274, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_275, 275, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_276, 276, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_277, 277, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_278, 278, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_279, 279, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_280, 280, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_281, 281, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_282, 282, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_283, 283, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_284, 284, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_285, 285, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_286, 286, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_287, 287, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_288, 288, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_289, 289, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_290, 290, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_291, 291, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_292, 292, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_293, 293, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_294, 294, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_295, 295, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_296, 296, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_297, 297, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_298, 298, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_299, 299, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(FADD_REG_REG_REG, 300, FMT_R_R_R, FLOW_NEXT, 0, "Float Add (op1=op2+op3)")
X(FADD_REG_REG_FLOAT, 301, FMT_R_R_F, FLOW_NEXT, 0, "Float Add (op1=op2+op3)")
X(FSUB_REG_REG_REG, 302, FMT_R_R_R, FLOW_NEXT, 0, "Float Subtract (op1=op2-op3)")
X(FSUB_REG_REG_FLOAT, 303, FMT_R_R_F, FLOW_NEXT, 0, "Float Subtract (op1=op2-op3)")
X(FSUB_REG_FLOAT_REG, 304, FMT_R_F_R, FLOW_NEXT, 0, "Float Subtract (op1=op2-op3)")
X(FMULT_REG_REG_REG, 305, FMT_R_R_R, FLOW_NEXT, 0, "Float Multiply (op1=op2*op3)")
X(FMULT_REG_REG_FLOAT, 306, FMT_R_R_F, FLOW_NEXT, 0, "Float Multiply (op1=op2*op3)")
X(FDIV_REG_REG_REG, 307, FMT_R_R_R, FLOW_NEXT, 0, "Float Divide (op1=op2/op3)")
X(FDIV_REG_REG_FLOAT, 308, FMT_R_R_F, FLOW_NEXT, 0, "Float Divide (op1=op2/op3)")
X(FDIV_REG_FLOAT_REG, 309, FMT_R_F_R, FLOW_NEXT, 0, "Float Divide (op1=op2/op3)")
X(FIDIV_REG_REG_REG, 310, FMT_R_R_R, FLOW_NEXT, 0, "Integer Divide with Floats (op1=op2/op3)")
X(FIDIV_REG_REG_FLOAT, 311, FMT_R_R_F, FLOW_NEXT, 0, "Integer Divide with Floats (op1=op2/op3)")
X(FIDIV_REG_FLOAT_REG, 312, FMT_R_F_R, FLOW_NEXT, 0, "Integer Divide with Floats (op1=op2/op3)")
X(FMOD_REG_REG_REG, 313, FMT_R_R_R, FLOW_NEXT, 0, "Float Modulo (op1=op2%op3)")
X(FMOD_REG_REG_FLOAT, 314, FMT_R_R_F, FLOW_NEXT, 0, "Float Modulo (op1=op2%op3)")
X(FMOD_REG_FLOAT_REG, 315, FMT_R_F_R, FLOW_NEXT, 0, "Float Modulo (op1=op2&op3)")
X(FEQ_REG_REG_REG, 316, FMT_R_R_R, FLOW_NEXT, 0, "Float Equals op1=(op2==op3)")
X(FEQ_REG_REG_FLOAT, 317, FMT_R_R_F, FLOW_NEXT, 0, "Float Equals op1=(op2==op3)")
X(FNE_REG_REG_REG, 318, FMT_R_R_R, FLOW_NEXT, 0, "Float Not equals op1=(op2!=op3)")
X(FNE_REG_REG_FLOAT, 319, FMT_R_R_F, FLOW_NEXT, 0, "Float Not equals op1=(op2!=op3)")
X(FGT_REG_REG_REG, 320, FMT_R_R_R, FLOW_NEXT, 0, "Float Greater than op1=(op2>op3)")
X(FGT_REG_REG_FLOAT, 321, FMT_R_R_F, FLOW_NEXT, 0, "Float Greater than op1=(op2>op3)")
X(FGT_REG_FLOAT_REG, 322, FMT_R_F_R, FLOW_NEXT, 0, "Float Greater than op1=(op2>op3)")
X(FGTE_REG_REG_REG, 323, FMT_R_R_R, FLOW_NEXT, 0, "Float Greater than equals op1=(op2>=op3)")
X(FGTE_REG_REG_FLOAT, 324, FMT_R_R_F, FLOW_NEXT, 0, "Float Greater than equals op1=(op2>=op3)")
X(FGTE_REG_FLOAT_REG, 325, FMT_R_F_R, FLOW_NEXT, 0, "Float Greater than equals op1=(op2>=op3)")
X(FLT_REG_REG_REG, 326, FMT_R_R_R, FLOW_NEXT, 0, "Float Less than op1=(op2<op3)")
X(FLT_REG_REG_FLOAT, 327, FMT_R_R_F, FLOW_NEXT, 0, "Float Less than op1=(op2<op3)")
X(FLT_REG_FLOAT_REG, 328, FMT_R_F_R, FLOW_NEXT, 0, "Float Less than op1=(op2<op3)")
X(FLTE_REG_REG_REG, 329, FMT_R_R_R, FLOW_NEXT, 0, "Float Less than equals op1=(op2<=op3)")
X(FLTE_REG_REG_FLOAT, 330, FMT_R_R_F, FLOW_NEXT, 0, "Float Less than equals op1=(op2<=op3)")
X(FLTE_REG_FLOAT_REG, 331, FMT_R_F_R, FLOW_NEXT, 0, "Float Less than equals op1=(op2<=op3)")
X(FGTBR_ID_REG_REG, 332, FMT_L_R_R, FLOW_NEXT, 0, "Float Greater than if (op2>op3) goto op1")
X(FLTBR_ID_REG_REG, 333, FMT_L_R_R, FLOW_NEXT, 0, "Float Less than if (op2<op3) goto op1")
X(FPOW_REG_REG_REG, 334, FMT_R_R_R, FLOW_NEXT, 0, "op1=op2**op3")
X(FPOW_REG_REG_FLOAT, 335, FMT_R_R_F, FLOW_NEXT, 0, "op1=op2**op3")
X(FPOW_REG_FLOAT_REG, 336, FMT_R_F_R, FLOW_NEXT, 0, "op1=op2**op3")
X(FSEX_REG, 337, FMT_R, FLOW_NEXT, 0, "float op1 = -op1 (sign change)")
X(FEXTR_REG_REG_REG, 338, FMT_R_R_R, FLOW_NEXT, 0, "op3 float extracted to op1 string coefficient and op2 int decimal exponent")
X(IPOW_REG_REG_REG, 339, FMT_R_R_R, FLOW_NEXT, 0, "op1=op2**op3")
X(IPOW_REG_REG_INT, 340, FMT_R_R_I, FLOW_NEXT, 0, "op1=op2**op3")
X(IPOW_REG_INT_REG, 341, FMT_R_I_R, FLOW_NEXT, 0, "op1=op2**op3")
X(ISEX_REG, 342, FMT_R, FLOW_NEXT, 0, "dec op1 = -op1 (sign change)")
X(IGTBR_ID_REG_REG, 343, FMT_L_R_R, FLOW_NEXT, 0, "Int Greater than if (op2>op3) goto op1")
X(ILTBR_ID_REG_REG, 344, FMT_L_R_R, FLOW_NEXT, 0, "Int Less than if (op2<op3) goto op1")
X(BCT_ID_REG, 345, FMT_L_R, FLOW_COND, 0, "dec op2; if op2>0; goto op1(if true)")
X(BCT_ID_REG_REG, 346, FMT_L_R_R, FLOW_COND, 0, "dec op2; inc op3, if op2>0; goto op1(if true)")
X(BCTNM_ID_REG, 347, FMT_L_R, FLOW_COND, 0, "dec op2; if op2>=0; goto op1(if true)")
X(BCTNM_ID_REG_REG, 348, FMT_L_R_R, FLOW_COND, 0, "dec op2; inc op3, if op2>=0; goto op1(if true)")
X(BCTP_ID_REG, 349, FMT_L_R, FLOW_COND, 0, "inc op2; goto op1")
X(BCF_ID_REG, 350, FMT_L_R, FLOW_COND, 0, "if op2=0 goto op1(if false) else dec op2")
X(BCF_ID_REG_REG, 351, FMT_L_R_R, FLOW_COND, 0, "if op2=0 goto op1(if false) else dec op2 and inc op3")
X(BGT_ID_REG_REG, 352, FMT_L_R_R, FLOW_COND, 0, "if op2>op3 then goto op1")
X(BGT_ID_REG_INT, 353, FMT_L_R_I, FLOW_COND, 0, "if op2>op3 then goto op1")
X(BGE_ID_REG_REG, 354, FMT_L_R_R, FLOW_COND, 0, "if op2>=op3 then goto op1")
X(BGE_ID_REG_INT, 355, FMT_L_R_I, FLOW_COND, 0, "if op2>=op3 then goto op1")
X(BLT_ID_REG_REG, 356, FMT_L_R_R, FLOW_COND, 0, "if op2<op3 then goto op1")
X(BLT_ID_REG_INT, 357, FMT_L_R_I, FLOW_COND, 0, "if op2<op3 then goto op1")
X(BLE_ID_REG_REG, 358, FMT_L_R_R, FLOW_COND, 0, "if op2<=op3 then goto op1")
X(BLE_ID_REG_INT, 359, FMT_L_R_I, FLOW_COND, 0, "if op2<=op3 then goto op1")
X(DADD_REG_REG_REG, 360, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Add (op1=op2-op3)")
X(DADD_REG_REG_DECIMAL, 361, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Add (op1=op2-op3)")
X(DSUB_REG_REG_REG, 362, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Subtract (op1=op2-op3)")
X(DSUB_REG_REG_DECIMAL, 363, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Subtract (op1=op2-op3)")
X(DSUB_REG_DECIMAL_REG, 364, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Subtract (op1=op2-op3)")
X(DMULT_REG_REG_REG, 365, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Multiply (op1=op2*op3)")
X(DMULT_REG_REG_DECIMAL, 366, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Multiply (op1=op2*op3)")
X(DDIV_REG_REG_REG, 367, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Divide (op1=op2/op3)")
X(DDIV_REG_REG_DECIMAL, 368, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Divide (op1=op2/op3)")
X(DDIV_REG_DECIMAL_REG, 369, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Divide (op1=op2/op3)")
X(DIDIV_REG_REG_REG, 370, FMT_R_R_R, FLOW_NEXT, 0, "Integer Divide with Decimals (op1=op2/op3)")
X(DIDIV_REG_REG_DECIMAL, 371, FMT_R_R_D, FLOW_NEXT, 0, "Integer Divide with Decimals (op1=op2/op3)")
X(DIDIV_REG_DECIMAL_REG, 372, FMT_R_D_R, FLOW_NEXT, 0, "Integer Divide with Decimals (op1=op2/op3)")
X(DMOD_REG_REG_REG, 373, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Modulo (op1=op2%op3)")
X(DMOD_REG_REG_DECIMAL, 374, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Modulo (op1=op2%op3)")
X(DMOD_REG_DECIMAL_REG, 375, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Modulo (op1=op2&op3)")
X(DEQ_REG_REG_REG, 376, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Equals op1=(op2==op3)")
X(DEQ_REG_REG_DECIMAL, 377, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Equals op1=(op2==op3)")
X(DNE_REG_REG_REG, 378, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Not equals op1=(op2!=op3)")
X(DNE_REG_REG_DECIMAL, 379, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Not equals op1=(op2!=op3)")
X(DGT_REG_REG_REG, 380, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Greater than op1=(op2>op3)")
X(DGT_REG_REG_DECIMAL, 381, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Greater than op1=(op2>op3)")
X(DGT_REG_DECIMAL_REG, 382, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Greater than op1=(op2>op3)")
X(DGTE_REG_REG_REG, 383, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Greater than equals op1=(op2>=op3)")
X(DGTE_REG_REG_DECIMAL, 384, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Greater than equals op1=(op2>=op3)")
X(DGTE_REG_DECIMAL_REG, 385, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Greater than equals op1=(op2>=op3)")
X(DLT_REG_REG_REG, 386, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Less than op1=(op2<op3)")
X(DLT_REG_REG_DECIMAL, 387, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Less than op1=(op2<op3)")
X(DLT_REG_DECIMAL_REG, 388, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Less than op1=(op2<op3)")
X(DLTE_REG_REG_REG, 389, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Less than equals op1=(op2<=op3)")
X(DLTE_REG_REG_DECIMAL, 390, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Less than equals op1=(op2<=op3)")
X(DLTE_REG_DECIMAL_REG, 391, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Less than equals op1=(op2<=op3)")
X(DGTBR_ID_REG_REG, 392, FMT_L_R_R, FLOW_NEXT, 0, "Decimal Greater than if (op2>op3) goto op1")
X(DLTBR_ID_REG_REG, 393, FMT_L_R_R, FLOW_NEXT, 0, "Decimal Less than if (op2<op3) goto op1")
X(DEQBR_ID_REG_REG, 394, FMT_L_R_R, FLOW_NEXT, 0, "Decimal Equal if (op2=op3) goto op1")
X(DPOW_REG_REG_REG, 395, FMT_R_R_R, FLOW_NEXT, 0, "op1=op2**op3")
X(DPOW_REG_REG_DECIMAL, 396, FMT_R_R_D, FLOW_NEXT, 0, "op1=op2**op3")
X(DPOW_REG_DECIMAL_REG, 397, FMT_R_D_R, FLOW_NEXT, 0, "op1=op2**op3")
X(DSEX_REG, 398, FMT_R, FLOW_NEXT, 0, "Decimal op1 = -op1 (sign change)")
X(DEXTR_REG_REG_REG, 399, FMT_R_R_R, FLOW_NEXT, 0, "op3 decimal extracted to op1 string coefficient and op2 int decimal exponent")
X(DECPLNM_REG_REG_REG, 400, FMT_R_R_R, FLOW_NEXT, 0, "Get Decimal Plugin Name op1=name op2=description op3=version")
X(RESERVED_401, 401, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_402, 402, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_403, 403, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_404, 404, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_405, 405, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_406, 406, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_407, 407, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_408, 408, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_409, 409, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_410, 410, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_411, 411, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_412, 412, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_413, 413, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_414, 414, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_415, 415, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_416, 416, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_417, 417, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_418, 418, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_419, 419, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_420, 420, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_421, 421, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_422, 422, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_423, 423, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_424, 424, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_425, 425, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_426, 426, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_427, 427, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_428, 428, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_429, 429, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_430, 430, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_431, 431, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_432, 432, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_433, 433, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_434, 434, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_435, 435, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_436, 436, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_437, 437, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_438, 438, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_439, 439, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_440, 440, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_441, 441, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_442, 442, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_443, 443, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_444, 444, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_445, 445, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_446, 446, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_447, 447, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_448, 448, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(RESERVED_449, 449, FMT_EMPTY, FLOW_NEXT, 0, "Reserved")
X(SAY_REG, 450, FMT_R, FLOW_NEXT, 0, "Say op1")
X(SAYX_REG, 451, FMT_R, FLOW_NEXT, 0, "Say op1 without line feed")
X(SAYX_STRING, 452, FMT_S, FLOW_NEXT, 0, "Say op1 (as string) without line feed")
X(SAY_INT, 453, FMT_I, FLOW_NEXT, 0, "Say op1")
X(SAY_FLOAT, 454, FMT_F, FLOW_NEXT, 0, "Say op1")
X(SAY_STRING, 455, FMT_S, FLOW_NEXT, 0, "Say op1")
X(SAY_CHAR, 456, FMT_C, FLOW_NEXT, 0, "Say op1")
X(READLINE_REG, 457, FMT_R, FLOW_NEXT, 0, "Read Line to op1")
X(TIME_REG, 458, FMT_R, FLOW_NEXT, 0, "Put time into op1")
X(MTIME_REG, 459, FMT_R, FLOW_NEXT, 0, "Put time in microseconds into op1")
X(XTIME_REG_STRING, 460, FMT_R_S, FLOW_NEXT, 0, "put special time properties into op1")
X(RXVERS_REG, 461, FMT_R, FLOW_NEXT, 0, "get version, op1=version details")
X(GETENV_REG_REG, 462, FMT_R_R, FLOW_NEXT, 0, "get environment variable, op1=env[op2]")
X(GETENV_REG_STRING, 463, FMT_R_S, FLOW_NEXT, 0, "get environment variable, op1=env[op2]")
X(IRAND_REG_REG, 464, FMT_R_R, FLOW_NEXT, 0, "random number random, op1=irand(op2)")
X(IRAND_REG_INT, 465, FMT_R_I, FLOW_NEXT, 0, "random number random, op1=irand(op2)")
X(SPAWN_REG_REG_REG, 466, FMT_R_R_R, FLOW_NEXT, 0, "Spawn Process op1 = exec op2 redirect op3")
X(REDIR2STR_REG_REG, 467, FMT_R_R, FLOW_NEXT, 0, "Redirect op1 -> string op2")
X(REDIR2ARR_REG_REG, 468, FMT_R_R, FLOW_NEXT, 0, "Redirect op1 -> array op2")
X(STR2REDIR_REG_REG, 469, FMT_R_R, FLOW_NEXT, 0, "Redirect op1 <- string op2")
X(ARR2REDIR_REG_REG, 470, FMT_R_R, FLOW_NEXT, 0, "Redirect op1 <- array op2")
X(NULLREDIR_REG, 471, FMT_R, FLOW_NEXT, 0, "Redirect op1 = to/from null")
X(FOPEN_REG_REG_REG, 472, FMT_R_R_R, FLOW_NEXT, 0, "op1 file*(int) = fopen filename op2(string) mode op3(string)")
X(FCLOSE_REG_REG, 473, FMT_R_R, FLOW_NEXT, 0, "op1 rc(int) = fclose op2 file*(int)")
X(FFLUSH_REG_REG, 474, FMT_R_R, FLOW_NEXT, 0, "op1 rc(int) = fflush op2 file*(int)")
X(FREADB_REG_REG_REG, 475, FMT_R_R_R, FLOW_NEXT, 0, "op1(binary) = fread op2 file*(int) op3 bytes(int)")
X(FREADLINE_REG_REG, 476, FMT_R_R, FLOW_NEXT, 0, "op1 (string) = read until newline op2 file*(int)")
X(FREADBYTE_REG_REG, 477, FMT_R_R, FLOW_NEXT, 0, "op1 (int) = read byte op2 file*(int)")
X(FREADCDPT_REG_REG, 478, FMT_R_R, FLOW_NEXT, 0, "op1 (string and int) = read codepoint op2 file*(int)")
X(FWRITE_REG_REG, 479, FMT_R_R, FLOW_NEXT, 0, "fwrite to op1 file*(int) from op2(string)")
X(FWRITEB_REG_REG, 480, FMT_R_R, FLOW_NEXT, 0, "fwrite to op1 file*(int) from op2(binary)")
X(FWRITEBYTE_REG_REG, 481, FMT_R_R, FLOW_NEXT, 0, "write byte to op1 file*(int) op2 source(int)")
X(FWRITECDPT_REG_REG, 482, FMT_R_R, FLOW_NEXT, 0, "write codepoint to op1 file*(int) op2 source(int)")
X(FCLEARERR_REG, 483, FMT_R, FLOW_NEXT, 0, "clearerr op1 file*(int)")
X(FEOF_REG_REG, 484, FMT_R_R, FLOW_NEXT, 0, "op1 rc(int) = feof op2 file*(int)")
X(FERROR_REG_REG, 485, FMT_R_R, FLOW_NEXT, 0, "op1 rc(int) = ferror op2 file*(int)")
X(SIGNAL_STRING, 486, FMT_S, FLOW_NEXT, 0, "Signal type op1")
X(SIGNALT_STRING_REG, 487, FMT_S_R, FLOW_NEXT, 0, "Signal type op1 if op2 true")
X(SIGNALF_STRING_REG, 488, FMT_S_R, FLOW_NEXT, 0, "Signal type op1 if op2 false")
X(SIGNAL_STRING_STRING, 489, FMT_S_S, FLOW_NEXT, 0, "Signal type op1 (message op2)")
X(SIGNAL_STRING_REG, 490, FMT_S_R, FLOW_NEXT, 0, "Signal type op1 (payload op2)")
X(SIGNALT_STRING_STRING_REG, 491, FMT_S_S_R, FLOW_NEXT, 0, "Signal type op1 (message op2) if op3 true")
X(SIGNALF_STRING_STRING_REG, 492, FMT_S_S_R, FLOW_NEXT, 0, "Signal type op1 (message op2) if op3 false")
X(BPON_FUNC, 493, FMT_P, FLOW_NEXT, 0, "Enable Breakpoints with op1 handler")
X(BPON, 494, FMT_EMPTY, FLOW_NEXT, 0, "Enable Breakpoints with existing handler")
X(BPOFF, 495, FMT_EMPTY, FLOW_NEXT, 0, "Disable Breakpoints")
X(SIGIGNORE_STRING, 496, FMT_S, FLOW_NEXT, 0, "Set Signal op1 Handle to Ignore")
X(SIGHALT_STRING, 497, FMT_S, FLOW_NEXT, 0, "Set Signal op1 Handle to Halt")
X(SIGSHALT_STRING, 498, FMT_S, FLOW_NEXT, 0, "Set Signal op1 Handle to Silent Halt")
X(SIGBR_ID_STRING, 499, FMT_L_S, FLOW_NEXT, 0, "Set Signal op2 Handle to Branch to op1")
X(SIGCALL_FUNC_STRING, 500, FMT_P_S, FLOW_NEXT, 0, "Set Signal op2 Handle to Call op1")
X(SIGCALLBR_ID_FUNC_STRING, 501, FMT_L_P_S, FLOW_NEXT, 0, "Set Signal op3 Handle to Call op2 returning to op1")
X(SIGRET_STRING, 502, FMT_S, FLOW_NEXT, 0, "Set Signal op1 Handle to Return")
X(ICHKRNG_REG_INT_INT, 503, FMT_R_I_I, FLOW_NEXT, 0, "if op1<op2 | op1>op3 signal OUT_OF_RANGE")
X(ICHKRNG_REG_INT_REG, 504, FMT_R_I_R, FLOW_NEXT, 0, "if op1<op2 | op1>op3 signal OUT_OF_RANGE")
X(ICHKRNG_REG_REG_REG, 505, FMT_R_R_R, FLOW_NEXT, 0, "if op1<op2 | op1>op3 signal OUT_OF_RANGE")
X(ICHKRNG_INT_INT_REG, 506, FMT_I_I_R, FLOW_NEXT, 0, "if op1<op2 | op1>op3 signal OUT_OF_RANGE")
X(ICHKRNG_INT_REG_REG, 507, FMT_I_R_R, FLOW_NEXT, 0, "if op1<op2 | op1>op3 signal OUT_OF_RANGE")
X(ERASE_REG, 508, FMT_R, FLOW_NEXT, 0, "erases register contents")
X(MOVE_REG_REG, 509, FMT_R_R, FLOW_NEXT, 0, "Move op2 to op1")
X(SWAP_REG_REG, 510, FMT_R_R, FLOW_NEXT, 0, "Swap op1 and op2")
X(LINKARG_REG_INT, 511, FMT_R_I, FLOW_NEXT, 0, "Link args[op2] to op1")
X(LINKARG_REG_REG_INT, 512, FMT_R_R_I, FLOW_NEXT, 0, "Link args[op2+op3] to op1")
X(RXHASH_REG_REG_REG, 513, FMT_R_R_R, FLOW_NEXT, 0, "returns hash value, etc, op1=hash(op2,len(op3))")
X(OPENDLL_REG_REG_REG, 514, FMT_R_R_R, FLOW_NEXT, 0, "open DLL")
X(DLLPARMS_REG_REG_REG, 515, FMT_R_R_R, FLOW_NEXT, 0, "fetches parms for DLL call ")
X(GETTP_REG_REG, 516, FMT_R_R, FLOW_NEXT, 0, "gets the register type flag (op1 = op2.typeflag)")
X(SETTP_REG_INT, 517, FMT_R_I, FLOW_NEXT, 0, "sets the register type flag (op1.typeflag = op2)")
X(LOADSETTP_REG_INT_INT, 518, FMT_R_I_I, FLOW_NEXT, 0, "load register and sets the register type flag load op1=op2 (op1.typeflag = op3)")
X(LOADSETTP_REG_FLOAT_INT, 519, FMT_R_F_I, FLOW_NEXT, 0, "load register and sets the register type flag load op1=op2 (op1.typeflag = op3)")
X(LOADSETTP_REG_STRING_INT, 520, FMT_R_S_I, FLOW_NEXT, 0, "load register and sets the register type flag load op1=op2 (op1.typeflag = op3)")
X(SETORTP_REG_INT, 521, FMT_R_I, FLOW_NEXT, 0, "or the register type flag (op1.typeflag = op1.typeflag | op2)")
X(GETANDTP_REG_REG_INT, 522, FMT_R_R_I, FLOW_NEXT, 0, "get the register type flag with mask (op1(int) = op2.typeflag & op3)")
X(BRTPT_ID_REG, 523, FMT_L_R, FLOW_COND, 0, "if op2.typeflag true then goto op1")
X(BRTPANDT_ID_REG_INT, 524, FMT_L_R_I, FLOW_COND, 0, "if op2.typeflag && op3 true then goto op1")
X(METALOADMODULE_REG_REG, 525, FMT_R_R, FLOW_NEXT, 0, "Load Module (op1 = module num of last loaded module in rxbin op2)")
X(METALOADEDMODULES_REG, 526, FMT_R, FLOW_NEXT, 0, "Loaded Modules (op1 = array loaded modules)")
X(METALOADEDPROCS_REG_REG, 527, FMT_R_R, FLOW_NEXT, 0, "Loaded Procedures (op1 = array procedures in module op2)")
X(METALOADEDEPROCS_REG_REG, 528, FMT_R_R, FLOW_NEXT, 0, "Loaded Exposed Procedures (op1 = array procedures in module op2)")
X(METALOADINST_REG_REG_REG, 529, FMT_R_R_R, FLOW_NEXT, 0, "Load Instruction Code (op1 = (inst)op2[op3])")
X(METADECODEINST_REG_REG, 530, FMT_R_R, FLOW_NEXT, 0, "Decode opcode (op1 decoded op2)")
X(METALOADIOPERAND_REG_REG_REG, 531, FMT_R_R_R, FLOW_NEXT, 0, "Load Integer/Index Operand (op1 = (int)op2[op3])")
X(METALOADFOPERAND_REG_REG_REG, 532, FMT_R_R_R, FLOW_NEXT, 0, "Load Float Operand (op1 = (float)op2[op3])")
X(METALOADSOPERAND_REG_REG_REG, 533, FMT_R_R_R, FLOW_NEXT, 0, "Load String Operand (op1 = (string)op2[op3])")
X(METALOADPOPERAND_REG_REG_REG, 534, FMT_R_R_R, FLOW_NEXT, 0, "Load Procedure Operand (op1 = (proc)op2[op3])")
X(METALOADDATA_REG_REG_REG, 535, FMT_R_R_R, FLOW_NEXT, 0, "Load Metadata (op1 = (metadata)op2[op3])")
X(METALINKPREG_REG_REG, 536, FMT_R_R, FLOW_NEXT, 0, "Link parent-frame-register[op2] to op1")
X(METALOADCALLERADDR_REG, 537, FMT_R, FLOW_NEXT, 0, "Load caller address object to op1")
X(INTERRUPT, 538, FMT_EMPTY, FLOW_NEXT, 0, "")
X(IUNKNOWN, 539, FMT_EMPTY, FLOW_NEXT, 0, "")
X(CNOP, 540, FMT_EMPTY, FLOW_NEXT, 0, "no operation")
