X(enum, 0, FMT_EMPTY, FLOW_NEXT, 0, "")
X(IADD_REG_REG_REG, 1, FMT_R_R_R, FLOW_NEXT, 0, "Integer Add (op1=op2+op3)")
X(IADD_REG_REG_INT, 2, FMT_R_R_I, FLOW_NEXT, 0, "Integer Add (op1=op2+op3)")
X(ADDI_REG_REG_REG, 3, FMT_R_R_R, FLOW_NEXT, FLG_DEPRECATED, "Convert and Add to Integer (op1=op2+op3) (Deprecated)")
X(ADDI_REG_REG_INT, 4, FMT_R_R_I, FLOW_NEXT, FLG_DEPRECATED, "Convert and Add to Integer (op1=op2+op3) (Deprecated)")
X(ISUB_REG_REG_REG, 5, FMT_R_R_R, FLOW_NEXT, 0, "Integer Subtract (op1=op2-op3)")
X(ISUB_REG_REG_INT, 6, FMT_R_R_I, FLOW_NEXT, 0, "Integer Subtract (op1=op2-op3)")
X(ISUB_REG_INT_REG, 7, FMT_R_I_R, FLOW_NEXT, 0, "Integer Subtract (op1=op2-op3)")
X(SUBI_REG_REG_REG, 8, FMT_R_R_R, FLOW_NEXT, FLG_DEPRECATED, "Convert and Subtract to Integer (op1=op2-op3) (Deprecated)")
X(SUBI_REG_REG_INT, 9, FMT_R_R_I, FLOW_NEXT, FLG_DEPRECATED, "Convert and Subtract to Integer (op1=op2-op3) (Deprecated)")
X(IMULT_REG_REG_REG, 10, FMT_R_R_R, FLOW_NEXT, 0, "Integer Multiply (op1=op2*op3)")
X(IMULT_REG_REG_INT, 11, FMT_R_R_I, FLOW_NEXT, 0, "Integer Multiply (op1=op2*op3)")
X(MULTI_REG_REG_REG, 12, FMT_R_R_R, FLOW_NEXT, FLG_DEPRECATED, "Convert and Multiply to Integer (op1=op2*op3) (Deprecated)")
X(MULTI_REG_REG_INT, 13, FMT_R_R_I, FLOW_NEXT, FLG_DEPRECATED, "Convert and Multiply to Integer (op1=op2*op3) (Deprecated)")
X(IDIV_REG_REG_REG, 14, FMT_R_R_R, FLOW_NEXT, 0, "Integer Divide (op1=op2/op3)")
X(IDIV_REG_REG_INT, 15, FMT_R_R_I, FLOW_NEXT, 0, "Integer Divide (op1=op2/op3)")
X(IDIV_REG_INT_REG, 16, FMT_R_I_R, FLOW_NEXT, 0, "Integer Divide (op1=op2/op3)")
X(FIDIV_REG_REG_REG, 17, FMT_R_R_R, FLOW_NEXT, 0, "Integer Divide with Floats (op1=op2/op3)")
X(FIDIV_REG_REG_FLOAT, 18, FMT_R_R_F, FLOW_NEXT, 0, "Integer Divide with Floats (op1=op2/op3)")
X(FIDIV_REG_FLOAT_REG, 19, FMT_R_F_R, FLOW_NEXT, 0, "Integer Divide with Floats (op1=op2/op3)")
X(DIDIV_REG_REG_REG, 20, FMT_R_R_R, FLOW_NEXT, 0, "Integer Divide with Decimals (op1=op2/op3)")
X(DIDIV_REG_REG_DECIMAL, 21, FMT_R_R_D, FLOW_NEXT, 0, "Integer Divide with Decimals (op1=op2/op3)")
X(DIDIV_REG_DECIMAL_REG, 22, FMT_R_D_R, FLOW_NEXT, 0, "Integer Divide with Decimals (op1=op2/op3)")
X(DIVI_REG_REG_REG, 23, FMT_R_R_R, FLOW_NEXT, FLG_DEPRECATED, "Convert and Divide to Integer (op1=op2/op3) (Deprecated)")
X(DIVI_REG_REG_INT, 24, FMT_R_R_I, FLOW_NEXT, FLG_DEPRECATED, "Convert and Divide to Integer (op1=op2/op3) (Deprecated)")
X(IMOD_REG_REG_REG, 25, FMT_R_R_R, FLOW_NEXT, 0, "Integer Modulo (op1=op2%op3)")
X(IMOD_REG_REG_INT, 26, FMT_R_R_I, FLOW_NEXT, 0, "Integer Modulo (op1=op2%op3)")
X(IMOD_REG_INT_REG, 27, FMT_R_I_R, FLOW_NEXT, 0, "Integer Modulo (op1=op2&op3)")
X(FMOD_REG_REG_REG, 28, FMT_R_R_R, FLOW_NEXT, 0, "Float Modulo (op1=op2%op3)")
X(FMOD_REG_REG_FLOAT, 29, FMT_R_R_F, FLOW_NEXT, 0, "Float Modulo (op1=op2%op3)")
X(FMOD_REG_FLOAT_REG, 30, FMT_R_F_R, FLOW_NEXT, 0, "Float Modulo (op1=op2&op3)")
X(DMOD_REG_REG_REG, 31, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Modulo (op1=op2%op3)")
X(DMOD_REG_REG_DECIMAL, 32, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Modulo (op1=op2%op3)")
X(DMOD_REG_DECIMAL_REG, 33, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Modulo (op1=op2&op3)")
X(FADD_REG_REG_REG, 34, FMT_R_R_R, FLOW_NEXT, 0, "Float Add (op1=op2+op3)")
X(FADD_REG_REG_FLOAT, 35, FMT_R_R_F, FLOW_NEXT, 0, "Float Add (op1=op2+op3)")
X(ADDF_REG_REG_REG, 36, FMT_R_R_R, FLOW_NEXT, FLG_DEPRECATED, "Convert and Add to Float (op1=op2+op3) (Deprecated)")
X(ADDF_REG_REG_FLOAT, 37, FMT_R_R_F, FLOW_NEXT, FLG_DEPRECATED, "Convert and Add to Float (op1=op2+op3) (Deprecated)")
X(FSUB_REG_REG_REG, 38, FMT_R_R_R, FLOW_NEXT, 0, "Float Subtract (op1=op2-op3)")
X(FSUB_REG_REG_FLOAT, 39, FMT_R_R_F, FLOW_NEXT, 0, "Float Subtract (op1=op2-op3)")
X(FSUB_REG_FLOAT_REG, 40, FMT_R_F_R, FLOW_NEXT, 0, "Float Subtract (op1=op2-op3)")
X(SUBF_REG_REG_REG, 41, FMT_R_R_R, FLOW_NEXT, FLG_DEPRECATED, "Convert and Subtract to Float (op1=op2-op3) (Deprecated)")
X(SUBF_REG_REG_FLOAT, 42, FMT_R_R_F, FLOW_NEXT, FLG_DEPRECATED, "Convert and Subtract to Float (op1=op2-op3) (Deprecated)")
X(SUBF_REG_FLOAT_REG, 43, FMT_R_F_R, FLOW_NEXT, FLG_DEPRECATED, "Convert and Subtract to Float (op1=op2-op3) (Deprecated)")
X(FMULT_REG_REG_REG, 44, FMT_R_R_R, FLOW_NEXT, 0, "Float Multiply (op1=op2*op3)")
X(FMULT_REG_REG_FLOAT, 45, FMT_R_R_F, FLOW_NEXT, 0, "Float Multiply (op1=op2*op3)")
X(MULTF_REG_REG_REG, 46, FMT_R_R_R, FLOW_NEXT, FLG_DEPRECATED, "Convert and Multiply to Float (op1=op2*op3) (Deprecated)")
X(MULTF_REG_REG_FLOAT, 47, FMT_R_R_F, FLOW_NEXT, FLG_DEPRECATED, "Convert and Multiply to Float (op1=op2*op3) (Deprecated)")
X(FDIV_REG_REG_REG, 48, FMT_R_R_R, FLOW_NEXT, 0, "Float Divide (op1=op2/op3)")
X(FDIV_REG_REG_FLOAT, 49, FMT_R_R_F, FLOW_NEXT, 0, "Float Divide (op1=op2/op3)")
X(FDIV_REG_FLOAT_REG, 50, FMT_R_F_R, FLOW_NEXT, 0, "Float Divide (op1=op2/op3)")
X(DIVF_REG_REG_REG, 51, FMT_R_R_R, FLOW_NEXT, FLG_DEPRECATED, "Convert and Divide to Float (op1=op2/op3) (Deprecated)")
X(DIVF_REG_REG_FLOAT, 52, FMT_R_R_F, FLOW_NEXT, FLG_DEPRECATED, "Convert and Divide to Float (op1=op2/op3) (Deprecated)")
X(DIVF_REG_FLOAT_REG, 53, FMT_R_F_R, FLOW_NEXT, FLG_DEPRECATED, "Convert and Divide to Float (op1=op2/op3) (Deprecated)")
X(INC_REG, 54, FMT_R, FLOW_NEXT, 0, "Increment Int (op1++)")
X(DEC_REG, 55, FMT_R, FLOW_NEXT, 0, "Decrement Int (op1--)")
X(INC0, 56, FMT_EMPTY, FLOW_NEXT, 0, "Increment R0++ Int")
X(DEC0, 57, FMT_EMPTY, FLOW_NEXT, 0, "Decrement R0-- Int")
X(INC1, 58, FMT_EMPTY, FLOW_NEXT, 0, "Increment R1++ Int")
X(DEC1, 59, FMT_EMPTY, FLOW_NEXT, 0, "Decrement R1-- Int")
X(INC2, 60, FMT_EMPTY, FLOW_NEXT, 0, "Increment R2++ Int")
X(DEC2, 61, FMT_EMPTY, FLOW_NEXT, 0, "Decrement R2-- Int")
X(IAND_REG_REG_REG, 62, FMT_R_R_R, FLOW_NEXT, 0, "bit wise and of 2 integers (op1=op2&op3)")
X(IAND_REG_REG_INT, 63, FMT_R_R_I, FLOW_NEXT, 0, "bit wise and of 2 integers (op1=op2&op3)")
X(IOR_REG_REG_REG, 64, FMT_R_R_R, FLOW_NEXT, 0, "bit wise or of 2 integers (op1=op2|op3)")
X(IOR_REG_REG_INT, 65, FMT_R_R_I, FLOW_NEXT, 0, "bit wise or of 2 integers (op1=op2|op3)")
X(IXOR_REG_REG_REG, 66, FMT_R_R_R, FLOW_NEXT, 0, "bit wise exclusive OR of 2 integers (op1=op2^op3)")
X(IXOR_REG_REG_INT, 67, FMT_R_R_I, FLOW_NEXT, 0, "bit wise exclusive OR of 2 integers (op1=op2^op3)")
X(ISHL_REG_REG_REG, 68, FMT_R_R_R, FLOW_NEXT, 0, "bit wise shift logical left of integer (op1=op2<<op3)")
X(ISHL_REG_REG_INT, 69, FMT_R_R_I, FLOW_NEXT, 0, "bit wise shift logical left of integer (op1=op2<<op3)")
X(ISHR_REG_REG_REG, 70, FMT_R_R_R, FLOW_NEXT, 0, "bit wise shift logical right of integer (op1=op2>>op3)")
X(ISHR_REG_REG_INT, 71, FMT_R_R_I, FLOW_NEXT, 0, "bit wise shift logical right of integer (op1=op2>>op3)")
X(INOT_REG_REG, 72, FMT_R_R, FLOW_NEXT, 0, "inverts all bits of an integer (op1=~op2)")
X(INOT_REG_INT, 73, FMT_R_I, FLOW_NEXT, 0, "inverts all bits of an integer (op1=~op2)")
X(SCONCAT_REG_REG_REG, 74, FMT_R_R_R, FLOW_NEXT, 0, "String Concat with space (op1=op2||op3)")
X(SCONCAT_REG_REG_STRING, 75, FMT_R_R_S, FLOW_NEXT, 0, "String Concat with space (op1=op2||op3)")
X(SCONCAT_REG_STRING_REG, 76, FMT_R_S_R, FLOW_NEXT, 0, "String Concat with space (op1=op2||op3)")
X(CONCAT_REG_REG_REG, 77, FMT_R_R_R, FLOW_NEXT, 0, "String Concat (op1=op2||op3)")
X(CONCAT_REG_REG_STRING, 78, FMT_R_R_S, FLOW_NEXT, 0, "String Concat (op1=op2||op3)")
X(CONCAT_REG_STRING_REG, 79, FMT_R_S_R, FLOW_NEXT, 0, "String Concat (op1=op2||op3)")
X(APPENDCHAR_REG_REG, 80, FMT_R_R, FLOW_NEXT, 0, "Append Concat Char op2 (as int) on op1")
X(CONCCHAR_REG_REG_REG, 81, FMT_R_R_R, FLOW_NEXT, 0, "Concat Char op1 from op2 position op3")
X(SAPPEND_REG_REG, 82, FMT_R_R, FLOW_NEXT, 0, "String Append with space (op1=op1||op2)")
X(APPEND_REG_REG, 83, FMT_R_R, FLOW_NEXT, 0, "String Append (op1=op1||op2)")
X(TRIML_REG_REG, 84, FMT_R_R, FLOW_NEXT, 0, "Trim String (op1) from Left by (op2) Chars")
X(TRIMR_REG_REG, 85, FMT_R_R, FLOW_NEXT, 0, "Trim String (op1) from Right by (op2) Chars")
X(TRUNC_REG_REG, 86, FMT_R_R, FLOW_NEXT, 0, "Trunc String (op1) to (op2) Chars")
X(TRIML_REG_REG_REG, 87, FMT_R_R_R, FLOW_NEXT, 0, "Trim String (op2) from Left by (op3) Chars into op1")
X(TRIMR_REG_REG_REG, 88, FMT_R_R_R, FLOW_NEXT, 0, "Trim String (op2) from Right by (op3) Chars into op1")
X(TRUNC_REG_REG_REG, 89, FMT_R_R_R, FLOW_NEXT, 0, "Trunc String (op2) to (op3) Chars into op1")
X(STRLEN_REG_REG, 90, FMT_R_R, FLOW_NEXT, 0, "String Length op1 = length(op2)")
X(STRCHAR_REG_REG_REG, 91, FMT_R_R_R, FLOW_NEXT, 0, "op1 (as int) = op2[op3]")
X(STRCHAR_REG_REG, 92, FMT_R_R, FLOW_NEXT, 0, "op1 (as int) = op2[charpos]")
X(HEXCHAR_REG_REG_REG, 93, FMT_R_R_R, FLOW_NEXT, 0, "op1 (as hex) = op2[op3]")
X(POSCHAR_REG_REG_REG, 94, FMT_R_R_R, FLOW_NEXT, 0, "op1 = position of op3 in op2")
X(SETSTRPOS_REG_REG, 95, FMT_R_R, FLOW_NEXT, 0, "Set String (op1) charpos set to op2")
X(GETSTRPOS_REG_REG, 96, FMT_R_R, FLOW_NEXT, 0, "Get String (op2) charpos into op1")
X(SUBSTR_REG_REG_REG, 97, FMT_R_R_R, FLOW_NEXT, 0, "op1 = op2[charpos]...op2[charpos+op3-1]")
X(IEQ_REG_REG_REG, 98, FMT_R_R_R, FLOW_NEXT, 0, "Int Equals op1=(op2==op3)")
X(IEQ_REG_REG_INT, 99, FMT_R_R_I, FLOW_NEXT, 0, "Int Equals op1=(op2==op3)")
X(INE_REG_REG_REG, 100, FMT_R_R_R, FLOW_NEXT, 0, "Int Not equals op1=(op2!=op3)")
X(INE_REG_REG_INT, 101, FMT_R_R_I, FLOW_NEXT, 0, "Int Not equals op1=(op2!=op3)")
X(IGT_REG_REG_REG, 102, FMT_R_R_R, FLOW_NEXT, 0, "Int Greater than op1=(op2>op3)")
X(IGT_REG_REG_INT, 103, FMT_R_R_I, FLOW_NEXT, 0, "Int Greater than op1=(op2>op3)")
X(IGT_REG_INT_REG, 104, FMT_R_I_R, FLOW_NEXT, 0, "Int Greater than op1=(op2>op3)")
X(IGTE_REG_REG_REG, 105, FMT_R_R_R, FLOW_NEXT, 0, "Int Greater than equals op1=(op2>=op3)")
X(IGTE_REG_REG_INT, 106, FMT_R_R_I, FLOW_NEXT, 0, "Int Greater than equals op1=(op2>=op3)")
X(IGTE_REG_INT_REG, 107, FMT_R_I_R, FLOW_NEXT, 0, "Int Greater than equals op1=(op2>=op3)")
X(ILT_REG_REG_REG, 108, FMT_R_R_R, FLOW_NEXT, 0, "Int Less than op1=(op2<op3)")
X(ILT_REG_REG_INT, 109, FMT_R_R_I, FLOW_NEXT, 0, "Int Less than op1=(op2<op3)")
X(ILT_REG_INT_REG, 110, FMT_R_I_R, FLOW_NEXT, 0, "Int Less than op1=(op2<op3)")
X(ILTE_REG_REG_REG, 111, FMT_R_R_R, FLOW_NEXT, 0, "Int Less than equals op1=(op2<=op3)")
X(ILTE_REG_REG_INT, 112, FMT_R_R_I, FLOW_NEXT, 0, "Int Less than equals op1=(op2<=op3)")
X(ILTE_REG_INT_REG, 113, FMT_R_I_R, FLOW_NEXT, 0, "Int Less than equals op1=(op2<=op3)")
X(IGTBR_ID_REG_REG, 114, FMT_L_R_R, FLOW_NEXT, 0, "Int Greater than if (op2>op3) goto op1")
X(ILTBR_ID_REG_REG, 115, FMT_L_R_R, FLOW_NEXT, 0, "Int Less than if (op2<op3) goto op1")
X(FEQ_REG_REG_REG, 116, FMT_R_R_R, FLOW_NEXT, 0, "Float Equals op1=(op2==op3)")
X(FEQ_REG_REG_FLOAT, 117, FMT_R_R_F, FLOW_NEXT, 0, "Float Equals op1=(op2==op3)")
X(FNE_REG_REG_REG, 118, FMT_R_R_R, FLOW_NEXT, 0, "Float Not equals op1=(op2!=op3)")
X(FNE_REG_REG_FLOAT, 119, FMT_R_R_F, FLOW_NEXT, 0, "Float Not equals op1=(op2!=op3)")
X(FGT_REG_REG_REG, 120, FMT_R_R_R, FLOW_NEXT, 0, "Float Greater than op1=(op2>op3)")
X(FGT_REG_REG_FLOAT, 121, FMT_R_R_F, FLOW_NEXT, 0, "Float Greater than op1=(op2>op3)")
X(FGT_REG_FLOAT_REG, 122, FMT_R_F_R, FLOW_NEXT, 0, "Float Greater than op1=(op2>op3)")
X(FGTE_REG_REG_REG, 123, FMT_R_R_R, FLOW_NEXT, 0, "Float Greater than equals op1=(op2>=op3)")
X(FGTE_REG_REG_FLOAT, 124, FMT_R_R_F, FLOW_NEXT, 0, "Float Greater than equals op1=(op2>=op3)")
X(FGTE_REG_FLOAT_REG, 125, FMT_R_F_R, FLOW_NEXT, 0, "Float Greater than equals op1=(op2>=op3)")
X(FLT_REG_REG_REG, 126, FMT_R_R_R, FLOW_NEXT, 0, "Float Less than op1=(op2<op3)")
X(FLT_REG_REG_FLOAT, 127, FMT_R_R_F, FLOW_NEXT, 0, "Float Less than op1=(op2<op3)")
X(FLT_REG_FLOAT_REG, 128, FMT_R_F_R, FLOW_NEXT, 0, "Float Less than op1=(op2<op3)")
X(FLTE_REG_REG_REG, 129, FMT_R_R_R, FLOW_NEXT, 0, "Float Less than equals op1=(op2<=op3)")
X(FLTE_REG_REG_FLOAT, 130, FMT_R_R_F, FLOW_NEXT, 0, "Float Less than equals op1=(op2<=op3)")
X(FLTE_REG_FLOAT_REG, 131, FMT_R_F_R, FLOW_NEXT, 0, "Float Less than equals op1=(op2<=op3)")
X(FGTBR_ID_REG_REG, 132, FMT_L_R_R, FLOW_NEXT, 0, "Float Greater than if (op2>op3) goto op1")
X(FLTBR_ID_REG_REG, 133, FMT_L_R_R, FLOW_NEXT, 0, "Float Less than if (op2<op3) goto op1")
X(SEQ_REG_REG_REG, 134, FMT_R_R_R, FLOW_NEXT, 0, "String Equals op1=(op2==op3)")
X(SEQ_REG_REG_STRING, 135, FMT_R_R_S, FLOW_NEXT, 0, "String Equals op1=(op2==op3)")
X(RSEQ_REG_REG_REG, 136, FMT_R_R_R, FLOW_NEXT, 0, "non strict String Equals op1=(op2=op3)")
X(RSEQ_REG_REG_STRING, 137, FMT_R_R_S, FLOW_NEXT, 0, "non strict String Equals op1=(op2=op3)")
X(SNE_REG_REG_REG, 138, FMT_R_R_R, FLOW_NEXT, 0, "String Not equals op1=(op2!=op3)")
X(SNE_REG_REG_STRING, 139, FMT_R_R_S, FLOW_NEXT, 0, "String Not equals op1=(op2!=op3)")
X(SGT_REG_REG_REG, 140, FMT_R_R_R, FLOW_NEXT, 0, "String Greater than op1=(op2>op3)")
X(SGT_REG_REG_STRING, 141, FMT_R_R_S, FLOW_NEXT, 0, "String Greater than op1=(op2>op3)")
X(SGT_REG_STRING_REG, 142, FMT_R_S_R, FLOW_NEXT, 0, "String Greater than op1=(op2>op3)")
X(SGTE_REG_REG_REG, 143, FMT_R_R_R, FLOW_NEXT, 0, "String Greater than equals op1=(op2>=op3)")
X(SGTE_REG_REG_STRING, 144, FMT_R_R_S, FLOW_NEXT, 0, "String Greater than equals op1=(op2>=op3)")
X(SGTE_REG_STRING_REG, 145, FMT_R_S_R, FLOW_NEXT, 0, "String Greater than equals op1=(op2>=op3)")
X(SLT_REG_REG_REG, 146, FMT_R_R_R, FLOW_NEXT, 0, "String Less than op1=(op2<op3)")
X(SLT_REG_REG_STRING, 147, FMT_R_R_S, FLOW_NEXT, 0, "String Less than op1=(op2<op3)")
X(SLT_REG_STRING_REG, 148, FMT_R_S_R, FLOW_NEXT, 0, "String Less than op1=(op2<op3)")
X(SLTE_REG_REG_REG, 149, FMT_R_R_R, FLOW_NEXT, 0, "String Less than equals op1=(op2<=op3)")
X(SLTE_REG_REG_STRING, 150, FMT_R_R_S, FLOW_NEXT, 0, "String Less than equals op1=(op2<=op3)")
X(SLTE_REG_STRING_REG, 151, FMT_R_S_R, FLOW_NEXT, 0, "String Less than equals op1=(op2<=op3)")
X(AND_REG_REG_REG, 152, FMT_R_R_R, FLOW_NEXT, 0, "Logical (int) and op1=(op2 && op3)")
X(OR_REG_REG_REG, 153, FMT_R_R_R, FLOW_NEXT, 0, "Logical (int) or op1=(op2 || op3)")
X(NOT_REG_REG, 154, FMT_R_R, FLOW_NEXT, 0, "Logical (int) not op1=!op2")
X(TIME_REG, 155, FMT_R, FLOW_NEXT, 0, "Put time into op1")
X(MTIME_REG, 156, FMT_R, FLOW_NEXT, 0, "Put time in microseconds into op1")
X(XTIME_REG_STRING, 157, FMT_R_S, FLOW_NEXT, 0, "put special time properties into op1")
X(MAP_REG_REG, 158, FMT_R_R, FLOW_NEXT, 0, "Map op1 to var name in op2")
X(MAP_REG_STRING, 159, FMT_R_S, FLOW_NEXT, 0, "Map op1 to var name op2")
X(PMAP_REG_REG, 160, FMT_R_R, FLOW_NEXT, 0, "Map op1 to parent var name in op2")
X(PMAP_REG_STRING, 161, FMT_R_S, FLOW_NEXT, 0, "Map op1 to parent var name op2")
X(GMAP_REG_REG, 162, FMT_R_R, FLOW_NEXT, 0, "Map op1 to global var name in op2")
X(GMAP_REG_STRING, 163, FMT_R_S, FLOW_NEXT, 0, "Map op1 to global var name op2")
X(NSMAP_REG_REG_REG, 164, FMT_R_R_R, FLOW_NEXT, 0, "Map op1 to namespace in op2 var name in op3")
X(NSMAP_REG_REG_STRING, 165, FMT_R_R_S, FLOW_NEXT, 0, "Map op1 to namespace in op2 var name op3")
X(NSMAP_REG_STRING_STRING, 166, FMT_R_S_S, FLOW_NEXT, 0, "Map op1 to namespace op2 var name op3")
X(NSMAP_REG_STRING_REG, 167, FMT_R_S_R, FLOW_NEXT, 0, "Map op1 to namespace op2 var name in op3")
X(UNMAP_REG, 168, FMT_R, FLOW_NEXT, 0, "Unmap op1")
X(CALL_FUNC, 169, FMT_P, FLOW_NEXT, 0, "Call procedure (op1())")
X(CALL_REG_FUNC, 170, FMT_R_P, FLOW_NEXT, 0, "Call procedure (op1=op2())")
X(CALL_REG_FUNC_REG, 171, FMT_R_P_R, FLOW_NEXT, 0, "Call procedure (op1=op2(op3...) )")
X(DCALL_REG_REG_REG, 172, FMT_R_R_R, FLOW_NEXT, 0, "Dynamic call procedure (op1=op2(op3...) )")
X(RET, 173, FMT_EMPTY, FLOW_TERM, 0, "Return VOID")
X(RET_REG, 174, FMT_R, FLOW_TERM, 0, "Return op1")
X(RET_INT, 175, FMT_I, FLOW_TERM, 0, "Return op1")
X(RET_FLOAT, 176, FMT_F, FLOW_TERM, 0, "Return op1")
X(RET_CHAR, 177, FMT_C, FLOW_TERM, 0, "Return op1")
X(RET_STRING, 178, FMT_S, FLOW_TERM, 0, "Return op1")
X(BR_ID, 179, FMT_L, FLOW_JUMP, 0, "Branch to op1")
X(BRT_ID_REG, 180, FMT_L_R, FLOW_COND, 0, "Branch to op1 if op2 true")
X(BRF_ID_REG, 181, FMT_L_R, FLOW_COND, 0, "Branch to op1 if op2 false")
X(BRTF_ID_ID_REG, 182, FMT_L_L_R, FLOW_COND, 0, "Branch to op1 if op3 true, otherwise branch to op2")
X(MOVE_REG_REG, 183, FMT_R_R, FLOW_NEXT, 0, "Move op2 to op1")
X(SWAP_REG_REG, 184, FMT_R_R, FLOW_NEXT, 0, "Swap op1 and op2")
X(COPY_REG_REG, 185, FMT_R_R, FLOW_NEXT, 0, "Copy op2 to op1")
X(ICOPY_REG_REG, 186, FMT_R_R, FLOW_NEXT, 0, "Copy Integer op2 to op1")
X(FCOPY_REG_REG, 187, FMT_R_R, FLOW_NEXT, 0, "Copy Float op2 to op1")
X(SCOPY_REG_REG, 188, FMT_R_R, FLOW_NEXT, 0, "Copy String op2 to op1")
X(ACOPY_REG_REG, 189, FMT_R_R, FLOW_NEXT, 0, "Copy status Attributes op2 to op1")
X(LINKARG_REG_INT, 190, FMT_R_I, FLOW_NEXT, 0, "Link args[op2] to op1")
X(LINKARG_REG_REG_INT, 191, FMT_R_R_I, FLOW_NEXT, 0, "Link args[op2+op3] to op1")
X(LINKATTR_REG_REG_REG, 192, FMT_R_R_R, FLOW_NEXT, 0, "Link attribute op3 of op2 to op1")
X(LINKATTR_REG_REG_INT, 193, FMT_R_R_I, FLOW_NEXT, 0, "Link attribute op3 of op2 to op1")
X(LINKATTR1_REG_REG_REG, 194, FMT_R_R_R, FLOW_NEXT, 0, "Link attribute op3 (1 base) of op2 to op1")
X(LINKATTR1_REG_REG_INT, 195, FMT_R_R_I, FLOW_NEXT, 0, "Link attribute op3 (1 base) of op2 to op1")
X(LINKTOATTR_REG_REG_REG, 196, FMT_R_R_R, FLOW_NEXT, 0, "Link op3 to attribute op1 of op2 ")
X(LINKTOATTR_INT_REG_REG, 197, FMT_I_R_R, FLOW_NEXT, 0, "Link op3 to attribute op1 of op2 ")
X(LINKTOATTR1_REG_REG_REG, 198, FMT_R_R_R, FLOW_NEXT, 0, "Link op3 to attribute op1 (1 base) of op2 ")
X(LINKTOATTR1_INT_REG_REG, 199, FMT_I_R_R, FLOW_NEXT, 0, "Link op3 to attribute op1 (1 base) of op2 ")
X(UNLINKATTR_REG_REG, 200, FMT_R_R, FLOW_NEXT, 0, "Unlink attribute op1 of op2")
X(UNLINKATTR_INT_REG, 201, FMT_I_R, FLOW_NEXT, 0, "Unlink attribute op1 of op2")
X(UNLINKATTR1_REG_REG, 202, FMT_R_R, FLOW_NEXT, 0, "Unlink attribute op1 (1 base) of op2")
X(UNLINKATTR1_INT_REG, 203, FMT_I_R, FLOW_NEXT, 0, "Unlink attribute op1 (1 base) of op2")
X(LINK_REG_REG, 204, FMT_R_R, FLOW_NEXT, 0, "Link op2 to op1")
X(UNLINK_REG, 205, FMT_R, FLOW_NEXT, 0, "Unlink op1")
X(NULL_REG, 206, FMT_R, FLOW_NEXT, 0, "Null (clear) op1")
X(LOAD_REG_INT, 207, FMT_R_I, FLOW_NEXT, 0, "Load op1 with op2")
X(LOAD_REG_FLOAT, 208, FMT_R_F, FLOW_NEXT, 0, "Load op1 with op2")
X(LOAD_REG_STRING, 209, FMT_R_S, FLOW_NEXT, 0, "Load op1 with op2")
X(LOAD_REG_CHAR, 210, FMT_R_C, FLOW_NEXT, 0, "Load op1 with op2")
X(LOAD_REG_REG, 211, FMT_R_R, FLOW_NEXT, 0, "Load op1 with op2")
X(LOAD_REG_DECIMAL, 212, FMT_R_D, FLOW_NEXT, 0, "Load op1 with op2")
X(LOAD_INT_INT, 213, FMT_I_I, FLOW_NEXT, 0, "Load op1 with op2 (non symbolic registers)")
X(LOAD_INT_REG, 214, FMT_I_R, FLOW_NEXT, 0, "Load op1 with op2 (non symbolic registers)")
X(SAY_REG, 215, FMT_R, FLOW_NEXT, 0, "Say op1")
X(SAYX_REG, 216, FMT_R, FLOW_NEXT, 0, "Say op1 without line feed")
X(SAYX_STRING, 217, FMT_S, FLOW_NEXT, 0, "Say op1 (as string) without line feed")
X(SAY_INT, 218, FMT_I, FLOW_NEXT, 0, "Say op1")
X(SAY_FLOAT, 219, FMT_F, FLOW_NEXT, 0, "Say op1")
X(SAY_STRING, 220, FMT_S, FLOW_NEXT, 0, "Say op1")
X(SAY_CHAR, 221, FMT_C, FLOW_NEXT, 0, "Say op1")
X(READLINE_REG, 222, FMT_R, FLOW_NEXT, 0, "Read Line to op1")
X(EXIT, 223, FMT_EMPTY, FLOW_TERM, 0, "Exit")
X(EXIT_REG, 224, FMT_R, FLOW_TERM, 0, "Exit op1")
X(EXIT_INT, 225, FMT_I, FLOW_TERM, 0, "Exit op1")
X(BTOI_REG, 226, FMT_R, FLOW_COND, 0, "Set register integer value from its boolean value")
X(BTOD_REG, 227, FMT_R, FLOW_COND, 0, "Set register decimal value from its boolean value")
X(BTOF_REG, 228, FMT_R, FLOW_COND, 0, "Set register float value from its boolean value")
X(BTOS_REG, 229, FMT_R, FLOW_COND, 0, "Set register string value from its boolean value")
X(ITOS_REG, 230, FMT_R, FLOW_NEXT, 0, "Set register string value from its int value")
X(FTOS_REG, 231, FMT_R, FLOW_NEXT, 0, "Set register string value from its float value")
X(ITOF_REG, 232, FMT_R, FLOW_NEXT, 0, "Set register float value from its int value")
X(FTOI_REG, 233, FMT_R, FLOW_NEXT, 0, "Set register int value from its float value")
X(FTOB_REG, 234, FMT_R, FLOW_NEXT, 0, "Set register boolean (int 1 or 0) value from its float value")
X(ITOB_REG, 235, FMT_R, FLOW_NEXT, 0, "Set register boolean (int 1 or 0) value from its integer value")
X(STOB_REG, 236, FMT_R, FLOW_NEXT, 0, "Set register boolean (int 1 or 0) value from its string value")
X(STOF_REG, 237, FMT_R, FLOW_NEXT, 0, "Set register float value from its string value")
X(STOI_REG, 238, FMT_R, FLOW_NEXT, 0, "Set register int value from its string value")
X(FFORMAT_REG_REG_REG, 239, FMT_R_R_R, FLOW_NEXT, 0, "DEPRECATED use fextr. Set string value from float value using a format string")
X(FEXTR_REG_REG_REG, 240, FMT_R_R_R, FLOW_NEXT, 0, "op3 float extracted to op1 string coefficient and op2 int decimal exponent")
X(STRLOWER_REG_REG, 241, FMT_R_R, FLOW_NEXT, 0, "Set string to lower case value")
X(STRUPPER_REG_REG, 242, FMT_R_R, FLOW_NEXT, 0, "Set string to upper case value")
X(TRANSCHAR_REG_REG_REG, 243, FMT_R_R_R, FLOW_NEXT, 0, "replace op1 if it is in op3-list by char in op2-list")
X(DROPCHAR_REG_REG_REG, 244, FMT_R_R_R, FLOW_NEXT, 0, "set op1 from op2 after dropping all chars from op3")
X(SUBSTRING_REG_REG_REG, 245, FMT_R_R_R, FLOW_NEXT, 0, "set op1=substr(op2,op3) remaining string")
X(SUBSTCUT_REG_REG, 246, FMT_R_R, FLOW_NEXT, 0, "set op1=substr(op1,,op2) cuts off op1 after position op3")
X(PADSTR_REG_REG_REG, 247, FMT_R_R_R, FLOW_NEXT, 0, "set op1=op2[repeated op3 times]")
X(STRPOS_REG_REG_REG, 248, FMT_R_R_R, FLOW_NEXT, 0, "op1 is position of op2 in op3")
X(GETBYTE_REG_REG_REG, 249, FMT_R_R_R, FLOW_NEXT, 0, "get byte  (op1=op2(op3)")
X(CNOP, 250, FMT_EMPTY, FLOW_NEXT, 0, "no operation")
X(IPOW_REG_REG_REG, 251, FMT_R_R_R, FLOW_NEXT, 0, "op1=op2**op3")
X(IPOW_REG_REG_INT, 252, FMT_R_R_I, FLOW_NEXT, 0, "op1=op2**op3")
X(IPOW_REG_INT_REG, 253, FMT_R_I_R, FLOW_NEXT, 0, "op1=op2**op3")
X(FPOW_REG_REG_REG, 254, FMT_R_R_R, FLOW_NEXT, 0, "op1=op2**op3")
X(FPOW_REG_REG_FLOAT, 255, FMT_R_R_F, FLOW_NEXT, 0, "op1=op2**op3")
X(FPOW_REG_FLOAT_REG, 256, FMT_R_F_R, FLOW_NEXT, 0, "op1=op2**op3")
X(BCT_ID_REG, 257, FMT_L_R, FLOW_COND, 0, "dec op2; if op2>0; goto op1(if true)")
X(BCT_ID_REG_REG, 258, FMT_L_R_R, FLOW_COND, 0, "dec op2; inc op3, if op2>0; goto op1(if true)")
X(BCTNM_ID_REG, 259, FMT_L_R, FLOW_COND, 0, "dec op2; if op2>=0; goto op1(if true)")
X(BCTNM_ID_REG_REG, 260, FMT_L_R_R, FLOW_COND, 0, "dec op2; inc op3, if op2>=0; goto op1(if true)")
X(BCTP_ID_REG, 261, FMT_L_R, FLOW_COND, 0, "inc op2; goto op1")
X(BCF_ID_REG, 262, FMT_L_R, FLOW_COND, 0, "if op2=0 goto op1(if false) else dec op2")
X(BCF_ID_REG_REG, 263, FMT_L_R_R, FLOW_COND, 0, "if op2=0 goto op1(if false) else dec op2 and inc op3")
X(BGT_ID_REG_REG, 264, FMT_L_R_R, FLOW_COND, 0, "if op2>op3 then goto op1")
X(BGT_ID_REG_INT, 265, FMT_L_R_I, FLOW_COND, 0, "if op2>op3 then goto op1")
X(BGE_ID_REG_REG, 266, FMT_L_R_R, FLOW_COND, 0, "if op2>=op3 then goto op1")
X(BGE_ID_REG_INT, 267, FMT_L_R_I, FLOW_COND, 0, "if op2>=op3 then goto op1")
X(BLT_ID_REG_REG, 268, FMT_L_R_R, FLOW_COND, 0, "if op2<op3 then goto op1")
X(BLT_ID_REG_INT, 269, FMT_L_R_I, FLOW_COND, 0, "if op2<op3 then goto op1")
X(BLE_ID_REG_REG, 270, FMT_L_R_R, FLOW_COND, 0, "if op2<=op3 then goto op1")
X(BLE_ID_REG_INT, 271, FMT_L_R_I, FLOW_COND, 0, "if op2<=op3 then goto op1")
X(BNE_ID_REG_REG, 272, FMT_L_R_R, FLOW_COND, 0, "if op2!=op3 then goto op1")
X(BNE_ID_REG_INT, 273, FMT_L_R_I, FLOW_COND, 0, "if op2!=op3 then goto op1")
X(BEQ_ID_REG_REG, 274, FMT_L_R_R, FLOW_COND, 0, "if op2==op3 then goto op1")
X(BEQ_ID_REG_INT, 275, FMT_L_R_I, FLOW_COND, 0, "if op2==op3 then goto op1")
X(FNDBLNK_REG_REG_REG, 276, FMT_R_R_R, FLOW_NEXT, 0, "op1 = find next blank in op2[op3] and behind")
X(FNDNBLNK_REG_REG_REG, 277, FMT_R_R_R, FLOW_NEXT, 0, "op1 = find next next non blank in op2[op3] and behind")
X(ISEX_REG, 278, FMT_R, FLOW_NEXT, 0, "dec op1 = -op1 (sign change)")
X(FSEX_REG, 279, FMT_R, FLOW_NEXT, 0, "float op1 = -op1 (sign change)")
X(GETTP_REG_REG, 280, FMT_R_R, FLOW_NEXT, 0, "gets the register type flag (op1 = op2.typeflag)")
X(SETTP_REG_INT, 281, FMT_R_I, FLOW_NEXT, 0, "sets the register type flag (op1.typeflag = op2)")
X(LOADSETTP_REG_INT_INT, 282, FMT_R_I_I, FLOW_NEXT, 0, "load register and sets the register type flag load op1=op2 (op1.typeflag = op3)")
X(LOADSETTP_REG_FLOAT_INT, 283, FMT_R_F_I, FLOW_NEXT, 0, "load register and sets the register type flag load op1=op2 (op1.typeflag = op3)")
X(LOADSETTP_REG_STRING_INT, 284, FMT_R_S_I, FLOW_NEXT, 0, "load register and sets the register type flag load op1=op2 (op1.typeflag = op3)")
X(SETORTP_REG_INT, 285, FMT_R_I, FLOW_NEXT, 0, "or the register type flag (op1.typeflag = op1.typeflag | op2)")
X(GETANDTP_REG_REG_INT, 286, FMT_R_R_I, FLOW_NEXT, 0, "get the register type flag with mask (op1(int) = op2.typeflag & op3)")
X(BRTPT_ID_REG, 287, FMT_L_R, FLOW_COND, 0, "if op2.typeflag true then goto op1")
X(BRTPANDT_ID_REG_INT, 288, FMT_L_R_I, FLOW_COND, 0, "if op2.typeflag && op3 true then goto op1")
X(OPENDLL_REG_REG_REG, 289, FMT_R_R_R, FLOW_NEXT, 0, "open DLL")
X(DLLPARMS_REG_REG_REG, 290, FMT_R_R_R, FLOW_NEXT, 0, "fetches parms for DLL call ")
X(IRAND_REG_REG, 291, FMT_R_R, FLOW_NEXT, 0, "random number random, op1=irand(op2)")
X(IRAND_REG_INT, 292, FMT_R_I, FLOW_NEXT, 0, "random number random, op1=irand(op2)")
X(RXVERS_REG, 293, FMT_R, FLOW_NEXT, 0, "get version, op1=version details")
X(GETENV_REG_REG, 294, FMT_R_R, FLOW_NEXT, 0, "get environment variable, op1=env[op2]")
X(GETENV_REG_STRING, 295, FMT_R_S, FLOW_NEXT, 0, "get environment variable, op1=env[op2]")
X(RXHASH_REG_REG_REG, 296, FMT_R_R_R, FLOW_NEXT, 0, "returns hash value, etc, op1=hash(op2,len(op3))")
X(GETATTRS_REG_REG, 297, FMT_R_R, FLOW_NEXT, 0, "get number attributes op1 = op2.num_attributes")
X(GETATTRS_REG_REG_INT, 298, FMT_R_R_I, FLOW_NEXT, 0, "get number attributes op1 = op2.num_attributes + op3")
X(SETATTRS_REG_REG, 299, FMT_R_R, FLOW_NEXT, 0, "set number attributes op1.num_attributes = op2")
X(SETATTRS_REG_INT, 300, FMT_R_I, FLOW_NEXT, 0, "set number attributes op1.num_attributes = op2")
X(SETATTRS_REG_REG_INT, 301, FMT_R_R_I, FLOW_NEXT, 0, "set number attributes op1.num_attributes = op2 + op3")
X(SETATTRS_REG_INT_INT, 302, FMT_R_I_I, FLOW_NEXT, 0, "set number attributes op1.num_attributes = op2 + op3")
X(GETABUFS_REG_REG, 303, FMT_R_R, FLOW_NEXT, 0, "get attribute buffer size op1 = op2.max_attributes")
X(MINATTRS_REG_REG, 304, FMT_R_R, FLOW_NEXT, 0, "ensure min number attributes op1.num_attributes >= op2")
X(MINATTRS_REG_INT, 305, FMT_R_I, FLOW_NEXT, 0, "ensure min number attributes op1.num_attributes >= op2")
X(MINATTRS_REG_REG_INT, 306, FMT_R_R_I, FLOW_NEXT, 0, "ensure min number attributes op1.num_attributes >= op2 + op3")
X(MINATTRS_REG_INT_INT, 307, FMT_R_I_I, FLOW_NEXT, 0, "ensure min number attributes op1.num_attributes >= op2 + op3")
X(ERASE_REG, 308, FMT_R, FLOW_NEXT, 0, "erases register contents")
X(SPAWN_REG_REG_REG, 309, FMT_R_R_R, FLOW_NEXT, 0, "Spawn Process op1 = exec op2 redirect op3")
X(REDIR2STR_REG_REG, 310, FMT_R_R, FLOW_NEXT, 0, "Redirect op1 -> string op2")
X(REDIR2ARR_REG_REG, 311, FMT_R_R, FLOW_NEXT, 0, "Redirect op1 -> array op2")
X(STR2REDIR_REG_REG, 312, FMT_R_R, FLOW_NEXT, 0, "Redirect op1 <- string op2")
X(ARR2REDIR_REG_REG, 313, FMT_R_R, FLOW_NEXT, 0, "Redirect op1 <- array op2")
X(NULLREDIR_REG, 314, FMT_R, FLOW_NEXT, 0, "Redirect op1 = to/from null")
X(FOPEN_REG_REG_REG, 315, FMT_R_R_R, FLOW_NEXT, 0, "op1 file*(int) = fopen filename op2(string) mode op3(string)")
X(FCLOSE_REG_REG, 316, FMT_R_R, FLOW_NEXT, 0, "op1 rc(int) = fclose op2 file*(int)")
X(FFLUSH_REG_REG, 317, FMT_R_R, FLOW_NEXT, 0, "op1 rc(int) = fflush op2 file*(int)")
X(FREADB_REG_REG_REG, 318, FMT_R_R_R, FLOW_NEXT, 0, "op1(binary) = fread op2 file*(int) op3 bytes(int)")
X(FREADLINE_REG_REG, 319, FMT_R_R, FLOW_NEXT, 0, "op1 (string) = read until newline op2 file*(int)")
X(FREADBYTE_REG_REG, 320, FMT_R_R, FLOW_NEXT, 0, "op1 (int) = read byte op2 file*(int)")
X(FREADCDPT_REG_REG, 321, FMT_R_R, FLOW_NEXT, 0, "op1 (string and int) = read codepoint op2 file*(int)")
X(FWRITE_REG_REG, 322, FMT_R_R, FLOW_NEXT, 0, "fwrite to op1 file*(int) from op2(string)")
X(FWRITEB_REG_REG, 323, FMT_R_R, FLOW_NEXT, 0, "fwrite to op1 file*(int) from op2(binary)")
X(FWRITEBYTE_REG_REG, 324, FMT_R_R, FLOW_NEXT, 0, "write byte to op1 file*(int) op2 source(int)")
X(FWRITECDPT_REG_REG, 325, FMT_R_R, FLOW_NEXT, 0, "write codepoint to op1 file*(int) op2 source(int)")
X(FCLEARERR_REG, 326, FMT_R, FLOW_NEXT, 0, "clearerr op1 file*(int)")
X(FEOF_REG_REG, 327, FMT_R_R, FLOW_NEXT, 0, "op1 rc(int) = feof op2 file*(int)")
X(FERROR_REG_REG, 328, FMT_R_R, FLOW_NEXT, 0, "op1 rc(int) = ferror op2 file*(int)")
X(SIGNAL_STRING, 329, FMT_S, FLOW_NEXT, 0, "Signal type op1")
X(SIGNALT_STRING_REG, 330, FMT_S_R, FLOW_NEXT, 0, "Signal type op1 if op2 true")
X(SIGNALF_STRING_REG, 331, FMT_S_R, FLOW_NEXT, 0, "Signal type op1 if op2 false")
X(SIGNAL_STRING_STRING, 332, FMT_S_S, FLOW_NEXT, 0, "Signal type op1 (message op2)")
X(SIGNAL_STRING_REG, 333, FMT_S_R, FLOW_NEXT, 0, "Signal type op1 (payload op2)")
X(SIGNALT_STRING_STRING_REG, 334, FMT_S_S_R, FLOW_NEXT, 0, "Signal type op1 (message op2) if op3 true")
X(SIGNALF_STRING_STRING_REG, 335, FMT_S_S_R, FLOW_NEXT, 0, "Signal type op1 (message op2) if op3 false")
X(BPON_FUNC, 336, FMT_P, FLOW_NEXT, 0, "Enable Breakpoints with op1 handler")
X(BPON, 337, FMT_EMPTY, FLOW_NEXT, 0, "Enable Breakpoints with existing handler")
X(BPOFF, 338, FMT_EMPTY, FLOW_NEXT, 0, "Disable Breakpoints")
X(SIGIGNORE_STRING, 339, FMT_S, FLOW_NEXT, 0, "Set Signal op1 Handle to Ignore")
X(SIGHALT_STRING, 340, FMT_S, FLOW_NEXT, 0, "Set Signal op1 Handle to Halt")
X(SIGSHALT_STRING, 341, FMT_S, FLOW_NEXT, 0, "Set Signal op1 Handle to Silent Halt")
X(SIGBR_ID_STRING, 342, FMT_L_S, FLOW_NEXT, 0, "Set Signal op2 Handle to Branch to op1")
X(SIGCALL_FUNC_STRING, 343, FMT_P_S, FLOW_NEXT, 0, "Set Signal op2 Handle to Call op1")
X(SIGCALLBR_ID_FUNC_STRING, 344, FMT_L_P_S, FLOW_NEXT, 0, "Set Signal op3 Handle to Call op2 returning to op1")
X(SIGRET_STRING, 345, FMT_S, FLOW_NEXT, 0, "Set Signal op1 Handle to Return")
X(ICHKRNG_REG_INT_INT, 346, FMT_R_I_I, FLOW_NEXT, 0, "if op1<op2 | op1>op3 signal OUT_OF_RANGE")
X(ICHKRNG_REG_INT_REG, 347, FMT_R_I_R, FLOW_NEXT, 0, "if op1<op2 | op1>op3 signal OUT_OF_RANGE")
X(ICHKRNG_REG_REG_REG, 348, FMT_R_R_R, FLOW_NEXT, 0, "if op1<op2 | op1>op3 signal OUT_OF_RANGE")
X(ICHKRNG_INT_INT_REG, 349, FMT_I_I_R, FLOW_NEXT, 0, "if op1<op2 | op1>op3 signal OUT_OF_RANGE")
X(ICHKRNG_INT_REG_REG, 350, FMT_I_R_R, FLOW_NEXT, 0, "if op1<op2 | op1>op3 signal OUT_OF_RANGE")
X(SETNUMDGTS_REG, 351, FMT_R, FLOW_NEXT, 0, "Set Numeric Digits digits=op1 (>4)")
X(SETNUMDGTS_INT, 352, FMT_I, FLOW_NEXT, 0, "Set Numeric Digits digits=op1 (>4)")
X(GETNUMDGTS_REG, 353, FMT_R, FLOW_NEXT, 0, "Get Numeric Digits op1=digits")
X(SETNUMFUZ_REG, 354, FMT_R, FLOW_NEXT, 0, "Set Numeric Fuzz digits=op1 (>=0)")
X(SETNUMFUZ_INT, 355, FMT_I, FLOW_NEXT, 0, "Set Numeric Fuzz digits=op1 (>=0)")
X(GETNUMFUZ_REG, 356, FMT_R, FLOW_NEXT, 0, "Get Numeric Fuzz op1=digits")
X(SETNUMFRM_REG, 357, FMT_R, FLOW_NEXT, 0, "Set Numeric Form=op1 (1=sci,2=eng)")
X(SETNUMFRM_INT, 358, FMT_I, FLOW_NEXT, 0, "Set Numeric Form=op1 (1=sci,2=eng)")
X(GETNUMFRM_REG, 359, FMT_R, FLOW_NEXT, 0, "Get Numeric Form=op1 (1=sci,2=eng)")
X(SETNUMCAS_REG, 360, FMT_R, FLOW_NEXT, 0, "Set Numeric Case=op1 (1=lower,2=upper)")
X(SETNUMCAS_INT, 361, FMT_I, FLOW_NEXT, 0, "Set Numeric Case=op1 (1=lower,2=upper)")
X(GETNUMCAS_REG, 362, FMT_R, FLOW_NEXT, 0, "Get Numeric Case=op1 (1=lower,2=upper)")
X(SETNUMSTD_REG, 363, FMT_R, FLOW_NEXT, 0, "Set Numeric Standard=op1 (1=common,2=classic)")
X(SETNUMSTD_INT, 364, FMT_I, FLOW_NEXT, 0, "Set Numeric Standard=op1 (1=common,2=classic)")
X(GETNUMSTD_REG, 365, FMT_R, FLOW_NEXT, 0, "Get Numeric Standard=op1 (1=common,2=classic)")
X(NUMSCI_INT_INT_INT, 366, FMT_I_I_I, FLOW_NEXT, 0, "Setup Scientific Numeric digits=op1, case=op2, std=op3, fuzz=0, form=sci")
X(NUMENG_INT_INT_INT, 367, FMT_I_I_I, FLOW_NEXT, 0, "Setup Engineering Numeric digits=op1, case=op2, std=op3, fuzz=0, form=eng")
X(DECPLNM_REG_REG_REG, 368, FMT_R_R_R, FLOW_NEXT, 0, "Get Decimal Plugin Name op1=name op2=description op3=version")
X(STOD_REG, 369, FMT_R, FLOW_NEXT, 0, "Convert Decimal String to Decimal Number op1=s2dec(op2)")
X(DTOS_REG, 370, FMT_R, FLOW_NEXT, 0, "Convert Decimal Number to Decimal String op1=dec2s(op2)")
X(DTOI_REG, 371, FMT_R, FLOW_NEXT, 0, "Convert Decimal Number to Integer op1=dec2s(op2)")
X(DTOB_REG, 372, FMT_R, FLOW_NEXT, 0, "Convert Decimal Number to Boolean op1=dec2s(op2)")
X(ITOD_REG, 373, FMT_R, FLOW_NEXT, 0, "Convert Integer to Decimal Number op1=s2dec(op2)")
X(FTOD_REG, 374, FMT_R, FLOW_NEXT, 0, "Convert Float to Decimal Number op1=f2dec(op2)")
X(DTOF_REG, 375, FMT_R, FLOW_NEXT, 0, "Convert Decimal Number to Float op1=f2dec(op2)")
X(DSUB_REG_REG_REG, 376, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Subtract (op1=op2-op3)")
X(DSUB_REG_REG_DECIMAL, 377, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Subtract (op1=op2-op3)")
X(DSUB_REG_DECIMAL_REG, 378, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Subtract (op1=op2-op3)")
X(DADD_REG_REG_REG, 379, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Add (op1=op2-op3)")
X(DADD_REG_REG_DECIMAL, 380, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Add (op1=op2-op3)")
X(DMULT_REG_REG_REG, 381, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Multiply (op1=op2*op3)")
X(DMULT_REG_REG_DECIMAL, 382, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Multiply (op1=op2*op3)")
X(DDIV_REG_REG_REG, 383, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Divide (op1=op2/op3)")
X(DDIV_REG_REG_DECIMAL, 384, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Divide (op1=op2/op3)")
X(DDIV_REG_DECIMAL_REG, 385, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Divide (op1=op2/op3)")
X(DEQ_REG_REG_REG, 386, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Equals op1=(op2==op3)")
X(DEQ_REG_REG_DECIMAL, 387, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Equals op1=(op2==op3)")
X(DNE_REG_REG_REG, 388, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Not equals op1=(op2!=op3)")
X(DNE_REG_REG_DECIMAL, 389, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Not equals op1=(op2!=op3)")
X(DGT_REG_REG_REG, 390, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Greater than op1=(op2>op3)")
X(DGT_REG_REG_DECIMAL, 391, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Greater than op1=(op2>op3)")
X(DGT_REG_DECIMAL_REG, 392, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Greater than op1=(op2>op3)")
X(DGTE_REG_REG_REG, 393, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Greater than equals op1=(op2>=op3)")
X(DGTE_REG_REG_DECIMAL, 394, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Greater than equals op1=(op2>=op3)")
X(DGTE_REG_DECIMAL_REG, 395, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Greater than equals op1=(op2>=op3)")
X(DLT_REG_REG_REG, 396, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Less than op1=(op2<op3)")
X(DLT_REG_REG_DECIMAL, 397, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Less than op1=(op2<op3)")
X(DLT_REG_DECIMAL_REG, 398, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Less than op1=(op2<op3)")
X(DLTE_REG_REG_REG, 399, FMT_R_R_R, FLOW_NEXT, 0, "Decimal Less than equals op1=(op2<=op3)")
X(DLTE_REG_REG_DECIMAL, 400, FMT_R_R_D, FLOW_NEXT, 0, "Decimal Less than equals op1=(op2<=op3)")
X(DLTE_REG_DECIMAL_REG, 401, FMT_R_D_R, FLOW_NEXT, 0, "Decimal Less than equals op1=(op2<=op3)")
X(DGTBR_ID_REG_REG, 402, FMT_L_R_R, FLOW_NEXT, 0, "Decimal Greater than if (op2>op3) goto op1")
X(DLTBR_ID_REG_REG, 403, FMT_L_R_R, FLOW_NEXT, 0, "Decimal Less than if (op2<op3) goto op1")
X(DEQBR_ID_REG_REG, 404, FMT_L_R_R, FLOW_NEXT, 0, "Decimal Equal if (op2=op3) goto op1")
X(DCOPY_REG_REG, 405, FMT_R_R, FLOW_NEXT, 0, "Copy Decimal op2 to op1")
X(DEXTR_REG_REG_REG, 406, FMT_R_R_R, FLOW_NEXT, 0, "op3 decimal extracted to op1 string coefficient and op2 int decimal exponent")
X(DPOW_REG_REG_REG, 407, FMT_R_R_R, FLOW_NEXT, 0, "op1=op2**op3")
X(DPOW_REG_REG_DECIMAL, 408, FMT_R_R_D, FLOW_NEXT, 0, "op1=op2**op3")
X(DPOW_REG_DECIMAL_REG, 409, FMT_R_D_R, FLOW_NEXT, 0, "op1=op2**op3")
X(DSEX_REG, 410, FMT_R, FLOW_NEXT, 0, "Decimal op1 = -op1 (sign change)")
X(METALOADMODULE_REG_REG, 411, FMT_R_R, FLOW_NEXT, 0, "Load Module (op1 = module num of last loaded module in rxbin op2)")
X(METALOADEDMODULES_REG, 412, FMT_R, FLOW_NEXT, 0, "Loaded Modules (op1 = array loaded modules)")
X(METALOADEDPROCS_REG_REG, 413, FMT_R_R, FLOW_NEXT, 0, "Loaded Procedures (op1 = array procedures in module op2)")
X(METALOADEDEPROCS_REG_REG, 414, FMT_R_R, FLOW_NEXT, 0, "Loaded Exposed Procedures (op1 = array procedures in module op2)")
X(METALOADINST_REG_REG_REG, 415, FMT_R_R_R, FLOW_NEXT, 0, "Load Instruction Code (op1 = (inst)op2[op3])")
X(METADECODEINST_REG_REG, 416, FMT_R_R, FLOW_NEXT, 0, "Decode opcode (op1 decoded op2)")
X(METALOADIOPERAND_REG_REG_REG, 417, FMT_R_R_R, FLOW_NEXT, 0, "Load Integer/Index Operand (op1 = (int)op2[op3])")
X(METALOADFOPERAND_REG_REG_REG, 418, FMT_R_R_R, FLOW_NEXT, 0, "Load Float Operand (op1 = (float)op2[op3])")
X(METALOADSOPERAND_REG_REG_REG, 419, FMT_R_R_R, FLOW_NEXT, 0, "Load String Operand (op1 = (string)op2[op3])")
X(METALOADPOPERAND_REG_REG_REG, 420, FMT_R_R_R, FLOW_NEXT, 0, "Load Procedure Operand (op1 = (proc)op2[op3])")
X(METALOADDATA_REG_REG_REG, 421, FMT_R_R_R, FLOW_NEXT, 0, "Load Metadata (op1 = (metadata)op2[op3])")
X(METALINKPREG_REG_REG, 422, FMT_R_R, FLOW_NEXT, 0, "Link parent-frame-register[op2] to op1")
X(METALOADCALLERADDR_REG, 423, FMT_R, FLOW_NEXT, 0, "Load caller address object to op1")
X(INTERRUPT, 424, FMT_EMPTY, FLOW_NEXT, 0, "")
X(IUNKNOWN, 425, FMT_EMPTY, FLOW_NEXT, 0, "")
