#define ANYTHING                         1
#define SY_STRING                        2
#define SY_NUMBER                        3
#define SY_CONST_SYMBOL                  4
#define SY_VAR_SYMBOL                    5
#define SY_LABEL                         6
#define SY_EOS                           7
#define SY_EOC                           8
#define OP_EQUAL                         9
#define KW_THEN                         10
#define KW_ELSE                         11
#define KW_WHEN                         12
#define KW_OTHERWISE                    13
#define KW_END                          14
