#define TK_NULL                          1
#define TK_VREF                          2
#define TK_LIST                          3
#define TK_FUNCTION                      4
#define TK_REP                           5
#define TK_PARSEERROR                    6
#define TK_SYMBOL                        7
#define TK_ADDRESS                       8
#define TK_ARG                           9
#define TK_BY                           10
#define TK_CALL                         11
#define TK_DIGITS                       12
#define TK_DO                           13
#define TK_DROP                         14
#define TK_END                          15
#define TK_ENGINEERING                  16
#define TK_ERROR                        17
#define TK_EXIT                         18
#define TK_EXPOSE                       19
#define TK_EXTERNAL                     20
#define TK_FAILURE                      21
#define TK_FOR                          22
#define TK_FOREVER                      23
#define TK_FORM                         24
#define TK_FUZZ                         25
#define TK_HALT                         26
#define TK_INTERPRET                    27
#define TK_ITERATE                      28
#define TK_LEAVE                        29
#define TK_NAME                         30
#define TK_NOP                          31
#define TK_NOVALUE                      32
#define TK_NUMERIC                      33
#define TK_OFF                          34
#define TK_ON                           35
#define TK_OPTIONS                      36
#define TK_OTHERWISE                    37
#define TK_PARSE                        38
#define TK_PROCEDURE                    39
#define TK_PULL                         40
#define TK_PUSH                         41
#define TK_QUEUE                        42
#define TK_RETURN                       43
#define TK_SAY                          44
#define TK_SCIENTIFIC                   45
#define TK_SELECT                       46
#define TK_SIGNAL                       47
#define TK_SOURCE                       48
#define TK_STOP                         49
#define TK_SYNTAX                       50
#define TK_TO                           51
#define TK_TRACE                        52
#define TK_UNTIL                        53
#define TK_UPPER                        54
#define TK_VALUE                        55
#define TK_VAR                          56
#define TK_VERSION                      57
#define TK_WHEN                         58
#define TK_WHILE                        59
#define TK_WITH                         60
#define TK_SYMBOL_STEM                  61
#define TK_SYMBOL_COMPOUND              62
#define TK_EQUAL                        63
#define TK_CONST                        64
#define TK_STRING                       65
#define TK_BOPEN                        66
#define TK_BCLOSE                       67
#define TK_PLUS                         68
#define TK_MINUS                        69
#define TK_NOT                          70
#define TK_POWER                        71
#define TK_MULT                         72
#define TK_DIV                          73
#define TK_IDIV                         74
#define TK_REMAIN                       75
#define TK_CONCAT                       76
#define TK_NOT_EQUAL                    77
#define TK_GT                           78
#define TK_LT                           79
#define TK_GE                           80
#define TK_LE                           81
#define TK_EQUAL_EQUAL                  82
#define TK_NOT_EQUAL_EQUAL              83
#define TK_GT_STRICT                    84
#define TK_LT_STRICT                    85
#define TK_GE_STRICT                    86
#define TK_LE_STRICT                    87
#define TK_OR                           88
#define TK_XOR                          89
#define TK_AND                          90
#define TK_COMMA                        91
#define TK_LINEIN                       92
#define TK_IF                           93
#define TK_THEN                         94
#define TK_ELSE                         95
#define TK_LABEL                        96
#define TK_EOC                          97
#define TK_EOL                          98
#define TK_EOF                          99
