/*
 * cREXX License (MIT)
 *
 * Copyright (c) 2020-2026 Adrian Sutherland, Peter Jacob, René Jansen
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * Compiler Parser Wrapper
 */

#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include "rxcpbgmr.h"
#include "rxcpmain.h"
#include "rxcp_util.h"
#include "rxcp_exit.h"

static int rxcp_is_instruction_lead_token(int last_token_type) {
    return last_token_type == TK_EOC ||
           last_token_type == TK_THEN ||
           last_token_type == TK_ELSE ||
           last_token_type == TK_OTHERWISE;
}

int rexbpars(Context *context) {

    char *buff, *buff_end;
    size_t bytes;
    int token_type, last_token_type;
    Token *token, *t, *peek_token;
    void *parser;

    /* Create parser and set up tracing */
    parser = RexxBAlloc(malloc);
#ifndef NDEBUG
    if (context->debug_mode >= 2) RexxBTrace(stderr, "[PARSER] ");
    else RexxBTrace(context->traceFile, "Parser(B) >> ");
#endif

    peek_token = token_f(context, rexbscan(context));
    last_token_type = TK_EOC;
    int in_exit_instruction = 0;
    while (1) {
        const char *disabled_certified_primary;

        token = peek_token;
        if (token->token_type == TK_EOL) token->token_type = TK_EOC;
        token_type = token->token_type;

        if (token_type == TK_EOC) {
            in_exit_instruction = 0;
        }

        // Promotion
        disabled_certified_primary = NULL;
        if (context->disable_exits && token->token_string) {
            disabled_certified_primary = rxcp_match_certified_exit_primary(token->token_string, token->length);
        }
        if (rxcp_is_instruction_lead_token(last_token_type) &&
            token_type != TK_EOC &&
            token_type != TK_EOS &&
            token->token_string &&
            (rxcp_is_exit_primary(context, token->token_string, token->length) ||
             disabled_certified_primary)) {
            token_type = TK_EXIT_PRIMARY;
            token->token_type = TK_EXIT_PRIMARY;
            in_exit_instruction = 1;
        } else if (token_type == TK_VAR_SYMBOL) {
            if (in_exit_instruction && rxcp_is_exit_additional(context, token->token_string, token->length)) {
                token_type = TK_EXIT_TOKEN;
                token->token_type = TK_EXIT_TOKEN;
            }
        }

        // EOS Special Processing
        if (token_type == TK_EOS || token_type == TK_BADCOMMENT) {
            // Send an EOC
            if (last_token_type != TK_EOC) {
                RexxB(parser, TK_EOC, 0, context);
            }

            if (token_type == TK_BADCOMMENT) {
                RexxB(parser, TK_BADCOMMENT, token, context);

                t = token_f(context, TK_EOC);
                RexxB(parser, TK_EOC, t, context);
            }

            // Send EOS
            t = token_f(context, TK_EOS);
            RexxB(parser, TK_EOS, t, context);

            // Send a null
            RexxB(parser, 0, NULL, context);
            break;
        }

        peek_token = token_f(context, rexbscan(context));

        // Line Continuation
        if (token_type == TK_COMMA && peek_token->token_type == TK_EOL) {
            token_r(context);  /* Discard tokens , and EOC tokens */
            token_r(context);
            peek_token = token_f(context, rexbscan(context));
            continue;
        }

        // Skip multiple end of clause/line
        if (last_token_type == TK_EOC && token_type == TK_EOC) continue;


        /* Special Processing */
        if (token_type == TK_MINUSMINUS) {
            /* TODO Check for Check for C operator mode - when/if implemented!    */
            /* The TK_MINUSMINUS token is generated by -- in comments_nodash mode, */
            /* it needs to be converted to two TK_MINUS tokens                    */
            t = tok_splt(context, token, 1);
            token = t->token_next; /* In case tok_splt() changes token pointer - it doesn't currently */
            token_type = TK_MINUS;
            t->token_type = token_type;
            token->token_type = token_type;
            RexxB(parser, token_type, t, context);
        }

        if (token_type != TK_EOC && last_token_type == TK_EOC) {
            context->current_clause_token = token;
        }
        context->current_parser_token = token;
        context->next_parser_token = peek_token;
        if (context->debug_mode >= 2) fprintf(stderr, "[GLUE] Line %d: Passing Token %d (%s) to Parser\n", context->line, token_type, token_to_string(token_type));
        RexxB(parser, token_type, token, context);
        last_token_type = token_type;
    }

    /* Deallocate parser */
    RexxBFree(parser, free);
    return (0);
}
