/* STEP-05 explicit functional qualification. Not registered as a CTest aggregate. */
#include <fstream>
#if defined(__has_feature)
# if __has_feature(address_sanitizer)
#  define NI_QUALIFICATION_ASAN 1
# endif
#endif
#if defined(__SANITIZE_ADDRESS__) && !defined(NI_QUALIFICATION_ASAN)
# define NI_QUALIFICATION_ASAN 1
#endif
#ifndef NI_QUALIFICATION_ASAN
# define NI_QUALIFICATION_ASAN 0
#endif
#if NI_QUALIFICATION_ASAN
# include <sanitizer/allocator_interface.h>
#endif
#ifdef __APPLE__
#include <mach/mach.h>
#elif !defined(_WIN32)
#include <unistd.h>
#endif
static uint64_t resident_memory() {
#ifdef __APPLE__
    mach_task_basic_info_data_t info{};mach_msg_type_number_t count=MACH_TASK_BASIC_INFO_COUNT;
    check(task_info(mach_task_self(),MACH_TASK_BASIC_INFO,reinterpret_cast<task_info_t>(&info),&count)==KERN_SUCCESS,"RSS query");
    return info.resident_size;
#elif defined(_WIN32)
    PROCESS_MEMORY_COUNTERS info{};check(GetProcessMemoryInfo(GetCurrentProcess(),&info,sizeof(info)),"RSS query");return info.WorkingSetSize;
#else
    std::ifstream file("/proc/self/statm");uint64_t total=0,resident=0;file>>total>>resident;
    check(bool(file),"RSS query");return resident*uint64_t(sysconf(_SC_PAGESIZE));
#endif
}
static int64_t property(VM &vm,rxllama_token t,const char *key) {
    return vm.call(RXLLAMA_INFO_INT,{h(t),s(key)}).integer;
}
static uint64_t retained_memory(uint64_t rss) {
#if NI_QUALIFICATION_ASAN
    // S2-QA01: ASan quarantine/reserved pages are not retained live objects.
    // Keep RSS diagnostics; the same 32 MiB guard applies to live allocations.
    (void)rss;
    return __sanitizer_get_current_allocated_bytes();
#else
    return rss;
#endif
}
static std::string property_text(VM &vm,rxllama_token t,const char *key) {
    return vm.call(RXLLAMA_INFO_TEXT,{h(t),s(key)}).text;
}
static rxllama_token limited_config(VM &vm,const char *mode) {
    auto c=vm.call(RXLLAMA_CONFIG_CREATE).handle;
    vm.call(RXLLAMA_CONFIG_TEXT,{h(c),s("hardware_mode"),s(mode)});return c;
}
static void generation_output_boundary(VM &vm,rxllama_token session,rxllama_token config,
        GenerationReference &direct,const char *mode) {
    const std::string prompt="Explain photosynthesis.",system=".";
    auto rendered=GenerationReference::prompt(prompt,system);
    auto expected=direct.generate({prompt},32,system);
    check(expected.text[0].size()>rendered.size(),"output byte-limit fixture must exceed its input size");
    auto c=limited_config(vm,mode);
    vm.call(RXLLAMA_CONFIG_INT,{h(c),s("request_bytes"),i(int64_t(rendered.size()))});
    auto q=vm.call(RXLLAMA_REQUEST_OPEN,{h(session),h(c)}).handle;
    vm.call(RXLLAMA_ADD_PROMPT,{h(q),complete_text(system),complete_text(prompt)});vm.call(RXLLAMA_SUBMIT,{h(q)});
    std::string output;bool failed=false;auto begin=Clock::now();
    while(!failed) {
        rxllama_result state{};int status=vm.raw(RXLLAMA_PROCESS,{h(q),i(128)},state);
        check(status==0 || status==-8,"output byte-limit error status");failed=status==-8;
        auto chunk=vm.call(RXLLAMA_READ_TEXT,{h(q),i(1)});output.append(chunk.text,chunk.text_length);
        check(output.size()<=rendered.size() && rxllama_utf8_prefix(output)==ptrdiff_t(output.size()),"output byte bound or UTF-8 prefix");
        if(failed)check(std::string(chunk.finish)=="error","output byte-limit finish");
        check(failed || property_text(vm,q,"state")=="running","byte-limit fixture finished without rejection");
        check(Clock::now()-begin<std::chrono::minutes(10),"output byte-limit deadline");
    }
    check(!output.empty() && expected.text[0].compare(0,output.size(),output)==0,"byte-limit lost or altered valid prefix");
    vm.close(q);vm.close(c);
    equal(generate(vm,session,config,{"Name one animal."}),direct.generate({"Name one animal."}));
    std::cout<<"PASS: generated byte overflow, complete UTF-8 prefix, error finish and recovery "<<mode<<" cap="<<rendered.size()<<" published="<<output.size()<<'\n';
}
static void generation_boundaries(VM &vm,rxllama_token rt,rxllama_token session,
        rxllama_token config,GenerationReference &direct,const char *mode) {
    auto reserved=property(vm,rt,"reserved_bytes");
    auto c=limited_config(vm,mode);
    auto rendered=GenerationReference::prompt("Name one animal.");
    auto tokens=direct.tokenize(rendered).size();
    vm.call(RXLLAMA_CONFIG_INT,{h(c),s("request_tokens"),i(int64_t(tokens*2))});
    vm.call(RXLLAMA_CONFIG_INT,{h(c),s("request_rows"),i(2)});
    auto q=vm.call(RXLLAMA_REQUEST_OPEN,{h(session),h(c)}).handle;
    for(int j=0;j<2;++j)vm.call(RXLLAMA_ADD_PROMPT,{h(q),s(""),s("Name one animal.")});
    vm.reject(RXLLAMA_ADD_PROMPT,{h(q),s(""),s("third")});
    check(property(vm,q,"rows")==2,"row rejection changed inputs");
    vm.call(RXLLAMA_SUBMIT,{h(q)});check(property(vm,q,"input_tokens")==int64_t(tokens*2),"exact token budget");
    vm.reject(RXLLAMA_SUBMIT,{h(q)});vm.call(RXLLAMA_CANCEL,{h(q)});vm.close(q);
    vm.call(RXLLAMA_CONFIG_INT,{h(c),s("request_tokens"),i(int64_t(tokens*2-1))});
    q=vm.call(RXLLAMA_REQUEST_OPEN,{h(session),h(c)}).handle;
    for(int j=0;j<2;++j)vm.call(RXLLAMA_ADD_PROMPT,{h(q),s(""),s("Name one animal.")});
    vm.reject(RXLLAMA_SUBMIT,{h(q)});
    check(property_text(vm,q,"state")=="failed" && property(vm,q,"decode_calls")==0,"overflow partially computed");
    for(int row=1;row<=2;++row) {
        auto chunk=vm.call(RXLLAMA_READ_TEXT,{h(q),i(row)});
        check(chunk.text_length==0 && chunk.integer==0 && std::string(chunk.finish)=="error","failed row publication");
    }
    vm.reject(RXLLAMA_PROCESS,{h(q),i(128)});vm.close(q);vm.close(c);
    c=limited_config(vm,mode);vm.call(RXLLAMA_CONFIG_INT,{h(c),s("request_bytes"),i(int64_t(rendered.size()))});
    q=vm.call(RXLLAMA_REQUEST_OPEN,{h(session),h(c)}).handle;
    vm.reject(RXLLAMA_ADD_PROMPT,{h(q),s(""),s("Name one animal.x")});
    check(property(vm,q,"input_bytes")==0,"byte rejection changed input");
    vm.call(RXLLAMA_ADD_PROMPT,{h(q),s(""),s("Name one animal.")});
    check(property(vm,q,"input_bytes")==int64_t(rendered.size()),"exact rendered byte bound");
    vm.reject(RXLLAMA_ADD_PROMPT,{h(q),s(""),s("")});vm.call(RXLLAMA_CANCEL,{h(q)});vm.close(q);vm.close(c);
    q=vm.call(RXLLAMA_REQUEST_OPEN,{h(session),h(config)}).handle;
    for(auto bad:{std::string("\xc0\xaf"),std::string("\xf0\x9f")}) {
        vm.reject(RXLLAMA_ADD_PROMPT,{h(q),s(""),complete_text(bad)});
        vm.reject(RXLLAMA_ADD_PROMPT,{h(q),complete_text(bad),s("okay")});
    }
    check(property(vm,q,"rows")==0,"malformed input changed rows");vm.close(q);
    c=limited_config(vm,mode);vm.call(RXLLAMA_CONFIG_INT,{h(c),s("threads"),i(3)});
    vm.reject(RXLLAMA_REQUEST_OPEN,{h(session),h(c)});vm.close(c);
    // The template is part of the sequence budget: exactly 480+32 fits 512.
    std::string exact;
    while(direct.tokenize(GenerationReference::prompt(exact)).size()<480)exact+=" a";
    check(direct.tokenize(GenerationReference::prompt(exact)).size()==480,"480-token fixture");
    equal(generate(vm,session,config,{exact}),direct.generate({exact}));
    auto over=exact+" a";
    check(direct.tokenize(GenerationReference::prompt(over)).size()==481,"481-token fixture");
    q=vm.call(RXLLAMA_REQUEST_OPEN,{h(session),h(config)}).handle;
    vm.call(RXLLAMA_ADD_PROMPT,{h(q),s(""),complete_text(over)});vm.reject(RXLLAMA_SUBMIT,{h(q)});vm.close(q);
    equal(generate(vm,session,config,{"Name one animal."}),direct.generate({"Name one animal."}));
    check(property(vm,rt,"reserved_bytes")==reserved,"boundary reservation leak");
    std::cout<<"PASS: exact bytes/rows/tokens, 480+32/481+32 context, UTF-8 rejection, error finish and recovery "<<mode<<'\n';
}
struct StartTogether {
    std::mutex mutex;std::condition_variable changed;int arrived=0;int expected;bool failed=false;
    explicit StartTogether(int n):expected(n){}
    void wait(){std::unique_lock<std::mutex> lock(mutex);++arrived;changed.notify_all();
        check(changed.wait_for(lock,std::chrono::minutes(10),[&]{return arrived==expected || failed;}),"worker barrier deadline");
        check(!failed,"worker barrier aborted");}
    void abort(){std::lock_guard<std::mutex> lock(mutex);failed=true;changed.notify_all();}
};
static void generation_qualification(VM &vm,rxllama_token rt,rxllama_token model,
        rxllama_token session,rxllama_token config,GenerationReference &direct,char **argv) {
    generation_boundaries(vm,rt,session,config,direct,argv[1]);
    generation_output_boundary(vm,session,config,direct,argv[1]);
    std::vector<std::string> texts={"Name one animal.","What is two plus two?","Say hello in French.","Name one planet."};
    auto single=direct.generate({texts[0]}),batch=direct.generate(texts);
    for(int j=0;j<2;++j){equal(generate(vm,session,config,{texts[0]}),single);equal(generate(vm,session,config,texts),batch);}
    maximum_generation_unit_ms=0;
    auto before=resident_memory();auto peak=before;auto completed=property(vm,session,"completed_requests");
    auto retained_before=retained_memory(before),retained_peak=retained_before;
    auto sample_memory=[&](const std::string &label) {
        auto rss=resident_memory();peak=std::max(peak,rss);
        auto retained=retained_memory(rss);retained_peak=std::max(retained_peak,retained);
        std::cout<<"RSS_"<<label<<'='<<rss<<"\nRETENTION_"<<label<<'='<<retained<<'\n';
        return rss;
    };
    std::cout<<"RSS_BEFORE="<<before<<'\n';
    std::cout<<"RETENTION_METRIC="<<(NI_QUALIFICATION_ASAN?"asan_live_allocations":"process_rss")<<"\nRETENTION_BEFORE="<<retained_before<<'\n';
    for(int j=0;j<100;++j){equal(generate(vm,session,config,{texts[0]}),single);if((j+1)%20==0)sample_memory("SINGLE_"+std::to_string(j+1));}
    for(int j=0;j<20;++j)equal(generate(vm,session,config,texts),batch);
    auto after=sample_memory("AFTER");
    check(retained_peak<=retained_before+32*1024*1024,"retained memory growth exceeds 32 MiB");
    check(property(vm,session,"completed_requests")==completed+120 && property(vm,model,"load_count")==1,"sustained completion/load count");
    std::cout<<"PASS: 100 singles and 20 four-row batches "<<argv[1]<<" rss_before="<<before<<" rss_after="<<after<<" max_growth="<<(peak-before)<<" retention_guard_growth="<<(retained_peak-retained_before)<<'\n';
    std::cout<<"MAX_ISOLATED_UNIT_MS="<<maximum_generation_unit_ms<<'\n';
#if defined(NDEBUG) && !NI_QUALIFICATION_ASAN
    // Same ordinary Release-only timing gate as STEP-02 CMakeLists.txt.
    check(maximum_generation_unit_ms<=250,"isolated warm unit exceeds 250 ms target");
#endif
    // Private context allocation/warm-up can be closed at each exposed boundary.
    for(int units:{0,1,2}) {
        auto partial=vm.call(RXLLAMA_SESSION_OPEN,{h(model),s("generation"),h(config)}).handle;
        for(int j=0;j<units;++j)vm.call(RXLLAMA_PREPARE,{h(partial),i(1)});
        vm.close(partial);
    }
    auto identity=property_text(vm,model,"shared_model_id");
    std::vector<std::vector<std::string>> worker_texts;
    std::vector<GenerationReference::Output> worker_expected;
    for(int id=0;id<4;++id) {
        auto unique=texts;std::rotate(unique.begin(),unique.begin()+id,unique.end());
        worker_expected.push_back(direct.generate(unique));worker_texts.push_back(std::move(unique));
    }
    for(int count:{1,2,4}) {
        StartTogether gate(count);std::vector<std::thread> threads;std::vector<std::string> failures(size_t(count),"");
        std::atomic<int> active{0},maximum{0};std::vector<double> unit_times(size_t(count),0);
        for(int id=0;id<count;++id)threads.emplace_back([&,id] {
            try {
                VM worker;auto c=limited_config(worker,argv[1]);auto runtime=worker.call(RXLLAMA_RUNTIME_OPEN,{h(c)}).handle;
                auto m=worker.call(RXLLAMA_MODEL_OPEN,{h(runtime),s(argv[2]),s(argv[3]),s("smollm2-360m-instruct"),h(c)}).handle;
                check(worker.ready(m)=="ready" && property_text(worker,m,"shared_model_id")==identity,"worker did not share weights");
                worker.reject(RXLLAMA_INFO_INT,{h(model),s("load_count")});
                auto private_session=worker.call(RXLLAMA_SESSION_OPEN,{h(m),s("generation"),h(c)}).handle;worker.prepare(private_session);
                maximum_generation_unit_ms=0;gate.wait();
                auto now=++active;auto prior=maximum.load();while(prior<now && !maximum.compare_exchange_weak(prior,now)){}
                for(int repeat=0;repeat<20;++repeat)equal(generate(worker,private_session,c,worker_texts[size_t(id)]),worker_expected[size_t(id)]);
                --active;unit_times[size_t(id)]=maximum_generation_unit_ms;
                check(property(worker,m,"load_count")==1 && property(worker,private_session,"completed_requests")==20,"private worker completion/load count");
                worker.close(private_session);worker.close(m);
                check(property(worker,runtime,"reserved_bytes")==0,"worker reservation leak");worker.close(runtime);worker.close(c);
            }catch(const std::exception &e){failures[size_t(id)]=e.what();gate.abort();}
        });
        for(auto &t:threads)t.join();for(auto &error:failures)if(!error.empty())throw std::runtime_error("generation worker: "+error);
        double longest=*std::max_element(unit_times.begin(),unit_times.end());
        std::cout<<"MAX_CONCURRENT_UNIT_MS_"<<count<<'='<<longest<<'\n';
        // STEP-02 snapshots/gates isolated warm units before launching parallel
        // jobs. Concurrent wall time includes other owners' CPU/GPU scheduling;
        // retain it as diagnostic evidence without inventing a queue deadline.
        check(maximum==count && property(vm,model,"owner_count")==1,"workers did not overlap or release owners");
        std::cout<<"PASS: "<<count<<" concurrent VM owners x 20 batches, shared_id="<<identity<<" overlap="<<maximum<<'\n';
    }
    auto bge=vm.call(RXLLAMA_MODEL_OPEN,{h(rt),s(argv[4]),s(argv[5]),s("bge-small-en-v1.5"),h(config)}).handle;
    check(vm.ready(bge)=="ready","co-resident BGE ready");
    auto embedding=vm.call(RXLLAMA_SESSION_OPEN,{h(bge),s("embedding"),h(config)}).handle;vm.prepare(embedding);
    auto embed=[&] {
        auto q=vm.call(RXLLAMA_REQUEST_OPEN,{h(embedding),h(config)}).handle;
        vm.call(RXLLAMA_ADD_EMBEDDING,{h(q),s("A cat sits near the window."),s("document")});vm.call(RXLLAMA_SUBMIT,{h(q)});
        vm.call(RXLLAMA_PROCESS,{h(q),i(128)});auto result=vm.call(RXLLAMA_EMBEDDINGS,{h(q)});
        check(result.value_count==384,"co-resident embedding shape");std::vector<double> values(result.values,result.values+384);vm.close(q);return values;
    };
    auto expected=embed();
    for(int j=0;j<5;++j){equal(generate(vm,session,config,texts),batch);auto values=embed();for(size_t d=0;d<384;++d)check(std::abs(values[d]-expected[d])<=0.00001,"co-resident embedding changed");}
    check(property(vm,rt,"reserved_bytes")<=INT64_C(4294967296) && peak_memory()<=UINT64_C(4294967296),"co-resident 4 GiB budget");
    std::cout<<"PASS: co-resident embeddings and generation, reserved="<<property(vm,rt,"reserved_bytes")<<" peak_bytes="<<peak_memory()<<'\n';
    vm.close(embedding);vm.close(bge);
}
// Separate processes give comparable one-model peaks, without the parity
// fixture's intentionally separate direct/provider model allocations.
static int generation_memory_control(int argc,char **argv) {
    check(argc==6,"usage: --memory-direct|--memory-provider MODE MODEL HASH SESSIONS");
    int count=std::stoi(argv[5]);check(count==1 || count==4,"memory session count");
    bool direct_mode=std::string(argv[1])=="--memory-direct",gpu=std::string(argv[2])!="cpu";
    VM vm;auto config=limited_config(vm,argv[2]);auto rt=vm.call(RXLLAMA_RUNTIME_OPEN,{h(config)}).handle;
    std::vector<std::string> texts(4,"Name one animal.");int64_t signature=0,tokens=0;
    auto inspect=[&](const GenerationReference::Output &out){
        signature=0;tokens=0;for(auto &row:out.tokens)for(auto token:row){signature+=token;++tokens;}
        check(tokens>0 && out.text.size()==4,"memory-control output");
    };
    if(direct_mode) {
        GenerationReference direct(argv[3],gpu);
        using Context=std::unique_ptr<llama_context,decltype(&llama_free)>;
        std::vector<Context> contexts;
        for(int j=1;j<count;++j) {
            auto cp=llama_context_default_params();cp.n_ctx=4096;cp.n_seq_max=8;cp.n_batch=512;cp.n_ubatch=128;
            cp.n_outputs_max=8;cp.n_outputs_max_per_seq=1;cp.n_threads=gpu?2:4;cp.n_threads_batch=cp.n_threads;
            cp.embeddings=false;cp.pooling_type=LLAMA_POOLING_TYPE_NONE;cp.offload_kqv=gpu;cp.op_offload=gpu;cp.no_perf=false;
            contexts.emplace_back(llama_init_from_model(direct.model.get(),cp),llama_free);
            check(bool(contexts.back()),"direct private context");
        }
        for(int j=0;j<count;++j) {
            if(j)direct.context.swap(contexts[size_t(j-1)]);
            for(int warm=0;warm<2;++warm)inspect(direct.generate(texts));
            if(j)direct.context.swap(contexts[size_t(j-1)]);
        }
        std::cout<<"RSS="<<resident_memory()<<"\nPEAK="<<peak_memory()<<'\n';
    }else {
        auto model=vm.call(RXLLAMA_MODEL_OPEN,{h(rt),s(argv[3]),s(argv[4]),s("smollm2-360m-instruct"),h(config)}).handle;
        check(vm.ready(model)=="ready","memory model ready");std::vector<rxllama_token> contexts;
        for(int j=0;j<count;++j) {
            auto session=vm.call(RXLLAMA_SESSION_OPEN,{h(model),s("generation"),h(config)}).handle;vm.prepare(session);contexts.push_back(session);
            for(int warm=0;warm<2;++warm)inspect(generate(vm,session,config,texts));
        }
        check(property(vm,model,"load_count")==1,"memory model sharing");
        std::cout<<"RSS="<<resident_memory()<<"\nPEAK="<<peak_memory()<<'\n';
        for(auto session:contexts)vm.close(session);vm.close(model);
    }
    vm.close(rt);vm.close(config);
    std::cout<<"TOKENS="<<tokens<<"\nSIGNATURE="<<signature<<"\nPASS: generation memory control "<<argv[1]<<' '<<argv[2]<<' '<<count<<'\n';return 0;
}
