# Explicit four-tool embedding check. Register after isolated Debug/ASan timing.
foreach(required BUILD SOURCE OUTPUT MODE MODEL HASH)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT}")
if(NOT DEFINED PROGRAM)
    set(PROGRAM embedding_acceptance)
endif()
if(NOT DEFINED MARKER)
    set(MARKER "PASS: rxllama persistent embedding acceptance")
endif()
set(compile_options "")
if(NO_OPT)
    list(APPEND compile_options -n)
endif()
set(program "${OUTPUT}/embedding")
function(run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 300)
    file(APPEND "${OUTPUT}/toolchain.log" "COMMAND: ${ARGV}\n${out}\n${err}\n")
    if(NOT rc EQUAL 0 OR "${out}\n${err}" MATCHES "FAIL:|PANIC:|FUNCTION_NOT_FOUND|ERROR:")
        message(FATAL_ERROR "Embedding command failed (${rc}); see ${OUTPUT}/toolchain.log")
    endif()
    set(last_output "${out}" PARENT_SCOPE)
endfunction()
file(WRITE "${OUTPUT}/toolchain.log" "")
if(NOT DEFINED CONSUMER)
    set(CONSUMER "${SOURCE}/tests/native-inference/${PROGRAM}.crexx")
endif()
run("${BUILD}/bin/rxc" --no-exe-import ${compile_options} -i "${BUILD}/bin" -o "${program}" "${CONSUMER}")
run("${BUILD}/bin/rxas" -o "${program}" "${program}")
# Explicit class/Level-G images satisfy attached-worker factories;
# binary import paths are compiler inputs, not runtime autoload search roots.
run("${BUILD}/bin/rxlink" -o "${program}-linked" "${program}" "${BUILD}/bin/library" "${BUILD}/bin/classlib" "${BUILD}/bin/rxfnsg")
foreach(vm rxbvm rxtvm)
    if(EXISTS "${BUILD}/bin/${vm}")
        run("${BUILD}/bin/${vm}" "${program}-linked" -a "${MODE}" "${MODEL}" "${HASH}")
        if(NOT last_output MATCHES "${MARKER}")
            message(FATAL_ERROR "Missing lifecycle positive marker: ${vm}")
        endif()
    endif()
endforeach()
message(STATUS "PASS: four-tool embedding ${MODE}")
