# Explicit four-tool lifecycle check. Register after isolated Debug/ASan timing.
foreach(required BUILD SOURCE OUTPUT MODE MODEL HASH PROFILE)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT}")
set(program "${OUTPUT}/lifecycle")
function(run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 300)
    file(APPEND "${OUTPUT}/toolchain.log" "COMMAND: ${ARGV}\n${out}\n${err}\n")
    if(NOT rc EQUAL 0 OR "${out}\n${err}" MATCHES "FAIL:|PANIC:|FUNCTION_NOT_FOUND|ERROR:")
        message(FATAL_ERROR "Lifecycle command failed (${rc}); see ${OUTPUT}/toolchain.log")
    endif()
    set(last_output "${out}" PARENT_SCOPE)
endfunction()
file(WRITE "${OUTPUT}/toolchain.log" "")
run("${BUILD}/bin/rxc" --no-exe-import -i "${BUILD}/bin" -o "${program}" "${SOURCE}/tests/native-inference/lifecycle_acceptance.crexx")
run("${BUILD}/bin/rxas" -o "${program}" "${program}")
run("${BUILD}/bin/rxlink" -o "${program}-linked" "${program}" "${BUILD}/bin/library")
foreach(vm rxbvm rxtvm)
    if(EXISTS "${BUILD}/bin/${vm}")
        run("${BUILD}/bin/${vm}" "${program}-linked" -a "${MODE}" "${MODEL}" "${HASH}" "${PROFILE}")
        if(NOT last_output MATCHES "PASS: rxllama lifecycle")
            message(FATAL_ERROR "Missing lifecycle positive marker: ${vm}")
        endif()
    endif()
endforeach()
message(STATUS "PASS: four-tool lifecycle ${MODE} ${PROFILE}")
