"""Compile the two private-header consumers before spending a full MSVC build.

The negative control removes only MSVC's atomics switch from each actual CMake
command. The positive control compiles that unchanged generated command. This
needs only configure-time headers, not the VM, toolchain or generated bytecode.
"""
import json
import os
from pathlib import Path
import subprocess
import sys
import time


def main(build):
    if os.name != 'nt':
        raise RuntimeError('This preflight requires the real Windows MSVC compiler')
    output = build / 'atomics-preflight'
    output.mkdir(parents=True, exist_ok=True)
    rows = [row for row in json.loads((build / 'compile_commands.json').read_text())
            if Path(row['file']).name == 'cri17_attached_provider_control.c']
    if len(rows) != 2:
        raise RuntimeError(f'Expected two attached-provider compile commands, got {len(rows)}')
    (output / 'compile-commands.json').write_text(json.dumps(rows, indent=2) + '\n')
    results = []
    for index, row in enumerate(rows, 1):
        command = row['command']
        if not any(flag in command for flag in ('/std:c11', '-std:c11')) or command.count('/experimental:c11atomics') != 1:
            raise RuntimeError('Generated command must declare both C11 and MSVC atomics')
        # Ninja creates object directories at configure time. Newer CMake also
        # supplies the output path explicitly; handle it when available.
        if row.get('output'):
            (Path(row['directory']) / row['output']).parent.mkdir(parents=True, exist_ok=True)
        for mode in ('negative', 'positive'):
            actual = command.replace('/experimental:c11atomics', '') if mode == 'negative' else command
            log = output / f'{index}-{mode}.log'
            started = time.monotonic()
            with log.open('wb') as stream:
                # A raw command string preserves CMake's Windows quoting under
                # CreateProcess. Do not POSIX-split paths or invoke a shell.
                result = subprocess.run(actual, cwd=row['directory'], shell=False,
                                        stdout=stream, stderr=subprocess.STDOUT, timeout=300)
            result_text = log.read_text(errors='replace')
            passed = (result.returncode != 0 and 'C atomic support is not enabled' in result_text
                      if mode == 'negative' else result.returncode == 0)
            results.append(dict(index=index, mode=mode, returncode=result.returncode,
                                elapsed_seconds=time.monotonic() - started, passed=passed))
            (output / 'summary.json').write_text(json.dumps(results, indent=2) + '\n')
            if not passed:
                raise RuntimeError(f'{index}-{mode} failed; inspect {log}')
            print(f'PASS: target {index}, {mode} MSVC atomics control', flush=True)


if __name__ == '__main__':
    main(Path(sys.argv[1]).resolve())
