# Explicit normal four-tool matrix. Not a nested CTest aggregate until STEP-06
# has measured isolated sanitizer scheduling; each command has its own deadline.
foreach(required BUILD SOURCE OUTPUT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT}")
if(WIN32)
    set(EXE_SUFFIX .exe)
endif()
if(NOT DEFINED RXC)
    set(RXC "${BUILD}/bin/rxc${EXE_SUFFIX}")
endif()
if(NOT DEFINED IMPORT_PATH)
    set(IMPORT_PATH "${BUILD}/bin\;${BUILD}/tests/rxpa")
endif()
if(NOT DEFINED PROVIDER_PATH)
    set(PROVIDER_PATH "${BUILD}/tests/rxpa/providers")
endif()
set(ENV{CREXX_PROVIDER_PATH} "${PROVIDER_PATH}")
function(run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 90)
    file(APPEND "${OUTPUT}/toolchain.log" "COMMAND: ${ARGV}\n${out}\n${err}\n")
    if(NOT rc EQUAL 0 OR "${out}\n${err}" MATCHES "FAIL:|PANIC:|FUNCTION_NOT_FOUND|ERROR:")
        message(FATAL_ERROR "Native objects command failed (${rc}); see ${OUTPUT}/toolchain.log")
    endif()
    set(last_output "${out}" PARENT_SCOPE)
endfunction()
file(WRITE "${OUTPUT}/toolchain.log" "")
foreach(mode IN ITEMS noopt opt)
    set(flags)
    if(mode STREQUAL "noopt")
        set(flags -n)
    endif()
    # Minimal imported named-factory parameter-scope crash regression.
    run("${RXC}" --no-exe-import ${flags} -i "${IMPORT_PATH}" -o "${OUTPUT}/${mode}-callback" "${SOURCE}/tests/rxpa/rxpa_objects_callback_compile.crexx")
    foreach(fixture IN ITEMS rxpa_objects rxpa_objects_class_only rxpa_objects_workers rxpa_objects_text_worker)
    set(program "${OUTPUT}/${mode}-${fixture}")
    run("${RXC}" --no-exe-import ${flags} -i "${IMPORT_PATH}" --import-resolution-report "${program}-imports.json" -o "${program}" "${SOURCE}/tests/rxpa/${fixture}.crexx")
    run("${BUILD}/bin/rxas${EXE_SUFFIX}" -o "${program}" "${program}")
    set(libraries "${BUILD}/bin/library")
    if(fixture STREQUAL "rxpa_objects_workers" OR fixture STREQUAL "rxpa_objects_text_worker")
        list(APPEND libraries "${BUILD}/bin/classlib" "${BUILD}/bin/rxfnsg")
    endif()
    run("${BUILD}/bin/rxlink${EXE_SUFFIX}" -o "${program}-linked" "${program}" ${libraries})
    if(DEFINED VM)
        set(vms "${VM}")
    else()
        set(vms "${BUILD}/bin/rxbvm${EXE_SUFFIX}")
        if(EXISTS "${BUILD}/bin/rxtvm${EXE_SUFFIX}")
            list(APPEND vms "${BUILD}/bin/rxtvm${EXE_SUFFIX}")
        endif()
    endif()
    foreach(vm IN LISTS vms)
            run("${vm}" "${program}-linked")
            if(NOT last_output MATCHES "PASS: C native")
                message(FATAL_ERROR "Missing native object acceptance marker")
            endif()
    endforeach()
    endforeach()
endforeach()
