cmake_minimum_required(VERSION 3.24)

foreach(_required_var IN ITEMS RXAS RXDAS SOURCE WORKING_DIRECTORY CASE)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "Missing required variable ${_required_var}")
    endif()
endforeach()

file(MAKE_DIRECTORY "${WORKING_DIRECTORY}/${CASE}")
get_filename_component(_stem "${SOURCE}" NAME_WE)
set(_output_base "${WORKING_DIRECTORY}/${CASE}/${_stem}")
set(_rxbin "${_output_base}.rxbin")
set(_disassembly "${WORKING_DIRECTORY}/${CASE}/${_stem}.rxas")

execute_process(
        COMMAND "${RXAS}" ${RXAS_FLAGS} -o "${_output_base}" "${SOURCE}"
        WORKING_DIRECTORY "${WORKING_DIRECTORY}/${CASE}"
        RESULT_VARIABLE _rxas_rc
        OUTPUT_VARIABLE _rxas_out
        ERROR_VARIABLE _rxas_err
)

if(NOT _rxas_rc EQUAL 0)
    message(FATAL_ERROR
            "rxas failed for ${SOURCE}\n"
            "case: ${CASE}\n"
            "stdout:\n${_rxas_out}\n"
            "stderr:\n${_rxas_err}")
endif()

execute_process(
        COMMAND "${RXDAS}" -o "${_disassembly}" "${_rxbin}"
        WORKING_DIRECTORY "${WORKING_DIRECTORY}/${CASE}"
        RESULT_VARIABLE _rxdas_rc
        OUTPUT_VARIABLE _rxdas_out
        ERROR_VARIABLE _rxdas_err
)

if(NOT _rxdas_rc EQUAL 0)
    message(FATAL_ERROR
            "rxdas failed for ${_rxbin}\n"
            "case: ${CASE}\n"
            "stdout:\n${_rxdas_out}\n"
            "stderr:\n${_rxdas_err}")
endif()

file(READ "${_disassembly}" _disassembly_text)
string(REPLACE "\r\n" "\n" _disassembly_text "${_disassembly_text}")
string(REPLACE "\r" "\n" _disassembly_text "${_disassembly_text}")

function(_optimizer_fail MESSAGE)
    message(FATAL_ERROR
            "${MESSAGE}\n"
            "case: ${CASE}\n"
            "source: ${SOURCE}\n"
            "disassembly: ${_disassembly}\n"
            "--- disassembly ---\n${_disassembly_text}")
endfunction()

function(_require REGEX DESCRIPTION)
    if(NOT _disassembly_text MATCHES "${REGEX}")
        _optimizer_fail("Expected ${DESCRIPTION}: ${REGEX}")
    endif()
endfunction()

function(_forbid REGEX DESCRIPTION)
    if(_disassembly_text MATCHES "${REGEX}")
        _optimizer_fail("Did not expect ${DESCRIPTION}: ${REGEX}")
    endif()
endfunction()

function(_count REGEX EXPECTED DESCRIPTION)
    string(REGEX MATCHALL "${REGEX}" _matches "${_disassembly_text}")
    list(LENGTH _matches _actual)
    if(NOT _actual EQUAL EXPECTED)
        _optimizer_fail("Expected ${EXPECTED} ${DESCRIPTION}, found ${_actual}: ${REGEX}")
    endif()
endfunction()

function(_require_debug REGEX DESCRIPTION)
    if(NOT _rxas_err MATCHES "${REGEX}")
        message(FATAL_ERROR
                "Expected ${DESCRIPTION}: ${REGEX}\n"
                "case: ${CASE}\n"
                "source: ${SOURCE}\n"
                "--- rxas stderr ---\n${_rxas_err}")
    endif()
endfunction()

set(_line_prefix "(^|\n)([ \t]*[A-Za-z_][A-Za-z0-9_]*:[ \t]*)?[ \t]*")
set(_line_suffix "[ \t]*(\\*|\n|$)")

if(CASE STREQUAL "fixed_registers_opt")
    foreach(_mnemonic IN ITEMS inc0 inc1 inc2 dec0 dec1 dec2)
        _require("${_line_prefix}${_mnemonic}${_line_suffix}" "${_mnemonic} shortcut")
    endforeach()
    foreach(_instruction IN ITEMS "inc r0" "inc r1" "inc r2" "dec r0" "dec r1" "dec r2")
        string(REPLACE " " "[ \t]+" _instruction_regex "${_instruction}")
        _forbid("${_line_prefix}${_instruction_regex}${_line_suffix}" "unoptimised ${_instruction}")
    endforeach()
    _require("${_line_prefix}inc[ \t]+r3${_line_suffix}" "non-shortcut inc r3")
    _require("${_line_prefix}dec[ \t]+r3${_line_suffix}" "non-shortcut dec r3")
elseif(CASE STREQUAL "fixed_registers_noopt")
    foreach(_instruction IN ITEMS "inc r0" "inc r1" "inc r2" "inc r3" "dec r0" "dec r1" "dec r2" "dec r3")
        string(REPLACE " " "[ \t]+" _instruction_regex "${_instruction}")
        _require("${_line_prefix}${_instruction_regex}${_line_suffix}" "unoptimised ${_instruction}")
    endforeach()
    foreach(_mnemonic IN ITEMS inc0 inc1 inc2 dec0 dec1 dec2)
        _forbid("${_line_prefix}${_mnemonic}${_line_suffix}" "shortcut ${_mnemonic} with -n")
    endforeach()
elseif(CASE STREQUAL "implicit_inc0_relevant")
    _require("${_line_prefix}inc0${_line_suffix}" "inc0")
    _count("${_line_prefix}swap[ \t]+r0,r1${_line_suffix}" 2 "r0/r1 swaps preserved across inc0")
elseif(CASE STREQUAL "implicit_inc0_unrelated")
    _require("${_line_prefix}inc0${_line_suffix}" "inc0")
    _count("${_line_prefix}swap[ \t]+r3,r4${_line_suffix}" 0 "unrelated r3/r4 swaps")
elseif(CASE STREQUAL "loadint_relevant")
    _require("${_line_prefix}load[ \t]+0,1${_line_suffix}" "implicit load 0,1")
    _count("${_line_prefix}swap[ \t]+r0,r1${_line_suffix}" 2 "r0/r1 swaps preserved across load 0,1")
elseif(CASE STREQUAL "loadint_unrelated")
    _require("${_line_prefix}load[ \t]+0,1${_line_suffix}" "implicit load 0,1")
    _count("${_line_prefix}swap[ \t]+r3,r4${_line_suffix}" 0 "unrelated r3/r4 swaps")
elseif(CASE STREQUAL "linkarg_relevant")
    _require("${_line_prefix}linkarg[ \t]+r0,0${_line_suffix}" "implicit argument register linkarg")
    _count("${_line_prefix}swap[ \t]+a0[^\n]*,a1[^\n]*(\n|$)" 2 "a0/a1 swaps preserved across linkarg r0,0")
elseif(CASE STREQUAL "linkarg_unrelated")
    _require("${_line_prefix}linkarg[ \t]+r0,0${_line_suffix}" "implicit argument register linkarg")
    _count("${_line_prefix}swap[ \t]+r3,r4${_line_suffix}" 0 "unrelated r3/r4 swaps")
elseif(CASE STREQUAL "copy_acopy_opt")
    _require("${_line_prefix}copy[ \t]+r1,r0${_line_suffix}" "full copy")
    _forbid("${_line_prefix}acopy[ \t]+r1,r0${_line_suffix}" "redundant acopy after full copy")
    _require("${_line_prefix}acopy[ \t]+r4,r2${_line_suffix}" "different-target acopy")
    _require("${_line_prefix}acopy[ \t]+r5,r0${_line_suffix}" "different-source acopy")
    _require("${_line_prefix}acopy[ \t]+r7,r6${_line_suffix}" "non-adjacent acopy")
    _require_debug("PERF3 legacy-rule procedure=main signature=d132e98f first=copy records=1,2" "stable legacy rule diagnostic identity")
elseif(CASE STREQUAL "copy_acopy_noopt")
    _require("${_line_prefix}copy[ \t]+r1,r0${_line_suffix}" "full copy")
    _require("${_line_prefix}acopy[ \t]+r1,r0${_line_suffix}" "acopy preserved with -n")
    _require("${_line_prefix}acopy[ \t]+r4,r2${_line_suffix}" "different-target acopy with -n")
    _require("${_line_prefix}acopy[ \t]+r5,r0${_line_suffix}" "different-source acopy with -n")
    _require("${_line_prefix}acopy[ \t]+r7,r6${_line_suffix}" "non-adjacent acopy with -n")
elseif(CASE STREQUAL "compare_branch")
    _count("${_line_prefix}beq[ \t]+[^,\n]+,r1,r2${_line_suffix}" 5 "fused ieq/brt register branches including TRACE deletion and unrelated opaque writes")
    _count("${_line_prefix}bne[ \t]+[^,\n]+,r1,r2${_line_suffix}" 2 "fused not-equal register branches")
    _require("${_line_prefix}beq[ \t]+[^,\n]+,r1,5${_line_suffix}" "inverted ine/brf immediate branch")
    _require("${_line_prefix}blt[ \t]+[^,\n]+,r1,r2${_line_suffix}" "fused ilt/brt register branch")
    _require("${_line_prefix}bge[ \t]+[^,\n]+,r1,3${_line_suffix}" "inverted ilt/brf immediate branch")
    _require("${_line_prefix}ble[ \t]+[^,\n]+,r1,r2${_line_suffix}" "fused ilte/brt register branch")
    _require("${_line_prefix}bgt[ \t]+[^,\n]+,r1,4${_line_suffix}" "inverted ilte/brf immediate branch")
    _require("${_line_prefix}bgt[ \t]+[^,\n]+,r1,r2${_line_suffix}" "fused igt/brt register branch")
    _require("${_line_prefix}ble[ \t]+[^,\n]+,r1,6${_line_suffix}" "inverted igt/brf immediate branch")
    _require("${_line_prefix}bge[ \t]+[^,\n]+,r1,r2${_line_suffix}" "fused igte/brt register branch")
    _require("${_line_prefix}blt[ \t]+[^,\n]+,r1,7${_line_suffix}" "inverted igte/brf immediate branch")
    _require("${_line_prefix}blt[ \t]+[^,\n]+,r1,8${_line_suffix}" "rewritten igt/brt int-register branch")
    _require("${_line_prefix}bgt[ \t]+[^,\n]+,r1,9${_line_suffix}" "rewritten igte/brf int-register branch")
    _require("${_line_prefix}bgt[ \t]+[^,\n]+,r1,10${_line_suffix}" "rewritten ilt/brt int-register branch")
    _require("${_line_prefix}blt[ \t]+[^,\n]+,r1,11${_line_suffix}" "rewritten ilte/brf int-register branch")
    _require("${_line_prefix}beq[ \t]+[^,\n]+,r1,37${_line_suffix}" "edge-aware fusion after all-paths call-window kill")
    _forbid("${_line_prefix}ieq[ \t]+r5,r1,37${_line_suffix}" "unfused all-paths-killed call-window comparison")
    _require("${_line_prefix}beq[ \t]+[^,\n]+,r0,r1${_line_suffix}" "fused in-place compare using the pre-write source ValueId")
    _count("${_line_prefix}ble[ \t]+[^,\n]+,r0,17${_line_suffix}" 2 "fused inverted in-place ilt/brf branches including a loop-backedge kill")
    _count("${_line_prefix}ieq[ \t]+r0,r1,32${_line_suffix}" 1 "compare whose boolean result remains live")
    _count("${_line_prefix}ieq[ \t]+r0,r1,r2${_line_suffix}" 1 "compare retained for an observed TRACE result")
    _count("${_line_prefix}ieq[ \t]+r0,r0,r2${_line_suffix}" 2 "in-place compares retained for hidden cleanup or linked storage")
    _count("${_line_prefix}ieq[ \t]+r0,r0,r1${_line_suffix}" 1 "in-place compare whose Boolean result remains live")
    _count("${_line_prefix}ieq[ \t]+r5,r1,3[3489]${_line_suffix}" 4 "compares retained for deprecated trim or observable call windows")
    _require("${_line_prefix}ieq[ \t]+r5,r1,40${_line_suffix}" "compare observed through a LINKed call-window register")
    foreach(_value IN ITEMS 41 42 43)
        _require("${_line_prefix}beq[ \t]+[^,\n]+,r1,${_value}${_line_suffix}" "fusion outside an exact one-shot call window")
        _forbid("${_line_prefix}ieq[ \t]+r5,r1,${_value}${_line_suffix}" "unfused one-shot call-window comparison")
    endforeach()
    _count("${_line_prefix}igt[ \t]+r0,r1,r2${_line_suffix}" 1 "older igtbr candidate whose boolean result remains live")
    _count("${_line_prefix}fgt[ \t]+r0,r1,r2${_line_suffix}" 1 "float compare retained until its signal contract is migrated")
    foreach(_cmp IN ITEMS ine ilt ilte igte)
        _forbid("${_line_prefix}${_cmp}[ \t]+" "unfused compare ${_cmp}")
    endforeach()
    _count("${_line_prefix}brt[ \t]+" 14 "conditional branches that still read an observed, unsafe or deferred boolean")
    _forbid("${_line_prefix}brf[ \t]+" "unfused conditional branch brf")
    _count("${_line_prefix}\\.traceevent[^\n]*\"O\"" 5 "retained unrelated or still-live operation trace events")
    foreach(_deleted IN ITEMS result-delete multi-delete-a multi-delete-b mixed-delete in-place-result-delete)
        _forbid("${_deleted}" "matching optimized-away Boolean TRACE event ${_deleted}")
    endforeach()
    foreach(_retained IN ITEMS unrelated-keep mixed-unrelated-keep-a mixed-unrelated-keep-b late-result-keep live-result-keep)
        _require("${_retained}" "retained TRACE event ${_retained}")
    endforeach()
    _require_debug("compare-branch-proof[^\n]*reason=trace-observed" "TRACE-observed compare-fusion rejection")
    _require_debug("compare-branch-proof[^\n]*reason=call-window-observed" "call-window compare-fusion rejection")
    _require_debug("compare-branch-proof[^\n]*reason=cleanup-required" "hidden-cleanup compare-fusion rejection")
    _require_debug("compare-branch-proof[^\n]*reason=destination-observable" "aliased or overlapping destination rejection")
    _require_debug("flow-use epoch=[^\n]*opaque-writes=2" "opaque writes remain barriers without becoming compare-result observations")
elseif(CASE STREQUAL "compare_branch_noopt")
    foreach(_cmp IN ITEMS ieq ine ilt ilte igt igte)
        _require("${_line_prefix}${_cmp}[ \t]+" "unoptimised compare ${_cmp}")
    endforeach()
    foreach(_branch IN ITEMS brt brf)
        _require("${_line_prefix}${_branch}[ \t]+" "unoptimised conditional branch ${_branch}")
    endforeach()
    _count("${_line_prefix}\\.traceevent[^\n]*\"O\"" 10 "all operation trace events preserved with -n")
    foreach(_trace IN ITEMS result-delete unrelated-keep multi-delete-a multi-delete-b mixed-delete mixed-unrelated-keep-a mixed-unrelated-keep-b late-result-keep live-result-keep)
        _require("${_trace}" "unoptimised TRACE event ${_trace}")
    endforeach()
    foreach(_fused IN ITEMS beq bne blt ble bgt bge)
        _forbid("${_line_prefix}${_fused}[ \t]+" "fused branch ${_fused} with -n")
    endforeach()
elseif(CASE STREQUAL "semantic_batch_flow")
    _forbid("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" "batched typed copy")
    _require("${_line_prefix}iadd[ \t]+r2,r0,1${_line_suffix}" "batched typed-copy redirect")
    _forbid("${_line_prefix}ieq[ \t]+r3,r4,5${_line_suffix}" "batched compare result")
    _require("${_line_prefix}beq[ \t]+[^,\n]+,r4,5${_line_suffix}" "batched fused compare branch")
    _require_debug("PERF3 semantic-batch procedure=semantic_batch_flow epoch=1 plans=2 records=4 deleted=2 opcodes=1 operand-records=2 status=applied" "one validated multi-family semantic batch")
    _require_debug("NR27 flow procedure=semantic_batch_flow[^\n]*semantic-batch=1 rejected=0 records=4 deleted=2 opcodes=1 operand-records=2" "single semantic batch summary")
elseif(CASE STREQUAL "local_single_use_copy")
    _forbid("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" "local single-use typed copy")
    _require("${_line_prefix}brt[ \t]+[^,\n]+,r0${_line_suffix}" "local single-use branch redirect")
    _require("${_line_prefix}iadd[ \t]+r5,r4,1${_line_suffix}" "TRACE-observed consumer")
    _require("${_line_prefix}\.traceevent[^\n]*observed-copy" "TRACE observation")
    _require_debug("reason=single-use-local-copy" "local write-once acceptance")
    _require_debug("NR27 flow procedure=local_single_use_copy[^\n]*local-single-use-copy=1" "local route summary")
elseif(CASE STREQUAL "branch_thread_flow")
    _count("${_line_prefix}brtf[ \t]+" 5 "threaded unconditional branches")
    _count("${_line_prefix}brt[ \t]+" 6 "threaded and deliberately retained true branches")
    _count("${_line_prefix}brf[ \t]+" 2 "threaded false branches")
    _count("${_line_prefix}br[ \t]+" 1 "non-leading target rejection")
    _require_debug("reason=immutable-cfg-branch-thread" "immutable-CFG branch-thread acceptance")
    _forbid("br-to-brt" "TRACE observation in a bypassed unreachable target block")
elseif(CASE STREQUAL "branch_thread_flow_noopt")
    _count("${_line_prefix}brtf[ \t]+" 1 "unoptimised two-target branch")
    _count("${_line_prefix}brt[ \t]+" 10 "unoptimised true branches")
    _count("${_line_prefix}brf[ \t]+" 5 "unoptimised false branches")
    _count("${_line_prefix}br[ \t]+" 7 "unoptimised unconditional branches")
    _require("br-to-brt" "TRACE observation preserved with -n")
elseif(CASE STREQUAL "unreachable_metadata_epoch")
    _forbid("dead" "metadata from an unreachable instruction-free block")
    _forbid("${_line_prefix}ieq[ \t]+r1,r0,0${_line_suffix}" "materialized comparison after epoch refresh")
    _forbid("result" "matching optimized comparison TRACE event")
    _require("${_line_prefix}bne[ \t]+[^,]+,r0,0${_line_suffix}" "K04 fusion after M00 metadata-only invalidation")
    _require_debug("NR27 flow procedure=unreachable_metadata_epoch[^\n]*compare-branch=1[^\n]*trace-delete=1" "fresh semantic epoch after M00 metadata cleanup")
elseif(CASE STREQUAL "duplicate_link_read")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 1 "linked reads")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 1 "read unlinks")
    _require("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "second read reuses first detached copy")
elseif(CASE STREQUAL "duplicate_link_read_meta_relevant")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 1 "linked reads across metadata observation")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 1 "read unlinks across metadata observation")
    _require("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "second read reuses unchanged detached copy across metadata observation")
elseif(CASE STREQUAL "duplicate_link_read_meta_unrelated")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 1 "linked reads across unrelated metadata")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 1 "read unlinks across unrelated metadata")
    _require("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "second read reuses first detached copy across unrelated metadata")
elseif(CASE STREQUAL "duplicate_link_read_trace_relevant")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 1 "linked reads across TRACE observation")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 1 "read unlinks across TRACE observation")
    _require("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "second read reuses unchanged detached copy across TRACE observation")
elseif(CASE STREQUAL "duplicate_link_read_trace_unrelated")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 1 "linked reads across unrelated trace")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 1 "read unlinks across unrelated trace")
    _require("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "second read reuses first detached copy across unrelated trace")
elseif(CASE STREQUAL "duplicate_link_read_bcopy")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 1 "linked binary reads")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 1 "binary read unlinks")
    _require("${_line_prefix}bcopy[ \t]+r4,r2${_line_suffix}" "second binary read reuses first detached copy")
elseif(CASE STREQUAL "duplicate_link_read_copy_families")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r(0|5|10|15)${_line_suffix}" 4 "one linked read per additional copy family")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 4 "one unlink per additional copy family")
    _require("${_line_prefix}copy[ \t]+r4,r2${_line_suffix}" "full-copy linked read reuse")
    _require("${_line_prefix}icopy[ \t]+r9,r7${_line_suffix}" "integer linked read reuse")
    _require("${_line_prefix}fcopy[ \t]+r14,r12${_line_suffix}" "float linked read reuse")
    _require("${_line_prefix}dcopy[ \t]+r19,r17${_line_suffix}" "decimal linked read reuse")
elseif(CASE STREQUAL "duplicate_link_read_source_changed")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 2 "linked reads retained after source change")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 2 "read unlinks retained after source change")
    _require("${_line_prefix}scopy[ \t]+r4,r3${_line_suffix}" "second read remains linked after source change")
    _forbid("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "stale detached-copy reuse after source change")
elseif(CASE STREQUAL "duplicate_link_read_detached_changed")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 2 "linked reads retained after detached-copy change")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 2 "read unlinks retained after detached-copy change")
    _require("${_line_prefix}scopy[ \t]+r4,r3${_line_suffix}" "second read remains linked after detached-copy change")
    _forbid("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "changed detached-copy reuse")
elseif(CASE STREQUAL "duplicate_link_read_call_alias")
    _count("${_line_prefix}link[ \t]+r[145],r0${_line_suffix}" 3 "source and call-argument aliases retained")
    _count("${_line_prefix}unlink[ \t]+r[145]${_line_suffix}" 3 "source and call-argument unlinks retained")
    _require("${_line_prefix}scopy[ \t]+r6,r5${_line_suffix}" "second read remains linked across aliased call")
    _forbid("${_line_prefix}scopy[ \t]+r6,r2${_line_suffix}" "detached-copy reuse across aliased call")
elseif(CASE STREQUAL "duplicate_link_read_divergent_phi")
    _count("${_line_prefix}link[ \t]+r[15],r0${_line_suffix}" 2 "linked reads retained across divergent source phi")
    _count("${_line_prefix}unlink[ \t]+r[15]${_line_suffix}" 2 "read unlinks retained across divergent source phi")
    _require("${_line_prefix}scopy[ \t]+r6,r5${_line_suffix}" "second read remains linked after divergent phi")
    _forbid("${_line_prefix}scopy[ \t]+r6,r2${_line_suffix}" "detached-copy reuse across divergent phi")
elseif(CASE STREQUAL "duplicate_linkattr_read")
    _count("${_line_prefix}linkattr1[ \t]+r[0-9]+,r0,1${_line_suffix}" 2 "attribute links including setup write")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 2 "attribute unlinks including setup write")
    _require("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "second attribute read reuses first detached copy")
elseif(CASE STREQUAL "duplicate_linkattr_read_bcopy")
    _count("${_line_prefix}linkattr1[ \t]+r[0-9]+,r0,1${_line_suffix}" 2 "binary attribute links including setup write")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 2 "binary attribute unlinks including setup write")
    _require("${_line_prefix}bcopy[ \t]+r4,r2${_line_suffix}" "second binary attribute read reuses first detached copy")
elseif(CASE STREQUAL "duplicate_linkattr_read_copy_families")
    _count("${_line_prefix}linkattr1[ \t]+r[0-9]+,r(0|7|14|21),1${_line_suffix}" 8 "setup and retained reads for four attribute copy families")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 8 "setup and retained unlinks for four attribute copy families")
    _require("${_line_prefix}copy[ \t]+r6,r4${_line_suffix}" "full-copy attribute read reuse")
    _require("${_line_prefix}icopy[ \t]+r13,r11${_line_suffix}" "integer attribute read reuse")
    _require("${_line_prefix}fcopy[ \t]+r20,r18${_line_suffix}" "float attribute read reuse")
    _require("${_line_prefix}dcopy[ \t]+r27,r25${_line_suffix}" "decimal attribute read reuse")
elseif(CASE STREQUAL "duplicate_linkattr_different")
    _count("${_line_prefix}linkattr1[ \t]+r[0-9]+,r0,[12]${_line_suffix}" 4 "attribute links for two setup writes and two reads")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 4 "attribute unlinks for two setup writes and two reads")
    _require("${_line_prefix}scopy[ \t]+r4,r3${_line_suffix}" "second read remains linked to the second attribute slot")
    _forbid("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "cross-slot detached-copy reuse")
elseif(CASE STREQUAL "duplicate_linkattr_count_changed")
    _count("${_line_prefix}linkattr1[ \t]+r[0-9]+,r0,1${_line_suffix}" 3 "attribute links retained across count generation")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 3 "attribute unlinks retained across count generation")
    _require("${_line_prefix}scopy[ \t]+r4,r3${_line_suffix}" "second attribute read uses current path")
    _forbid("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "attribute reuse across count generation")
elseif(CASE STREQUAL "duplicate_linkattr_unproved_signal")
    _count("${_line_prefix}linkattr1[ \t]+r[13],r0,1${_line_suffix}" 2 "unproved signalling attribute links retained")
    _count("${_line_prefix}unlink[ \t]+r[13]${_line_suffix}" 2 "post-signal unlinks retained")
    _require("${_line_prefix}scopy[ \t]+r4,r3${_line_suffix}" "second possibly signalling read retained")
    _forbid("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "signal-suppressing detached-copy reuse")
elseif(CASE STREQUAL "duplicate_linkattr_source_changed")
    _count("${_line_prefix}linkattr1[ \t]+r[0-9]+,r0,1${_line_suffix}" 4 "attribute setup, reads, and intervening write retained")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 4 "attribute unlinks retained across source write")
    _require("${_line_prefix}copy[ \t]+r4,r3${_line_suffix}" "full-copy read observes the changed attribute")
    _forbid("${_line_prefix}copy[ \t]+r4,r2${_line_suffix}" "full-copy reuse across attribute write")
elseif(CASE STREQUAL "duplicate_linkattr_owner_alias")
    _count("${_line_prefix}linkattr1[ \t]+r[0-9]+,r[07],1${_line_suffix}" 2 "setup and one retained attribute read through aliased owners")
    _require("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "owner alias resolves to the same attribute StorageId")
    _forbid("${_line_prefix}scopy[ \t]+r4,r3${_line_suffix}" "raw owner register blocks path reuse")
elseif(CASE STREQUAL "duplicate_linkattr_owner_different")
    _count("${_line_prefix}linkattr1[ \t]+r[0-9]+,r[07],1${_line_suffix}" 4 "different-owner attribute links retained")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 4 "different-owner attribute unlinks retained")
    _require("${_line_prefix}scopy[ \t]+r4,r3${_line_suffix}" "second owner retains its own linked read")
    _forbid("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "cross-owner detached-copy reuse")
elseif(CASE STREQUAL "nr09_class1")
    _require("${_line_prefix}swapn[ \t]+r0,r1,r2,r3${_line_suffix}" "two-swap superinstruction")
    _require("${_line_prefix}swapn[ \t]+r0,r1,r2,r3,r4,r5${_line_suffix}" "three-swap superinstruction")
    _require("${_line_prefix}swapn[ \t]+r0,r1,r2,r3,r4,r5,r6,r7${_line_suffix}" "four-swap superinstruction")
    _require("${_line_prefix}settpswap[ \t]+r0,256,r1${_line_suffix}" "settp/swap superinstruction")
    _require("${_line_prefix}loadsettp2[ \t]+r0,1,r1,256${_line_suffix}" "load/settp superinstruction")
    _require("${_line_prefix}loadsettpswap[ \t]+r0,2,r1,512,r2${_line_suffix}" "load/settp/swap superinstruction")
    _require("${_line_prefix}swapsettp[ \t]+r0,r1,r2,256${_line_suffix}" "swap/settp superinstruction")
    _require("${_line_prefix}swapsettpswap[ \t]+r0,r1,r2,512,r3${_line_suffix}" "swap/settp/swap superinstruction")
    _require("${_line_prefix}settpswapsettpswap[ \t]+r0,512,r1,r2,r3${_line_suffix}" "settp/swap/settp/swap superinstruction")
    _require("${_line_prefix}nulln[ \t]+r0,r1${_line_suffix}" "two-null superinstruction")
    _require("${_line_prefix}nulln[ \t]+r0,r1,r2${_line_suffix}" "three-null superinstruction")
    _require("${_line_prefix}nulln[ \t]+r0,r1,r2,r3${_line_suffix}" "four-null superinstruction")
    _require("${_line_prefix}load[ \t]+r1,10${_line_suffix}" "load/copy producer forwarded to the final destination")
    _forbid("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" "typed copy after producer forwarding")
    _require("${_line_prefix}load[ \t]+r0,11${_line_suffix}" "first distinct load remains expanded")
    _require("${_line_prefix}load[ \t]+r1,12${_line_suffix}" "second distinct load remains expanded")
    _require("${_line_prefix}load[ \t]+r0,13${_line_suffix}" "first equal load remains expanded")
    _require("${_line_prefix}load[ \t]+r1,13${_line_suffix}" "second equal load remains expanded")
elseif(CASE STREQUAL "nr09_class1_noopt")
    foreach(_fused IN ITEMS swapn settpswap loadsettp2 loadsettpswap swapsettp swapsettpswap settpswapsettpswap nulln)
        _forbid("${_line_prefix}${_fused}[ \t]+" "${_fused} with -n")
    endforeach()
    _require("${_line_prefix}swap[ \t]+r0,r1${_line_suffix}" "unoptimised swap")
    _require("${_line_prefix}settp[ \t]+r0,256${_line_suffix}" "unoptimised settp")
    _require("${_line_prefix}null[ \t]+r0${_line_suffix}" "unoptimised null")
    _require("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" "unoptimised icopy")
elseif(CASE STREQUAL "whole_procedure_flow")
    _count("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" 2 "typed copies retained only by other-view and TRACE cases")
    _require("${_line_prefix}load[ \t]+r1,7${_line_suffix}" "changed-source producer retargeted to the copied destination")
    _forbid("${_line_prefix}icopy[ \t]+r5,r4${_line_suffix}" "typed copy removed across a zero-argument call")
    _require("${_line_prefix}load[ \t]+r4,17${_line_suffix}" "zero-argument call leaves the original caller local unobserved")
    _require("${_line_prefix}ieq[ \t]+r6,r4,17${_line_suffix}" "post-call consumer redirects to the original value")
    _count("${_line_prefix}ieq[ \t]+r2,r0,(7|9)${_line_suffix}" 3 "compare consumers redirected to original integer registers")
    _count("${_line_prefix}ieq[ \t]+r2,r1,7${_line_suffix}" 2 "negative compare consumers kept on copied registers")
    _require("${_line_prefix}scopy[ \t]+r2,r1${_line_suffix}" "other-view negative consumer")
    _require("${_line_prefix}\\.traceevent[^\\n]*copy" "relevant TRACE observation")
    _count("${_line_prefix}load[ \t]+r0,3${_line_suffix}" 1 "redundant join load removed")
    _forbid("${_line_prefix}load[ \t]+r0,99${_line_suffix}" "unreachable load")
    _forbid("${_line_prefix}ieq[ \t]+r1,r0,99${_line_suffix}" "unreachable compare")
    _require("${_line_prefix}load[ \t]+r0,5${_line_suffix}" "dead integer load retained pending hidden-lifetime proof")
    _require("${_line_prefix}ieq[ \t]+r1,r0,5${_line_suffix}" "dead compare retained pending hidden-lifetime proof")
    _require("${_line_prefix}load[ \t]+r2,4\\.5${_line_suffix}" "dead float load retained pending hidden-lifetime proof")
elseif(CASE STREQUAL "whole_procedure_flow_noopt")
    _count("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" 6 "all r1/r0 typed copies with -n")
    _require("${_line_prefix}icopy[ \t]+r5,r4${_line_suffix}" "call-crossing typed copy with -n")
    _count("${_line_prefix}load[ \t]+r0,3${_line_suffix}" 2 "redundant loads with -n")
    _require("${_line_prefix}load[ \t]+r0,99${_line_suffix}" "unreachable load with -n")
    _require("${_line_prefix}ieq[ \t]+r1,r0,99${_line_suffix}" "unreachable compare with -n")
    _require("${_line_prefix}load[ \t]+r0,5${_line_suffix}" "dead integer load with -n")
    _require("${_line_prefix}load[ \t]+r2,4\\.5${_line_suffix}" "dead float load with -n")
elseif(CASE STREQUAL "whole_procedure_panel")
    _forbid("${_line_prefix}fcopy[ \t]+r11,r10${_line_suffix}" "proved float copy")
    _require("${_line_prefix}feq[ \t]+r9,r10,7\\.5${_line_suffix}" "float consumer redirected")
    _forbid("${_line_prefix}scopy[ \t]+r13,r12${_line_suffix}" "proved string copy")
    _require("${_line_prefix}seq[ \t]+r9,r12,\"alpha\"${_line_suffix}" "strict string consumer redirected")
    _require("${_line_prefix}dcopy[ \t]+r15,r14${_line_suffix}" "decimal copy retained pending allocation/signal proof")
    _forbid("${_line_prefix}copy[ \t]+r16,r16${_line_suffix}" "identity full copy")
    _require("${_line_prefix}copy[ \t]+r18,r17${_line_suffix}" "nonidentity full copy retained")
    _count("${_line_prefix}null[ \t]+r20${_line_suffix}" 1 "redundant NULL removed across join")
    _count("${_line_prefix}null[ \t]+r21${_line_suffix}" 2 "NULLs separated by an observed write")
    _count("${_line_prefix}itof[ \t]+r22${_line_suffix}" 1 "redundant context-free conversion removed")
    _count("${_line_prefix}itof[ \t]+r23${_line_suffix}" 2 "conversions separated by an observed integer write")
    _require("${_line_prefix}load[ \t]+r24,-0\\.0${_line_suffix}" "negative floating zero load")
    _require("${_line_prefix}load[ \t]+r24,0\\.0${_line_suffix}" "positive floating zero load")
    _require("${_line_prefix}icopy[ \t]+r26,r25${_line_suffix}" "mixed-entry loop copy retained")
    _require("${_line_prefix}ieq[ \t]+r27,r26,77${_line_suffix}" "mixed-entry loop consumer not partially rewritten")
    _forbid("${_line_prefix}icopy[ \t]+r29,r28${_line_suffix}" "dominating loop copy")
    _require("${_line_prefix}ieq[ \t]+r30,r28,79${_line_suffix}" "dominated loop consumer redirected")
    _require("${_line_prefix}load[ \t]+r31,99${_line_suffix}" "TRACE-observed otherwise-dead load")
    _require("trace-keeps-load" "TRACE record for retained load")
    _forbid("${_line_prefix}load[ \t]+r32,88${_line_suffix}" "unreachable traced load")
    _forbid("unreachable-trace" "unreachable TRACE record")
    _forbid("unreachable-source-step" "unreachable source-step record")
    _forbid("${_line_prefix}load[ \t]+r33,87${_line_suffix}" "unreachable source-stepped load")
    _require("${_line_prefix}endlife[ \t]+r36${_line_suffix}" "ENDLIFE preserved")
    _forbid("${_line_prefix}icopy[ \t]+r38,r37${_line_suffix}" "copy in region after ENDLIFE")
    _require("${_line_prefix}ieq[ \t]+r9,r37,83${_line_suffix}" "consumer after ENDLIFE redirected")
    _forbid("${_line_prefix}icopy[ \t]+r40,r39${_line_suffix}" "copy before a later exceptional ENDLIFE")
    _require("${_line_prefix}load[ \t]+r39,89${_line_suffix}" "source retained before an unrelated exceptional ENDLIFE")
    _require("${_line_prefix}ieq[ \t]+r42,r39,89${_line_suffix}" "typed-copy consumer redirected across an unrelated exceptional ENDLIFE")
    _forbid("${_line_prefix}icopy[ \t]+r44,r43${_line_suffix}" "copy whose final value is observed by following metadata")
    _require("${_line_prefix}load[ \t]+r44,97${_line_suffix}" "metadata-observed value produced directly in its final register")
    _forbid("${_line_prefix}icopy[ \t]+r47,r46${_line_suffix}" "copy with unrelated metadata")
    _require("${_line_prefix}ieq[ \t]+r45,r46,101${_line_suffix}" "consumer across unrelated metadata redirected")
    _require("${_line_prefix}load[ \t]+r49,107${_line_suffix}" "registered SIGNAL-handler body retained as reachable")
    _require("${_line_prefix}load[ \t]+r50,109${_line_suffix}" "value observable by an asynchronous SIGNAL handler retained")
    _forbid("${_line_prefix}copy[ \t]+r52,r52${_line_suffix}" "no-op identity copy before TRACE across a label")
    _require("trace-after-label" "TRACE record after a label")
    _forbid("${_line_prefix}icopy[ \t]+r54,r53${_line_suffix}" "typed copy across an unobserved throwing instruction")
    _require("${_line_prefix}ieq[ \t]+r56,r53,111${_line_suffix}" "consumer across an unobserved throw redirected")
    _require("${_line_prefix}icopy[ \t]+r58,r57${_line_suffix}" "typed copy observed by a local exception handler retained")
    _require("${_line_prefix}ieq[ \t]+r60,r58,113${_line_suffix}" "exception handler still reads the copied register")
    _require("${_line_prefix}ieq[ \t]+r61,r62,1${_line_suffix}" "dead numeric result retained because its destination may release hidden lifetime state")
    _forbid("${_line_prefix}icopy[ \t]+r62,r61${_line_suffix}" "copy admitted by complete local jump-table flow")
    _require("${_line_prefix}ieq[ \t]+r63,r61,127${_line_suffix}" "jump-table-region consumer redirected to the source register")
elseif(CASE STREQUAL "whole_procedure_panel_noopt")
    foreach(_copy IN ITEMS "fcopy r11,r10" "scopy r13,r12" "dcopy r15,r14" "copy r16,r16" "copy r18,r17" "icopy r26,r25" "icopy r29,r28" "icopy r38,r37" "icopy r40,r39" "icopy r44,r43" "icopy r47,r46" "icopy r62,r61")
        string(REPLACE " " "[ \t]+" _copy_regex "${_copy}")
        _require("${_line_prefix}${_copy_regex}${_line_suffix}" "${_copy} with -n")
    endforeach()
    _count("${_line_prefix}null[ \t]+r20${_line_suffix}" 2 "both join NULLs with -n")
    _count("${_line_prefix}null[ \t]+r21${_line_suffix}" 2 "both separated NULLs with -n")
    _count("${_line_prefix}itof[ \t]+r22${_line_suffix}" 2 "both join conversions with -n")
    _count("${_line_prefix}itof[ \t]+r23${_line_suffix}" 2 "both separated conversions with -n")
    _require("${_line_prefix}load[ \t]+r32,88${_line_suffix}" "unreachable load with -n")
    _require("unreachable-trace" "unreachable TRACE with -n")
    _require("unreachable-source-step" "unreachable source step with -n")
    _require("${_line_prefix}load[ \t]+r49,107${_line_suffix}" "registered SIGNAL-handler body with -n")
    _require("${_line_prefix}load[ \t]+r50,109${_line_suffix}" "asynchronous SIGNAL-observed value with -n")
    _require("${_line_prefix}copy[ \t]+r52,r52${_line_suffix}" "TRACE-observed identity copy across a label with -n")
    _require("${_line_prefix}icopy[ \t]+r54,r53${_line_suffix}" "copy across throwing instruction with -n")
    _require("${_line_prefix}icopy[ \t]+r58,r57${_line_suffix}" "exception-handler copy with -n")
    _require("${_line_prefix}ieq[ \t]+r61,r62,1${_line_suffix}" "dead numeric result with -n")
elseif(CASE STREQUAL "nr18_flow_harvest")
    foreach(_copy IN ITEMS "icopy r1,r0" "fcopy r3,r2" "icopy r24,r23" "icopy r19,r18" "icopy r21,r20" "icopy r35,r34" "icopy r37,r36" "icopy r39,r38")
        string(REPLACE " " "[ \t]+" _copy_regex "${_copy}")
        _forbid("${_line_prefix}${_copy_regex}${_line_suffix}" "${_copy} removed by destination forwarding")
    endforeach()
    _require("${_line_prefix}load[ \t]+r1,7${_line_suffix}" "integer producer retargeted")
    _require("${_line_prefix}load[ \t]+r3,2\\.5${_line_suffix}" "float producer retargeted")
    _require("${_line_prefix}ieq[ \t]+r24,r22,31${_line_suffix}" "comparison producer retargeted")
    foreach(_copy IN ITEMS "icopy r5,r4" "icopy r9,r7" "scopy r11,r10" "icopy r13,r12" "icopy r15,r14" "fcopy r26,r25" "icopy r28,r27" "icopy r30,r29" "icopy r32,r31" "icopy r45,r44" "icopy r47,r48" "icopy r41,r40")
        string(REPLACE " " "[ \t]+" _copy_regex "${_copy}")
        _require("${_line_prefix}${_copy_regex}${_line_suffix}" "${_copy} negative retained")
    endforeach()
    _require("source-step-after-copy" "address-observing source step retained")
    _require("nr18\\.producer" "producer metadata retained")
    _require_debug("PERF3 producer-forward-proof procedure=temporary_cleanup_required[^\n]*reason=cleanup-required" "discarded temporary cleanup remains observable")
    _require_debug("PERF3 producer-forward-proof procedure=destination_cleanup_required[^\n]*reason=cleanup-required" "final destination cleanup differs from typed copy")
    _require("${_line_prefix}jumpr[ \t]+r42," "jump table without a local miss edge retained fail-closed")
elseif(CASE STREQUAL "nr18_flow_harvest_noopt")
    foreach(_copy IN ITEMS "icopy r1,r0" "fcopy r3,r2" "icopy r24,r23" "icopy r19,r18" "icopy r21,r20" "icopy r35,r34" "icopy r37,r36" "icopy r39,r38" "icopy r45,r44" "icopy r47,r48")
        string(REPLACE " " "[ \t]+" _copy_regex "${_copy}")
        _require("${_line_prefix}${_copy_regex}${_line_suffix}" "${_copy} with -n")
    endforeach()
elseif(CASE STREQUAL "storage_identity_flow")
    # M07 is now a bounded sparse-SSA oracle. The detailed join, loop,
    # signal-edge and storage-node contracts live in test_rxas_flow_graph;
    # this assembled fixture proves that every historical scenario still
    # reaches that service without rebuilding the retired dense matrix.
    foreach(_procedure IN ITEMS identity_straight identity_join_agrees identity_join_disagrees identity_loop_stable identity_attribute_loop identity_tainted_copy_base identity_alias_self_copy identity_cri13_shape identity_signal_handler_unknown identity_reference_unknown identity_fused_partial_signal identity_lifetime_forgets_dynamic identity_swap_roundtrip identity_swap_observed)
        _require_debug("PERF3 sparse-storage-oracle procedure=${_procedure} status=complete[^\n]*retained-bytes=[1-9][0-9]*" "sparse storage oracle for ${_procedure}")
    endforeach()
    _require_debug("PERF3 sparse-storage-oracle procedure=identity_straight[^\n]*queries=4 exact=4 unknown=0" "exact straight-line mapping queries")
    _require_debug("PERF3 sparse-storage-oracle procedure=identity_join_agrees[^\n]*queries=3 exact=3 unknown=0" "agreeing join remains exact")
    _require_debug("PERF3 sparse-storage-oracle procedure=identity_signal_handler_unknown[^\n]*queries=2 exact=1 unknown=1" "same-frame handler mapping fails closed")
    _require_debug("PERF3 flow-graph procedure=identity_signal_handler_unknown[^\n]*skip=1[^\n]*handler=3[^\n]*unwind=2" "signal continuations remain explicit CFG edges")
    _require_debug("PERF3 sparse-storage-oracle procedure=identity_reference_unknown[^\n]*site=1" "reference link owns a sparse storage site")
    _require_debug("PERF3 sparse-storage-oracle procedure=identity_fused_partial_signal[^\n]*site=1" "fused partial signal owns a sparse storage site")
    _require_debug("PERF3 sparse-storage-oracle procedure=identity_lifetime_forgets_dynamic[^\n]*exact=2 unknown=1[^\n]*site=1" "lifetime mutation forgets dynamic identity")
    _require_debug("PERF3 self-copy-proof-candidate opcode=COPY_REG_REG record=1 instruction=1[^\n]*proved=1 reason=proved storage=[1-9][0-9]*" "new proof follows distinct register numbers to the same storage")
    _require_debug("NR27 flow procedure=identity_alias_self_copy[^\n]*instructions=4->3[^\n]*full-copy=1[^\n]*self-copy-proof=1/1" "proved aliased full copy is deleted")
elseif(CASE STREQUAL "swap_round_trip_flow")
    _count("${_line_prefix}swap[ \t]+" 21 "retained SWAP instructions")
    _forbid("${_line_prefix}swapn[ \t]+" "encoded self-cancelling SWAPN")
    foreach(_procedure IN ITEMS adjacent_encoded_round_trip reversed_round_trip beyond_legacy_window unrelated_register_metadata unrelated_trace_register unrelated_external_effect inherited_signal_discards_mapping same_storage_is_identity disjoint_permutation_is_irrelevant)
        _require_debug("NR27 accept procedure=${_procedure}[^\n]*reason=storage-permutation-round-trip" "proved ${_procedure} storage round trip")
    endforeach()
    foreach(_procedure IN ITEMS explicit_read_observes explicit_write_observes register_metadata_observes trace_register_observes)
        _require_debug("PERF3 storage-permutation-proof procedure=${_procedure}[^\n]*proved=0 reason=permutation-observed" "observed ${_procedure} rejection")
    endforeach()
    _require_debug("PERF3 storage-permutation-proof procedure=mapping_not_restored[^\n]*proved=0 reason=permutation-not-restored" "mapping restoration rejection")
    _require_debug("PERF3 storage-permutation-proof procedure=local_signal_handler_observes[^\n]*proved=0 reason=permutation-signal-exit" "local signal-handler rejection")
    _require_debug("PERF3 storage-permutation-proof procedure=asynchronous_handler_observes[^\n]*proved=0 reason=permutation-observed" "asynchronous handler observation rejection")
elseif(CASE STREQUAL "swap_round_trip_flow_noopt")
    _count("${_line_prefix}swap[ \t]+" 39 "source SWAP instructions with -n")
    _forbid("${_line_prefix}swapn[ \t]+" "SWAPN with -n")
elseif(CASE STREQUAL "redundant_itos_flow")
    _count("${_line_prefix}itos[ \t]+r0${_line_suffix}" 1 "TRACE-batched redundant ITOS")
    foreach(_register IN ITEMS 1 2 3 4 11)
        _count("${_line_prefix}itos[ \t]+r${_register}${_line_suffix}" 2 "fail-closed r${_register} ITOS pair")
    endforeach()
    _count("${_line_prefix}itos[ \t]+r5${_line_suffix}" 1 "join-dominating redundant ITOS")
    _count("${_line_prefix}itos[ \t]+r(6|7)${_line_suffix}" 1 "linked-storage redundant ITOS")
    _count("${_line_prefix}itos[ \t]+r(8|9)${_line_suffix}" 1 "swapped-storage redundant ITOS")
    _count("${_line_prefix}itos[ \t]+r10${_line_suffix}" 1 "unescaped local ITOS across unrelated indirect write")
    _count("${_line_prefix}itos[ \t]+r12${_line_suffix}" 1 "component-SSA ITOS across an unaliased call")
    _count("${_line_prefix}\.traceevent[^\n]*\"[VA]\"[^\n]*\"S\"[^\n]*\"r\"[ \t]+0" 2 "ordered string TRACE events retained after ITOS elimination")
elseif(CASE STREQUAL "redundant_itos_flow_noopt")
    _count("${_line_prefix}itos[ \t]+" 22 "all ITOS instructions with -n")
elseif(CASE STREQUAL "redundant_xtoy_flow")
    _count("${_line_prefix}itof[ \t]+r0${_line_suffix}" 1 "old ITOF floor recovered by generic proof")
    _count("${_line_prefix}ftos[ \t]+r1${_line_suffix}" 1 "repeated FTOS removed")
    _count("${_line_prefix}ftos[ \t]+r2${_line_suffix}" 2 "FTOS retained across numeric-context write")
    _count("${_line_prefix}dtos[ \t]+r3${_line_suffix}" 1 "repeated DTOS removed")
    _count("${_line_prefix}dtos[ \t]+r4${_line_suffix}" 2 "DTOS retained across numeric-context write")
    _count("${_line_prefix}itod[ \t]+r5${_line_suffix}" 1 "repeated ITOD removed")
    _count("${_line_prefix}itod[ \t]+r6${_line_suffix}" 2 "ITOD retained across source write")
    _count("${_line_prefix}itod[ \t]+r7${_line_suffix}" 2 "ITOD retained across numeric-context write")
    _count("${_line_prefix}itod[ \t]+r8${_line_suffix}" 1 "total ITOD repeated under an installed handler")
    _count("${_line_prefix}itod[ \t]+r9${_line_suffix}" 1 "TRACE-batched repeated ITOD removed")
    _count("${_line_prefix}itod[ \t]+r(10|11)${_line_suffix}" 1 "linked-storage repeated ITOD removed")
    foreach(_total IN ITEMS "btod r12" "btof r13" "btos r14" "ftob r15" "stob r16")
        string(REPLACE " " "[ \t]+" _total_regex "${_total}")
        _count("${_line_prefix}${_total_regex}${_line_suffix}" 1 "total distinct-component ${_total} repetition removed")
    endforeach()
    foreach(_signalling IN ITEMS "ftoi r17" "stof r18" "stod r19" "dtoi r20" "dtob r21" "ftod r22" "dtof r23")
        string(REPLACE " " "[ \t]+" _signalling_regex "${_signalling}")
        _count("${_line_prefix}${_signalling_regex}${_line_suffix}" 2 "signalling ${_signalling} repetition retained without success-edge proof")
    endforeach()
    _count("${_line_prefix}btoi[ \t]+r24${_line_suffix}" 2 "same-component BTOI awaits idempotence proof")
    _count("${_line_prefix}itob[ \t]+r25${_line_suffix}" 2 "same-component ITOB awaits idempotence proof")
    _count("${_line_prefix}\.traceevent[^\n]*\"[VA]\"[^\n]*\"D\"[^\n]*\"r\"[ \t]+9" 2 "ordered decimal TRACE events retained")
    _require_debug("PERF3 derivation-proof-candidate opcode=ITOD_REG" "ITOD selected from canonical derivation metadata")
elseif(CASE STREQUAL "redundant_xtoy_flow_noopt")
    _count("${_line_prefix}itof[ \t]+r0${_line_suffix}" 2 "both ITOF instructions with -n")
    _count("${_line_prefix}ftos[ \t]+" 4 "all FTOS instructions with -n")
    _count("${_line_prefix}dtos[ \t]+" 4 "all DTOS instructions with -n")
    _count("${_line_prefix}itod[ \t]+" 12 "all ITOD instructions with -n")
    foreach(_conversion IN ITEMS btod btof btos ftob stob ftoi stof stod dtoi dtob ftod dtof btoi itob)
        _count("${_line_prefix}${_conversion}[ \t]+" 2 "both ${_conversion} instructions with -n")
    endforeach()
elseif(CASE STREQUAL "copied_xtoy_component_placement")
    _count("${_line_prefix}dcopy[ \t]+r1,r0${_line_suffix}" 12 "retained unsafe decimal copies")
    _count("${_line_prefix}dtos[ \t]+r0${_line_suffix}" 1 "placed decimal-to-string derivation")
    _count("${_line_prefix}dtos[ \t]+r1${_line_suffix}" 12 "retained unsafe decimal-to-string derivations")
    _forbid("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" "placed integer copy")
    _require("${_line_prefix}itos[ \t]+r1${_line_suffix}" "producer-forwarded integer-to-string derivation")
    _forbid("${_line_prefix}fcopy[ \t]+r1,r0${_line_suffix}" "placed float copy")
    _require("${_line_prefix}ftos[ \t]+r1${_line_suffix}" "producer-forwarded float-to-string derivation")
    _require("${_line_prefix}strlen[ \t]+r2,r0${_line_suffix}" "redirected placed decimal string consumer")
    _forbid("placed-string-delete" "TRACE event for the eliminated temporary result")
    _require("temporary-input" "TRACE observation of the copied input component")
    _require("\.meta[ \t]+\"fixture\.x1\"=\"result\"[ \t]+\"\.string\"[ \t]+r1" "register metadata observation")
    _require_debug("reason=component-placement-ssa" "accepted X01 component placement")
    foreach(_reason IN ITEMS source-result-observed temporary-input-observed source-changed use-not-redirectable)
        _require_debug("component-placement-proof[^\n]*reason=${_reason}" "X01 rejection ${_reason}")
    endforeach()
    _require_debug("component-placement-proof procedure=branch_phi_observed[^\n]*reason=use-not-redirectable" "branch/phi rejection")
    _require_debug("component-placement-proof procedure=linked_result_observed[^\n]*reason=temporary-input-observed" "linked-storage rejection")
    _require_debug("component-placement-proof procedure=call_result_observed[^\n]*reason=temporary-input-observed" "call-window rejection")
    _require_debug("component-placement-proof procedure=signal_handler_observes_source_result[^\n]*reason=use-not-redirectable" "signal-handler rejection")
    _require_debug("component-placement-proof procedure=metadata_observes_result[^\n]*reason=temporary-input-observed[^\n]*rejected-kind=5" "metadata rejection")
    _require_debug("component-placement-proof procedure=trace_observes_temporary_input[^\n]*reason=temporary-input-observed[^\n]*rejected-kind=6" "input TRACE rejection")
    _require_debug("component-placement-proof procedure=referenced_source_observed[^\n]*reason=reference-observed" "reference-observed rejection")
    _require_debug("flow procedure=context_boundary_not_crossed[^\n]*component-placement-proof=0/0" "context boundary not crossed")
elseif(CASE STREQUAL "copied_xtoy_component_placement_noopt")
    _count("${_line_prefix}dcopy[ \t]+r1,r0${_line_suffix}" 13 "unoptimised decimal copies")
    _count("${_line_prefix}dtos[ \t]+r1${_line_suffix}" 13 "unoptimised decimal-to-string derivations")
    _require("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" "unoptimised integer copy")
    _require("${_line_prefix}itos[ \t]+r1${_line_suffix}" "unoptimised integer-to-string derivation")
    _require("${_line_prefix}fcopy[ \t]+r1,r0${_line_suffix}" "unoptimised float copy")
    _require("${_line_prefix}ftos[ \t]+r1${_line_suffix}" "unoptimised float-to-string derivation")
    _require("placed-string-delete" "TRACE event retained with -n")
elseif(CASE STREQUAL "redundant_constant_flow")
    _count("${_line_prefix}load[ \t]+r0,3${_line_suffix}" 1 "old integer-load floor recovered")
    _count("${_line_prefix}load[ \t]+r1,7${_line_suffix}" 2 "equal constant phi makes the join write redundant")
    _count("${_line_prefix}load[ \t]+r2,7${_line_suffix}" 2 "different constant phi retains the join write")
    _count("${_line_prefix}load[ \t]+r2,8${_line_suffix}" 1 "different phi input retained")
    _count("${_line_prefix}load[ \t]+r3,1.5${_line_suffix}" 1 "bitwise-identical float write removed")
    _count("${_line_prefix}load[ \t]+r4,-0\\.0${_line_suffix}" 1 "negative zero retained")
    _count("${_line_prefix}load[ \t]+r4,0\\.0${_line_suffix}" 1 "positive zero retained as bitwise-distinct")
    _count("${_line_prefix}load[ \t]+r(5|6),11${_line_suffix}" 1 "linked-storage constant write removed")
    _count("${_line_prefix}load[ \t]+r7,12${_line_suffix}" 1 "TRACE-observed equivalent write removed")
    _count("${_line_prefix}load[ \t]+r8,0${_line_suffix}" 2 "reference cleanup write retained")
    _count("${_line_prefix}load[ \t]+r9,0${_line_suffix}" 2 "native cleanup write retained")
    _count("${_line_prefix}\.traceevent[^\n]*\"[VA]\"[^\n]*\"I\"[^\n]*\"r\"[ \t]+7" 2 "ordered integer TRACE events retained")
    _require_debug("PERF3 constant-proof-candidate opcode=LOAD_REG_INT[^\n]*proved=0 reason=cleanup-required" "hidden cleanup rejection")
elseif(CASE STREQUAL "redundant_constant_flow_noopt")
    _count("${_line_prefix}load[ \t]+r0,3${_line_suffix}" 2 "both old-floor loads with -n")
    _count("${_line_prefix}load[ \t]+r1,7${_line_suffix}" 3 "all equal-phi loads with -n")
    _count("${_line_prefix}load[ \t]+r2,7${_line_suffix}" 2 "both r2=7 loads with -n")
    _count("${_line_prefix}load[ \t]+r2,8${_line_suffix}" 1 "r2=8 load with -n")
    _count("${_line_prefix}load[ \t]+r3,1.5${_line_suffix}" 2 "both float loads with -n")
    _count("${_line_prefix}load[ \t]+r4,-0\\.0${_line_suffix}" 1 "negative zero with -n")
    _count("${_line_prefix}load[ \t]+r4,0\\.0${_line_suffix}" 1 "positive zero with -n")
    _count("${_line_prefix}load[ \t]+r(5|6),11${_line_suffix}" 2 "both linked-storage loads with -n")
    _count("${_line_prefix}load[ \t]+r7,12${_line_suffix}" 2 "both TRACE-observed loads with -n")
    _count("${_line_prefix}load[ \t]+r8,0${_line_suffix}" 2 "both cleanup loads with -n")
    _count("${_line_prefix}load[ \t]+r9,0${_line_suffix}" 2 "both native-cleanup loads with -n")
elseif(CASE STREQUAL "redundant_absent_flow")
    _count("${_line_prefix}null[ \t]+r0${_line_suffix}" 1 "old repeated-NULL floor recovered")
    _count("${_line_prefix}null[ \t]+r1${_line_suffix}" 2 "equal absence phi makes the join NULL redundant")
    _count("${_line_prefix}null[ \t]+r2${_line_suffix}" 2 "different absence phi retains the join NULL")
    _count("${_line_prefix}null[ \t]+r3${_line_suffix}" 2 "intervening scalar write retains NULL")
    _count("${_line_prefix}null[ \t]+r4${_line_suffix}" 1 "TRACE-observed equivalent NULL removed")
    _count("${_line_prefix}null[ \t]+r(5|6)${_line_suffix}" 1 "linked-storage NULL removed")
    _count("${_line_prefix}null[ \t]+r7${_line_suffix}" 2 "reference cleanup NULL retained")
    _count("${_line_prefix}null[ \t]+r9${_line_suffix}" 2 "native cleanup NULL retained")
    _count("${_line_prefix}\.traceevent[^\n]*\"[VA]\"[^\n]*\"I\"[^\n]*\"r\"[ \t]+4" 2 "ordered NULL-adjacent TRACE events retained")
    _require_debug("PERF3 absent-proof-candidate opcode=NULL_REG[^\n]*proved=0 reason=component-present" "present-component rejection")
elseif(CASE STREQUAL "redundant_absent_flow_noopt")
    foreach(_register IN ITEMS 0 2 3 4 7 9)
        _count("${_line_prefix}null[ \t]+r${_register}${_line_suffix}" 2 "both r${_register} NULL instructions with -n")
    endforeach()
    _count("${_line_prefix}null[ \t]+r1${_line_suffix}" 3 "all equal-phi NULL instructions with -n")
    _count("${_line_prefix}null[ \t]+r(5|6)${_line_suffix}" 2 "both linked-storage NULL instructions with -n")
elseif(CASE STREQUAL "redundant_self_copy_flow")
    foreach(_copy IN ITEMS "copy r0,r0" "icopy r1,r1" "fcopy r2,r2" "scopy r3,r3" "dcopy r4,r4" "acopy r5,r5" "bcopy r6,r6" "copy r8,r7" "bcopy r8,r7" "copy r14,r14" "dcopy r16,r15")
        string(REPLACE " " "[ \t]+" _copy_regex "${_copy}")
        _forbid("${_line_prefix}${_copy_regex}${_line_suffix}" "proved same-storage ${_copy}")
    endforeach()
    _require("${_line_prefix}dcopy[ \t]+r18,r17${_line_suffix}" "divergent-phi typed copy retained")
    _require("${_line_prefix}copy[ \t]+r20,r21${_line_suffix}" "different-storage full copy retained")
    _require("self-copy-trace-anchor" "TRACE event retained after no-op copy deletion")
    _require("divergent-copy-retained" "TRACE event observing the negative copy retained")
    _require_debug("PERF3 self-copy-proof-candidate opcode=BCOPY_REG_REG[^\n]*proved=1 reason=proved" "conditional BCOPY same-storage proof")
    _require_debug("PERF3 self-copy-proof-candidate opcode=DCOPY_REG_REG[^\n]*proved=0 reason=storage-not-identical" "divergent-storage rejection")
elseif(CASE STREQUAL "redundant_self_copy_flow_noopt")
    foreach(_copy IN ITEMS "copy r0,r0" "icopy r1,r1" "fcopy r2,r2" "scopy r3,r3" "dcopy r4,r4" "acopy r5,r5" "bcopy r6,r6" "copy r8,r7" "bcopy r8,r7" "copy r14,r14" "dcopy r16,r15" "dcopy r18,r17" "copy r20,r21")
        string(REPLACE " " "[ \t]+" _copy_regex "${_copy}")
        _require("${_line_prefix}${_copy_regex}${_line_suffix}" "${_copy} with -n")
    endforeach()
elseif(CASE STREQUAL "nr09_class1_boundaries")
    foreach(_fused IN ITEMS swapn loadsettpswap swapsettpswap settpswapsettpswap nulln)
        _forbid("${_line_prefix}${_fused}[ \t]+" "${_fused} across a boundary or mismatched dependency")
    endforeach()
    _count("${_line_prefix}settpswap[ \t]+" 3 "valid two-instruction subsets retained in mismatch cases")
    _count("${_line_prefix}loadsettp2[ \t]+" 1 "valid load/settp subset before a boundary")
    _count("${_line_prefix}swapsettp[ \t]+" 1 "valid swap/settp subset before a boundary")
    _require("${_line_prefix}icopy[ \t]+r1,r2${_line_suffix}" "mismatched load/copy source preserved")
    _require("${_line_prefix}settp[ \t]+r2,512${_line_suffix}" "mismatched shared status preserved")
elseif(CASE MATCHES "^barrier_")
    _count("${_line_prefix}swap[ \t]+r1,r2${_line_suffix}" 2 "r1/r2 swaps preserved by optimiser barrier")
else()
    _optimizer_fail("Unknown optimiser check case")
endif()
