cmake_minimum_required(VERSION 3.24)

foreach(_required_var IN ITEMS RXAS RXDAS SOURCE WORKING_DIRECTORY CASE)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "Missing required variable ${_required_var}")
    endif()
endforeach()

file(MAKE_DIRECTORY "${WORKING_DIRECTORY}/${CASE}")
get_filename_component(_stem "${SOURCE}" NAME_WE)
set(_output_base "${WORKING_DIRECTORY}/${CASE}/${_stem}")
set(_rxbin "${_output_base}.rxbin")
set(_disassembly "${WORKING_DIRECTORY}/${CASE}/${_stem}.rxas")

execute_process(
        COMMAND "${RXAS}" ${RXAS_FLAGS} -o "${_output_base}" "${SOURCE}"
        WORKING_DIRECTORY "${WORKING_DIRECTORY}/${CASE}"
        RESULT_VARIABLE _rxas_rc
        OUTPUT_VARIABLE _rxas_out
        ERROR_VARIABLE _rxas_err
)

if(NOT _rxas_rc EQUAL 0)
    message(FATAL_ERROR
            "rxas failed for ${SOURCE}\n"
            "case: ${CASE}\n"
            "stdout:\n${_rxas_out}\n"
            "stderr:\n${_rxas_err}")
endif()

execute_process(
        COMMAND "${RXDAS}" -o "${_disassembly}" "${_rxbin}"
        WORKING_DIRECTORY "${WORKING_DIRECTORY}/${CASE}"
        RESULT_VARIABLE _rxdas_rc
        OUTPUT_VARIABLE _rxdas_out
        ERROR_VARIABLE _rxdas_err
)

if(NOT _rxdas_rc EQUAL 0)
    message(FATAL_ERROR
            "rxdas failed for ${_rxbin}\n"
            "case: ${CASE}\n"
            "stdout:\n${_rxdas_out}\n"
            "stderr:\n${_rxdas_err}")
endif()

file(READ "${_disassembly}" _disassembly_text)
string(REPLACE "\r\n" "\n" _disassembly_text "${_disassembly_text}")
string(REPLACE "\r" "\n" _disassembly_text "${_disassembly_text}")

function(_optimizer_fail MESSAGE)
    message(FATAL_ERROR
            "${MESSAGE}\n"
            "case: ${CASE}\n"
            "source: ${SOURCE}\n"
            "disassembly: ${_disassembly}\n"
            "--- disassembly ---\n${_disassembly_text}")
endfunction()

function(_require REGEX DESCRIPTION)
    if(NOT _disassembly_text MATCHES "${REGEX}")
        _optimizer_fail("Expected ${DESCRIPTION}: ${REGEX}")
    endif()
endfunction()

function(_forbid REGEX DESCRIPTION)
    if(_disassembly_text MATCHES "${REGEX}")
        _optimizer_fail("Did not expect ${DESCRIPTION}: ${REGEX}")
    endif()
endfunction()

function(_count REGEX EXPECTED DESCRIPTION)
    string(REGEX MATCHALL "${REGEX}" _matches "${_disassembly_text}")
    list(LENGTH _matches _actual)
    if(NOT _actual EQUAL EXPECTED)
        _optimizer_fail("Expected ${EXPECTED} ${DESCRIPTION}, found ${_actual}: ${REGEX}")
    endif()
endfunction()

set(_line_prefix "(^|\n)([ \t]*[A-Za-z_][A-Za-z0-9_]*:[ \t]*)?[ \t]*")
set(_line_suffix "[ \t]*(\\*|\n|$)")

if(CASE STREQUAL "fixed_registers_opt")
    foreach(_mnemonic IN ITEMS inc0 inc1 inc2 dec0 dec1 dec2)
        _require("${_line_prefix}${_mnemonic}${_line_suffix}" "${_mnemonic} shortcut")
    endforeach()
    foreach(_instruction IN ITEMS "inc r0" "inc r1" "inc r2" "dec r0" "dec r1" "dec r2")
        string(REPLACE " " "[ \t]+" _instruction_regex "${_instruction}")
        _forbid("${_line_prefix}${_instruction_regex}${_line_suffix}" "unoptimised ${_instruction}")
    endforeach()
    _require("${_line_prefix}inc[ \t]+r3${_line_suffix}" "non-shortcut inc r3")
    _require("${_line_prefix}dec[ \t]+r3${_line_suffix}" "non-shortcut dec r3")
elseif(CASE STREQUAL "fixed_registers_noopt")
    foreach(_instruction IN ITEMS "inc r0" "inc r1" "inc r2" "inc r3" "dec r0" "dec r1" "dec r2" "dec r3")
        string(REPLACE " " "[ \t]+" _instruction_regex "${_instruction}")
        _require("${_line_prefix}${_instruction_regex}${_line_suffix}" "unoptimised ${_instruction}")
    endforeach()
    foreach(_mnemonic IN ITEMS inc0 inc1 inc2 dec0 dec1 dec2)
        _forbid("${_line_prefix}${_mnemonic}${_line_suffix}" "shortcut ${_mnemonic} with -n")
    endforeach()
elseif(CASE STREQUAL "implicit_inc0_relevant")
    _require("${_line_prefix}inc0${_line_suffix}" "inc0")
    _count("${_line_prefix}swap[ \t]+r0,r1${_line_suffix}" 2 "r0/r1 swaps preserved across inc0")
elseif(CASE STREQUAL "implicit_inc0_unrelated")
    _require("${_line_prefix}inc0${_line_suffix}" "inc0")
    _count("${_line_prefix}swap[ \t]+r3,r4${_line_suffix}" 0 "unrelated r3/r4 swaps")
elseif(CASE STREQUAL "loadint_relevant")
    _require("${_line_prefix}load[ \t]+0,1${_line_suffix}" "implicit load 0,1")
    _count("${_line_prefix}swap[ \t]+r0,r1${_line_suffix}" 2 "r0/r1 swaps preserved across load 0,1")
elseif(CASE STREQUAL "loadint_unrelated")
    _require("${_line_prefix}load[ \t]+0,1${_line_suffix}" "implicit load 0,1")
    _count("${_line_prefix}swap[ \t]+r3,r4${_line_suffix}" 0 "unrelated r3/r4 swaps")
elseif(CASE STREQUAL "linkarg_relevant")
    _require("${_line_prefix}linkarg[ \t]+r0,0${_line_suffix}" "implicit argument register linkarg")
    _count("${_line_prefix}swap[ \t]+a0[^\n]*,a1[^\n]*(\n|$)" 2 "a0/a1 swaps preserved across linkarg r0,0")
elseif(CASE STREQUAL "linkarg_unrelated")
    _require("${_line_prefix}linkarg[ \t]+r0,0${_line_suffix}" "implicit argument register linkarg")
    _count("${_line_prefix}swap[ \t]+r3,r4${_line_suffix}" 0 "unrelated r3/r4 swaps")
elseif(CASE STREQUAL "copy_acopy_opt")
    _require("${_line_prefix}copy[ \t]+r1,r0${_line_suffix}" "full copy")
    _forbid("${_line_prefix}acopy[ \t]+r1,r0${_line_suffix}" "redundant acopy after full copy")
elseif(CASE STREQUAL "copy_acopy_noopt")
    _require("${_line_prefix}copy[ \t]+r1,r0${_line_suffix}" "full copy")
    _require("${_line_prefix}acopy[ \t]+r1,r0${_line_suffix}" "acopy preserved with -n")
elseif(CASE STREQUAL "compare_branch")
    _count("${_line_prefix}beq[ \t]+[^,\n]+,r1,r2${_line_suffix}" 1 "fused ieq/brt register branch")
    _count("${_line_prefix}bne[ \t]+[^,\n]+,r1,r2${_line_suffix}" 2 "fused not-equal register branches")
    _require("${_line_prefix}beq[ \t]+[^,\n]+,r1,5${_line_suffix}" "inverted ine/brf immediate branch")
    _require("${_line_prefix}blt[ \t]+[^,\n]+,r1,r2${_line_suffix}" "fused ilt/brt register branch")
    _require("${_line_prefix}bge[ \t]+[^,\n]+,r1,3${_line_suffix}" "inverted ilt/brf immediate branch")
    _require("${_line_prefix}ble[ \t]+[^,\n]+,r1,r2${_line_suffix}" "fused ilte/brt register branch")
    _require("${_line_prefix}bgt[ \t]+[^,\n]+,r1,4${_line_suffix}" "inverted ilte/brf immediate branch")
    _require("${_line_prefix}bgt[ \t]+[^,\n]+,r1,r2${_line_suffix}" "fused igt/brt register branch")
    _require("${_line_prefix}ble[ \t]+[^,\n]+,r1,6${_line_suffix}" "inverted igt/brf immediate branch")
    _require("${_line_prefix}bge[ \t]+[^,\n]+,r1,r2${_line_suffix}" "fused igte/brt register branch")
    _require("${_line_prefix}blt[ \t]+[^,\n]+,r1,7${_line_suffix}" "inverted igte/brf immediate branch")
    _require("${_line_prefix}blt[ \t]+[^,\n]+,r1,8${_line_suffix}" "rewritten igt/brt int-register branch")
    _require("${_line_prefix}bgt[ \t]+[^,\n]+,r1,9${_line_suffix}" "rewritten igte/brf int-register branch")
    _require("${_line_prefix}bgt[ \t]+[^,\n]+,r1,10${_line_suffix}" "rewritten ilt/brt int-register branch")
    _require("${_line_prefix}blt[ \t]+[^,\n]+,r1,11${_line_suffix}" "rewritten ilte/brf int-register branch")
    _count("${_line_prefix}ieq[ \t]+r0,r1,32${_line_suffix}" 1 "compare whose boolean result remains live")
    _count("${_line_prefix}ieq[ \t]+r5,r1,3[34]${_line_suffix}" 2 "compares used by deprecated trim and call argument range")
    _count("${_line_prefix}igt[ \t]+r0,r1,r2${_line_suffix}" 1 "older igtbr candidate whose boolean result remains live")
    foreach(_cmp IN ITEMS ine ilt ilte igte)
        _forbid("${_line_prefix}${_cmp}[ \t]+" "unfused compare ${_cmp}")
    endforeach()
    _count("${_line_prefix}brt[ \t]+" 6 "conditional branches that still read the live boolean")
    _forbid("${_line_prefix}brf[ \t]+" "unfused conditional branch brf")
    _count("${_line_prefix}\\.traceevent[^\n]*\"O\"" 1 "operation trace event for the retained compare")
elseif(CASE STREQUAL "compare_branch_noopt")
    foreach(_cmp IN ITEMS ieq ine ilt ilte igt igte)
        _require("${_line_prefix}${_cmp}[ \t]+" "unoptimised compare ${_cmp}")
    endforeach()
    foreach(_branch IN ITEMS brt brf)
        _require("${_line_prefix}${_branch}[ \t]+" "unoptimised conditional branch ${_branch}")
    endforeach()
    _require("${_line_prefix}\\.traceevent[^\n]*\"O\"" "operation trace event preserved with -n")
    foreach(_fused IN ITEMS beq bne blt ble bgt bge)
        _forbid("${_line_prefix}${_fused}[ \t]+" "fused branch ${_fused} with -n")
    endforeach()
elseif(CASE STREQUAL "duplicate_link_read")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 1 "linked reads")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 1 "read unlinks")
    _require("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "second read reuses first detached copy")
elseif(CASE STREQUAL "duplicate_link_read_meta_relevant")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 2 "linked reads preserved across relevant metadata")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 2 "read unlinks preserved across relevant metadata")
    _require("${_line_prefix}scopy[ \t]+r4,r3${_line_suffix}" "second read remains linked when metadata uses first detached copy")
    _forbid("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "reuse across relevant register-token metadata")
elseif(CASE STREQUAL "duplicate_link_read_meta_unrelated")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 1 "linked reads across unrelated metadata")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 1 "read unlinks across unrelated metadata")
    _require("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "second read reuses first detached copy across unrelated metadata")
elseif(CASE STREQUAL "duplicate_link_read_trace_relevant")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 2 "linked reads preserved across relevant trace")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 2 "read unlinks preserved across relevant trace")
    _require("${_line_prefix}scopy[ \t]+r4,r3${_line_suffix}" "second read remains linked when trace uses first detached copy")
    _forbid("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "reuse across relevant trace metadata")
elseif(CASE STREQUAL "duplicate_link_read_trace_unrelated")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 1 "linked reads across unrelated trace")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 1 "read unlinks across unrelated trace")
    _require("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "second read reuses first detached copy across unrelated trace")
elseif(CASE STREQUAL "duplicate_link_read_bcopy")
    _count("${_line_prefix}link[ \t]+r[0-9]+,r0${_line_suffix}" 1 "linked binary reads")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 1 "binary read unlinks")
    _require("${_line_prefix}bcopy[ \t]+r4,r2${_line_suffix}" "second binary read reuses first detached copy")
elseif(CASE STREQUAL "duplicate_linkattr_read")
    _count("${_line_prefix}linkattr1[ \t]+r[0-9]+,r0,1${_line_suffix}" 2 "attribute links including setup write")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 2 "attribute unlinks including setup write")
    _require("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "second attribute read reuses first detached copy")
elseif(CASE STREQUAL "duplicate_linkattr_read_bcopy")
    _count("${_line_prefix}linkattr1[ \t]+r[0-9]+,r0,1${_line_suffix}" 2 "binary attribute links including setup write")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 2 "binary attribute unlinks including setup write")
    _require("${_line_prefix}bcopy[ \t]+r4,r2${_line_suffix}" "second binary attribute read reuses first detached copy")
elseif(CASE STREQUAL "duplicate_linkattr_different")
    _count("${_line_prefix}linkattr1[ \t]+r[0-9]+,r0,[12]${_line_suffix}" 4 "attribute links for two setup writes and two reads")
    _count("${_line_prefix}unlink[ \t]+r[0-9]+${_line_suffix}" 4 "attribute unlinks for two setup writes and two reads")
    _require("${_line_prefix}scopy[ \t]+r4,r3${_line_suffix}" "second read remains linked to the second attribute slot")
    _forbid("${_line_prefix}scopy[ \t]+r4,r2${_line_suffix}" "cross-slot detached-copy reuse")
elseif(CASE STREQUAL "nr09_class1")
    _require("${_line_prefix}swapn[ \t]+r0,r1,r2,r3${_line_suffix}" "two-swap superinstruction")
    _require("${_line_prefix}swapn[ \t]+r0,r1,r2,r3,r4,r5${_line_suffix}" "three-swap superinstruction")
    _require("${_line_prefix}swapn[ \t]+r0,r1,r2,r3,r4,r5,r6,r7${_line_suffix}" "four-swap superinstruction")
    _require("${_line_prefix}settpswap[ \t]+r0,256,r1${_line_suffix}" "settp/swap superinstruction")
    _require("${_line_prefix}loadsettp2[ \t]+r0,1,r1,256${_line_suffix}" "load/settp superinstruction")
    _require("${_line_prefix}loadsettpswap[ \t]+r0,2,r1,512,r2${_line_suffix}" "load/settp/swap superinstruction")
    _require("${_line_prefix}swapsettp[ \t]+r0,r1,r2,256${_line_suffix}" "swap/settp superinstruction")
    _require("${_line_prefix}swapsettpswap[ \t]+r0,r1,r2,512,r3${_line_suffix}" "swap/settp/swap superinstruction")
    _require("${_line_prefix}settpswapsettpswap[ \t]+r0,512,r1,r2,r3${_line_suffix}" "settp/swap/settp/swap superinstruction")
    _require("${_line_prefix}nulln[ \t]+r0,r1${_line_suffix}" "two-null superinstruction")
    _require("${_line_prefix}nulln[ \t]+r0,r1,r2${_line_suffix}" "three-null superinstruction")
    _require("${_line_prefix}nulln[ \t]+r0,r1,r2,r3${_line_suffix}" "four-null superinstruction")
    _require("${_line_prefix}load[ \t]+r0,10${_line_suffix}" "withdrawn load/copy source load")
    _require("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" "withdrawn load/copy remains expanded")
    _require("${_line_prefix}load[ \t]+r0,11${_line_suffix}" "first distinct load remains expanded")
    _require("${_line_prefix}load[ \t]+r1,12${_line_suffix}" "second distinct load remains expanded")
    _require("${_line_prefix}load[ \t]+r0,13${_line_suffix}" "first equal load remains expanded")
    _require("${_line_prefix}load[ \t]+r1,13${_line_suffix}" "second equal load remains expanded")
elseif(CASE STREQUAL "nr09_class1_noopt")
    foreach(_fused IN ITEMS swapn settpswap loadsettp2 loadsettpswap swapsettp swapsettpswap settpswapsettpswap nulln)
        _forbid("${_line_prefix}${_fused}[ \t]+" "${_fused} with -n")
    endforeach()
    _require("${_line_prefix}swap[ \t]+r0,r1${_line_suffix}" "unoptimised swap")
    _require("${_line_prefix}settp[ \t]+r0,256${_line_suffix}" "unoptimised settp")
    _require("${_line_prefix}null[ \t]+r0${_line_suffix}" "unoptimised null")
    _require("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" "unoptimised icopy")
elseif(CASE STREQUAL "whole_procedure_flow")
    _count("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" 2 "typed copies retained only by other-view and TRACE cases")
    _require("${_line_prefix}load[ \t]+r1,7${_line_suffix}" "changed-source producer retargeted to the copied destination")
    _forbid("${_line_prefix}icopy[ \t]+r5,r4${_line_suffix}" "producer destination forwarded before a later call barrier")
    _require("${_line_prefix}load[ \t]+r5,17${_line_suffix}" "call-crossing value produced directly in its final register")
    _require("${_line_prefix}ieq[ \t]+r6,r5,17${_line_suffix}" "post-call consumer stays on the copied register")
    _count("${_line_prefix}ieq[ \t]+r2,r0,(7|9)${_line_suffix}" 3 "compare consumers redirected to original integer registers")
    _count("${_line_prefix}ieq[ \t]+r2,r1,7${_line_suffix}" 2 "negative compare consumers kept on copied registers")
    _require("${_line_prefix}scopy[ \t]+r2,r1${_line_suffix}" "other-view negative consumer")
    _require("${_line_prefix}\\.traceevent[^\\n]*copy" "relevant TRACE observation")
    _count("${_line_prefix}load[ \t]+r0,3${_line_suffix}" 1 "redundant join load removed")
    _forbid("${_line_prefix}load[ \t]+r0,99${_line_suffix}" "unreachable load")
    _forbid("${_line_prefix}ieq[ \t]+r1,r0,99${_line_suffix}" "unreachable compare")
    _require("${_line_prefix}load[ \t]+r0,5${_line_suffix}" "dead integer load retained pending hidden-lifetime proof")
    _require("${_line_prefix}ieq[ \t]+r1,r0,5${_line_suffix}" "dead compare retained pending hidden-lifetime proof")
    _require("${_line_prefix}load[ \t]+r2,4\\.5${_line_suffix}" "dead float load retained pending hidden-lifetime proof")
elseif(CASE STREQUAL "whole_procedure_flow_noopt")
    _count("${_line_prefix}icopy[ \t]+r1,r0${_line_suffix}" 6 "all r1/r0 typed copies with -n")
    _require("${_line_prefix}icopy[ \t]+r5,r4${_line_suffix}" "call-crossing typed copy with -n")
    _count("${_line_prefix}load[ \t]+r0,3${_line_suffix}" 2 "redundant loads with -n")
    _require("${_line_prefix}load[ \t]+r0,99${_line_suffix}" "unreachable load with -n")
    _require("${_line_prefix}ieq[ \t]+r1,r0,99${_line_suffix}" "unreachable compare with -n")
    _require("${_line_prefix}load[ \t]+r0,5${_line_suffix}" "dead integer load with -n")
    _require("${_line_prefix}load[ \t]+r2,4\\.5${_line_suffix}" "dead float load with -n")
elseif(CASE STREQUAL "whole_procedure_panel")
    _forbid("${_line_prefix}fcopy[ \t]+r11,r10${_line_suffix}" "proved float copy")
    _require("${_line_prefix}feq[ \t]+r9,r10,7\\.5${_line_suffix}" "float consumer redirected")
    _forbid("${_line_prefix}scopy[ \t]+r13,r12${_line_suffix}" "proved string copy")
    _require("${_line_prefix}seq[ \t]+r9,r12,\"alpha\"${_line_suffix}" "strict string consumer redirected")
    _require("${_line_prefix}dcopy[ \t]+r15,r14${_line_suffix}" "decimal copy retained pending allocation/signal proof")
    _forbid("${_line_prefix}copy[ \t]+r16,r16${_line_suffix}" "identity full copy")
    _require("${_line_prefix}copy[ \t]+r18,r17${_line_suffix}" "nonidentity full copy retained")
    _count("${_line_prefix}null[ \t]+r20${_line_suffix}" 1 "redundant NULL removed across join")
    _count("${_line_prefix}null[ \t]+r21${_line_suffix}" 2 "NULLs separated by an observed write")
    _count("${_line_prefix}itof[ \t]+r22${_line_suffix}" 1 "redundant context-free conversion removed")
    _count("${_line_prefix}itof[ \t]+r23${_line_suffix}" 2 "conversions separated by an observed integer write")
    _require("${_line_prefix}load[ \t]+r24,-0\\.0${_line_suffix}" "negative floating zero load")
    _require("${_line_prefix}load[ \t]+r24,0\\.0${_line_suffix}" "positive floating zero load")
    _require("${_line_prefix}icopy[ \t]+r26,r25${_line_suffix}" "mixed-entry loop copy retained")
    _require("${_line_prefix}ieq[ \t]+r27,r26,77${_line_suffix}" "mixed-entry loop consumer not partially rewritten")
    _forbid("${_line_prefix}icopy[ \t]+r29,r28${_line_suffix}" "dominating loop copy")
    _require("${_line_prefix}ieq[ \t]+r30,r28,79${_line_suffix}" "dominated loop consumer redirected")
    _require("${_line_prefix}load[ \t]+r31,99${_line_suffix}" "TRACE-observed otherwise-dead load")
    _require("trace-keeps-load" "TRACE record for retained load")
    _forbid("${_line_prefix}load[ \t]+r32,88${_line_suffix}" "unreachable traced load")
    _forbid("unreachable-trace" "unreachable TRACE record")
    _forbid("unreachable-source-step" "unreachable source-step record")
    _forbid("${_line_prefix}load[ \t]+r33,87${_line_suffix}" "unreachable source-stepped load")
    _require("${_line_prefix}endlife[ \t]+r36${_line_suffix}" "ENDLIFE preserved")
    _forbid("${_line_prefix}icopy[ \t]+r38,r37${_line_suffix}" "copy in region after ENDLIFE")
    _require("${_line_prefix}ieq[ \t]+r9,r37,83${_line_suffix}" "consumer after ENDLIFE redirected")
    _forbid("${_line_prefix}icopy[ \t]+r40,r39${_line_suffix}" "copy before a later exceptional ENDLIFE")
    _require("${_line_prefix}load[ \t]+r40,89${_line_suffix}" "producer retargeted before a later exceptional ENDLIFE")
    _forbid("${_line_prefix}icopy[ \t]+r44,r43${_line_suffix}" "copy whose final value is observed by following metadata")
    _require("${_line_prefix}load[ \t]+r44,97${_line_suffix}" "metadata-observed value produced directly in its final register")
    _forbid("${_line_prefix}icopy[ \t]+r47,r46${_line_suffix}" "copy with unrelated metadata")
    _require("${_line_prefix}ieq[ \t]+r45,r46,101${_line_suffix}" "consumer across unrelated metadata redirected")
    _require("${_line_prefix}load[ \t]+r49,107${_line_suffix}" "registered SIGNAL-handler body retained as reachable")
    _require("${_line_prefix}load[ \t]+r50,109${_line_suffix}" "value observable by an asynchronous SIGNAL handler retained")
    _require("${_line_prefix}copy[ \t]+r52,r52${_line_suffix}" "identity copy observed by TRACE across a label retained")
    _require("trace-after-label" "TRACE record after a label")
    _forbid("${_line_prefix}icopy[ \t]+r54,r53${_line_suffix}" "typed copy across an unobserved throwing instruction")
    _require("${_line_prefix}ieq[ \t]+r56,r53,111${_line_suffix}" "consumer across an unobserved throw redirected")
    _require("${_line_prefix}icopy[ \t]+r58,r57${_line_suffix}" "typed copy observed by a local exception handler retained")
    _require("${_line_prefix}ieq[ \t]+r60,r58,113${_line_suffix}" "exception handler still reads the copied register")
    _require("${_line_prefix}ieq[ \t]+r61,r62,1${_line_suffix}" "dead numeric result retained because its destination may release hidden lifetime state")
    _forbid("${_line_prefix}icopy[ \t]+r62,r61${_line_suffix}" "copy admitted by complete local jump-table flow")
    _require("${_line_prefix}ieq[ \t]+r63,r61,127${_line_suffix}" "jump-table-region consumer redirected to the source register")
elseif(CASE STREQUAL "whole_procedure_panel_noopt")
    foreach(_copy IN ITEMS "fcopy r11,r10" "scopy r13,r12" "dcopy r15,r14" "copy r16,r16" "copy r18,r17" "icopy r26,r25" "icopy r29,r28" "icopy r38,r37" "icopy r40,r39" "icopy r44,r43" "icopy r47,r46" "icopy r62,r61")
        string(REPLACE " " "[ \t]+" _copy_regex "${_copy}")
        _require("${_line_prefix}${_copy_regex}${_line_suffix}" "${_copy} with -n")
    endforeach()
    _count("${_line_prefix}null[ \t]+r20${_line_suffix}" 2 "both join NULLs with -n")
    _count("${_line_prefix}null[ \t]+r21${_line_suffix}" 2 "both separated NULLs with -n")
    _count("${_line_prefix}itof[ \t]+r22${_line_suffix}" 2 "both join conversions with -n")
    _count("${_line_prefix}itof[ \t]+r23${_line_suffix}" 2 "both separated conversions with -n")
    _require("${_line_prefix}load[ \t]+r32,88${_line_suffix}" "unreachable load with -n")
    _require("unreachable-trace" "unreachable TRACE with -n")
    _require("unreachable-source-step" "unreachable source step with -n")
    _require("${_line_prefix}load[ \t]+r49,107${_line_suffix}" "registered SIGNAL-handler body with -n")
    _require("${_line_prefix}load[ \t]+r50,109${_line_suffix}" "asynchronous SIGNAL-observed value with -n")
    _require("${_line_prefix}copy[ \t]+r52,r52${_line_suffix}" "TRACE-observed identity copy across a label with -n")
    _require("${_line_prefix}icopy[ \t]+r54,r53${_line_suffix}" "copy across throwing instruction with -n")
    _require("${_line_prefix}icopy[ \t]+r58,r57${_line_suffix}" "exception-handler copy with -n")
    _require("${_line_prefix}ieq[ \t]+r61,r62,1${_line_suffix}" "dead numeric result with -n")
elseif(CASE STREQUAL "nr18_flow_harvest")
    foreach(_copy IN ITEMS "icopy r1,r0" "fcopy r3,r2" "icopy r24,r23" "icopy r19,r18" "icopy r21,r20" "icopy r35,r34" "icopy r37,r36" "icopy r39,r38")
        string(REPLACE " " "[ \t]+" _copy_regex "${_copy}")
        _forbid("${_line_prefix}${_copy_regex}${_line_suffix}" "${_copy} removed by destination forwarding")
    endforeach()
    _require("${_line_prefix}load[ \t]+r1,7${_line_suffix}" "integer producer retargeted")
    _require("${_line_prefix}load[ \t]+r3,2\\.5${_line_suffix}" "float producer retargeted")
    _require("${_line_prefix}ieq[ \t]+r24,r22,31${_line_suffix}" "comparison producer retargeted")
    foreach(_copy IN ITEMS "icopy r5,r4" "icopy r9,r7" "scopy r11,r10" "icopy r13,r12" "icopy r15,r14" "fcopy r26,r25" "icopy r28,r27" "icopy r30,r29" "icopy r32,r31" "icopy r41,r40")
        string(REPLACE " " "[ \t]+" _copy_regex "${_copy}")
        _require("${_line_prefix}${_copy_regex}${_line_suffix}" "${_copy} negative retained")
    endforeach()
    _require("source-step-after-copy" "address-observing source step retained")
    _require("nr18\\.producer" "producer metadata retained")
    _require("${_line_prefix}jumpr[ \t]+r42," "jump table without a local miss edge retained fail-closed")
elseif(CASE STREQUAL "nr18_flow_harvest_noopt")
    foreach(_copy IN ITEMS "icopy r1,r0" "fcopy r3,r2" "icopy r24,r23" "icopy r19,r18" "icopy r21,r20" "icopy r35,r34" "icopy r37,r36" "icopy r39,r38")
        string(REPLACE " " "[ \t]+" _copy_regex "${_copy}")
        _require("${_line_prefix}${_copy_regex}${_line_suffix}" "${_copy} with -n")
    endforeach()
elseif(CASE STREQUAL "nr09_class1_boundaries")
    foreach(_fused IN ITEMS swapn loadsettpswap swapsettpswap settpswapsettpswap nulln)
        _forbid("${_line_prefix}${_fused}[ \t]+" "${_fused} across a boundary or mismatched dependency")
    endforeach()
    _count("${_line_prefix}settpswap[ \t]+" 3 "valid two-instruction subsets retained in mismatch cases")
    _count("${_line_prefix}loadsettp2[ \t]+" 1 "valid load/settp subset before a boundary")
    _count("${_line_prefix}swapsettp[ \t]+" 1 "valid swap/settp subset before a boundary")
    _require("${_line_prefix}icopy[ \t]+r1,r2${_line_suffix}" "mismatched load/copy source preserved")
    _require("${_line_prefix}settp[ \t]+r2,512${_line_suffix}" "mismatched shared status preserved")
elseif(CASE MATCHES "^barrier_")
    _count("${_line_prefix}swap[ \t]+r1,r2${_line_suffix}" 2 "r1/r2 swaps preserved by optimiser barrier")
else()
    _optimizer_fail("Unknown optimiser check case")
endif()
