cmake_minimum_required(VERSION 3.24)

set(RXUNICODE_CASEFOLD_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/unicode-17.0.0/CaseFolding.txt")
set(RXUNICODE_GRAPHEME_PROPERTY_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/unicode-17.0.0/auxiliary/GraphemeBreakProperty.txt")
set(RXUNICODE_GRAPHEME_TEST_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/unicode-17.0.0/auxiliary/GraphemeBreakTest.txt")
set(RXUNICODE_EMOJI_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/unicode-17.0.0/emoji/emoji-data.txt")
set(RXUNICODE_DERIVED_CORE_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/unicode-17.0.0/DerivedCoreProperties.txt")
set(RXUNICODE_UNICODE_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/unicode-17.0.0/UnicodeData.txt")
set(RXUNICODE_NORMALIZATION_PROPERTIES_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/unicode-17.0.0/DerivedNormalizationProps.txt")
set(RXUNICODE_NORMALIZATION_TEST_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/unicode-17.0.0/NormalizationTest.txt")
set(RXUNICODE_SPECIAL_CASING_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/unicode-17.0.0/SpecialCasing.txt")
set(RXUNICODE_WINDOWS1252_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/legacy/CP1252-2.0.0.txt")
set(RXUNICODE_IBM437_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/legacy/CP437-2.0.0.txt")
set(RXUNICODE_IBM850_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/legacy/CP850-2.0.0.txt")
set(RXUNICODE_IBM1047_DATA
  "${CMAKE_CURRENT_SOURCE_DIR}/unicode/data/legacy/IBM1047.txt")
set(RXUNICODE_CASEFOLD_TOOL_DIR
  "${CMAKE_CURRENT_BINARY_DIR}/rexx/unicode-tools")
set(RXUNICODE_CASEFOLD_TABLE_RXBIN
  "${RXUNICODE_CASEFOLD_TOOL_DIR}/casefold_table.rxbin")
set(RXUNICODE_GRAPHEME_TABLE_RXBIN
  "${RXUNICODE_CASEFOLD_TOOL_DIR}/grapheme_table.rxbin")
set(RXUNICODE_CASE_MAPPING_TABLE_RXBIN
  "${RXUNICODE_CASEFOLD_TOOL_DIR}/case_mapping_table.rxbin")
set(RXUNICODE_NORMALIZATION_TABLE_RXBIN
  "${RXUNICODE_CASEFOLD_TOOL_DIR}/unicode_d.rxbin")
set(RXUNICODE_ENCODING_TABLE_RXBIN
  "${RXUNICODE_CASEFOLD_TOOL_DIR}/encoding_table.rxbin")

add_subdirectory(rexx)
add_subdirectory(tests_functional)
