# Share the scanner's exact Unicode letter categories with Classic runtime
# validation. Generated sources remain in the build tree; no Python dependency.
function(crexx_classic_u32_hex value output)
    set(result "")
    set(digits "0123456789ABCDEF")
    foreach(byte RANGE 0 3)
        math(EXPR octet "(${value} >> (${byte} * 8)) & 255")
        math(EXPR high "${octet} / 16")
        math(EXPR low "${octet} % 16")
        string(SUBSTRING "${digits}" ${high} 1 hi)
        string(SUBSTRING "${digits}" ${low} 1 lo)
        string(APPEND result "${hi}${lo}")
    endforeach()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

function(crexx_classic_unicode_source output)
    set(input "${CMAKE_SOURCE_DIR}/re2c/include/unicode_categories.re")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${input}")
    file(STRINGS "${input}" categories)
    set(header "")
    set(records "")
    set(record_count 0)
    foreach(category L Ll Lu)
        set(found FALSE)
        foreach(line IN LISTS categories)
            if(line MATCHES "^${category} = ")
                string(REGEX REPLACE "^[^[]*\\[" "" ranges "${line}")
                string(REGEX REPLACE "\\].*$" "" ranges "${ranges}")
                set(found TRUE)
                break()
            endif()
        endforeach()
        if(NOT found)
            message(FATAL_ERROR "Missing scanner Unicode category ${category}")
        endif()
        set(count 0)
        crexx_classic_u32_hex(${record_count} start_hex)
        while(NOT ranges STREQUAL "")
            foreach(bound first last)
                string(SUBSTRING "${ranges}" 0 2 escape)
                if(escape STREQUAL "\\x")
                    set(width 2)
                elseif(escape STREQUAL "\\u")
                    set(width 4)
                elseif(escape STREQUAL "\\U")
                    set(width 8)
                else()
                    message(FATAL_ERROR "Invalid scanner category escape ${escape}")
                endif()
                string(SUBSTRING "${ranges}" 2 ${width} hex)
                math(EXPR ${bound} "0x${hex}")
                math(EXPR consumed "${width} + 2")
                string(SUBSTRING "${ranges}" ${consumed} -1 ranges)
                if(bound STREQUAL "first")
                    if(ranges MATCHES "^-")
                        string(SUBSTRING "${ranges}" 1 -1 ranges)
                    else()
                        set(last ${first})
                        break()
                    endif()
                endif()
            endforeach()
            crexx_classic_u32_hex(${first} first_hex)
            crexx_classic_u32_hex(${last} last_hex)
            string(APPEND records "${first_hex}${last_hex}")
            math(EXPR count "${count} + 1")
        endwhile()
        crexx_classic_u32_hex(${count} count_hex)
        string(APPEND header "${start_hex}${count_hex}")
        math(EXPR record_count "${record_count} + ${count}")
    endforeach()
    set(case_input "${CMAKE_SOURCE_DIR}/lib/rxfnsg/unicode/data/unicode-17.0.0/UnicodeData.txt")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${case_input}")
    file(STRINGS "${case_input}" case_lines)
    set(c_header "/* Generated from pinned Unicode 17.0.0 simple case mappings. */\n")
    foreach(direction upper lower)
        set(case_records "")
        set(count 0)
        string(APPEND c_header "static const unsigned int levelc_${direction}_cases[][2] = {\n")
        foreach(line IN LISTS case_lines)
            if(line MATCHES "^([0-9A-F]+);[^;]*;[^;]*;[^;]*;[^;]*;[^;]*;[^;]*;[^;]*;[^;]*;[^;]*;[^;]*;[^;]*;([0-9A-F]*);([0-9A-F]*);")
                set(cp_hex "${CMAKE_MATCH_1}")
                if(direction STREQUAL "upper")
                    set(mapped_hex "${CMAKE_MATCH_2}")
                else()
                    set(mapped_hex "${CMAKE_MATCH_3}")
                endif()
                if(NOT mapped_hex STREQUAL "" AND NOT (direction STREQUAL "upper" AND cp_hex STREQUAL "00B5"))
                    math(EXPR cp "0x${cp_hex}")
                    math(EXPR mapped "0x${mapped_hex}")
                    crexx_classic_u32_hex(${cp} cp_bytes)
                    crexx_classic_u32_hex(${mapped} mapped_bytes)
                    string(APPEND case_records "${cp_bytes}${mapped_bytes}")
                    string(APPEND c_header "{0x${cp_hex},0x${mapped_hex}},\n")
                    math(EXPR count "${count} + 1")
                endif()
            endif()
        endforeach()
        string(APPEND c_header "};\n")
        crexx_classic_u32_hex(${record_count} start_hex)
        crexx_classic_u32_hex(${count} count_hex)
        string(APPEND header "${start_hex}${count_hex}")
        string(APPEND records "${case_records}")
        math(EXPR record_count "${record_count} + ${count}")
    endforeach()
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/generated")
    file(WRITE "${CMAKE_BINARY_DIR}/generated/crexx_levelc_unicode_cases.h.tmp" "${c_header}")
    configure_file("${CMAKE_BINARY_DIR}/generated/crexx_levelc_unicode_cases.h.tmp"
                   "${CMAKE_BINARY_DIR}/generated/crexx_levelc_unicode_cases.h" COPYONLY)
    set(RXCLASSIC_UNICODE_CATEGORIES "${header}${records}")
    configure_file("${CMAKE_SOURCE_DIR}/lib/rxfnsc/RexxClassicUnicodeProperties.crexx.in"
                   "${output}" @ONLY)
endfunction()
