function(crexx_label_smoke_tests)
    foreach(_crexx_smoke_test IN LISTS ARGN)
        if(TEST "${_crexx_smoke_test}")
            set_property(TEST "${_crexx_smoke_test}" APPEND PROPERTY LABELS smoke)
        else()
            message(STATUS "Smoke test '${_crexx_smoke_test}' is not present in this configuration; skipping")
        endif()
    endforeach()
endfunction()
