# Regression for speculative source loading while binary signatures refer to
# classes whose metadata has not yet been registered. No elapsed-time assertion.
function(run_checked label)
    execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${WORK_ROOT}"
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT rc EQUAL 0)
        message(FATAL_ERROR "${label}: ${rc}\n${out}\n${err}")
    endif()
endfunction()

file(REMOVE_RECURSE "${WORK_ROOT}")
file(MAKE_DIRECTORY "${WORK_ROOT}")
set(extension "${WORK_ROOT}/extension.crexx")
set(consumer "${WORK_ROOT}/consumer.crexx")
set(snapshot "${WORK_ROOT}/dependencies.snapshot")
foreach(mode IN ITEMS opt noopt)
    set(options)
    if(mode STREQUAL noopt)
        list(APPEND options -n)
    endif()
    file(WRITE "${extension}" "options levelb\nnamespace _rxsysb expose unused_extension\nunused_extension: procedure = .int\n  arg value = .int\n  return value + 1\n")
    file(WRITE "${consumer}" "options levelb\nimport rxfnsb\nmain: procedure = .int\n  if abs(-7) <> 7 then return 1\n  return 0\n")
    set(arguments ${options} -s "${WORK_ROOT}" -i "${BIN}" -o consumer "${consumer}")
    run_checked("${mode} compile unused extension consumer" "${RXC}" --project-dependencies "${snapshot}" ${arguments})
    run_checked("${mode} fresh snapshot" "${RXC}" --check-project-dependencies "${snapshot}" ${arguments})
    file(APPEND "${extension}" "\n/* private unused body edit */\n")
    run_checked("${mode} unused source body must not invalidate" "${RXC}" --check-project-dependencies "${snapshot}" ${arguments})

    file(WRITE "${consumer}" "options levelb\nimport _rxsysb\nmain: procedure = .int\n  if unused_extension(7) <> 8 then return 1\n  return 0\n")
    run_checked("${mode} compile actual extension consumer" "${RXC}" --project-dependencies "${snapshot}" ${arguments})
    run_checked("${mode} assemble consumer" "${RXAS}" -o consumer consumer)
    run_checked("${mode} compile extension" "${RXC}" ${options} -i "${BIN}" -o extension "${extension}")
    run_checked("${mode} assemble extension" "${RXAS}" -o extension extension)
    run_checked("${mode} link used extension" "${RXLINK}" -s -o program consumer.rxbin extension.rxbin "${BIN}/library.rxbin" "${BIN}/classlib.rxbin")
    run_checked("${mode} execute used extension" "${RXVME}" program.rxbin)
    file(APPEND "${extension}" "\n/* now a real source dependency */\n")
    execute_process(COMMAND "${RXC}" --check-project-dependencies "${snapshot}" ${arguments}
        WORKING_DIRECTORY "${WORK_ROOT}" RESULT_VARIABLE stale_rc OUTPUT_QUIET ERROR_QUIET)
    if(NOT stale_rc EQUAL 2)
        message(FATAL_ERROR "${mode}: used source changed without invalidation (${stale_rc})")
    endif()
    file(WRITE "${consumer}" "options levelb\nimport _rxsysb\nmain: procedure = .int\n  return unused_extension(7, 8)\n")
    execute_process(COMMAND "${RXC}" ${arguments} WORKING_DIRECTORY "${WORK_ROOT}"
        RESULT_VARIABLE invalid_rc OUTPUT_VARIABLE invalid_out ERROR_VARIABLE invalid_err)
    if(invalid_rc EQUAL 0 OR NOT "${invalid_out}${invalid_err}" MATCHES "UNEXPECTED_ARGUMENT")
        message(FATAL_ERROR "${mode}: used callable validation weakened\n${invalid_out}\n${invalid_err}")
    endif()
endforeach()
