# Exposed globals use the module's export chain and complete type metadata.
# Every import lane must retain the same runtime values and array diagnostics.
function(run_checked label)
    execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${work}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 60)
    if(NOT "${result}" STREQUAL "0")
        message(FATAL_ERROR "${label}: exit ${result}\n${out}\n${err}")
    endif()
    set(last_output "${out}" PARENT_SCOPE)
endfunction()

function(expect_error label diagnostic)
    execute_process(COMMAND "${RXC}" ${options} ${import_options} -s imports -i imports -i "${BIN}" consumer.crexx
        WORKING_DIRECTORY "${work}" RESULT_VARIABLE result
        OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 60)
    if(NOT "${result}" STREQUAL "2" OR NOT "${out}${err}" MATCHES "${diagnostic}")
        message(FATAL_ERROR "${label}: expected ${diagnostic}, got ${result}\n${out}\n${err}")
    endif()
endfunction()

function(check_runtime label)
    run_checked("${label} assemble consumer" "${RXAS}" ${asm_options} -o consumer consumer.rxas)
    run_checked("${label} link" "${RXLINK}" -s -o program consumer.rxbin
        "${provider_binary}" "${BIN}/library.rxbin" "${BIN}/classlib.rxbin")
    foreach(vm IN ITEMS "${RXBVM}" "${RXVM}")
        run_checked("${label} run ${vm}" "${vm}" program.rxbin)
        string(REPLACE "\r\n" "\n" last_output "${last_output}")
        if(NOT last_output STREQUAL expected)
            message(FATAL_ERROR "${label}: incorrect globals: ${last_output}")
        endif()
    endforeach()
endfunction()

file(READ "${FIXTURE}" provider_source)
set(consumer_source [=[options levelb
import rxfnsb
namespace binary_global_import_types
main: procedure = .int expose state labels grid boxes counter counter_ref
  call Make
  box = boxes[1]
  saved = snapshot counter_ref
  counter = 37
  say state["text"] || ":" || labels[1] || ":" || grid[-2, 1] || ":" || grid[2, 3] || ":" || box["number"] || ":" || saved || ":" || snapshot counter_ref
  return 0
]=])
file(REMOVE_RECURSE "${WORK_ROOT}")
foreach(mode IN ITEMS opt noopt)
    set(options)
    if(mode STREQUAL noopt)
        list(APPEND options -n)
    endif()
    foreach(asm_mode IN ITEMS opt noopt)
        set(asm_options)
        if(asm_mode STREQUAL noopt)
            list(APPEND asm_options -n)
        endif()
        set(build "${WORK_ROOT}/${mode}-${asm_mode}")
        set(work "${build}/provider")
        file(MAKE_DIRECTORY "${work}")
        file(WRITE "${work}/provider.crexx" "${provider_source}")
        run_checked("compile provider" "${RXC}" ${options} -i "${BIN}" provider.crexx)
        run_checked("assemble provider" "${RXAS}" ${asm_options} provider.rxas)
        file(READ "${work}/provider.rxas" provider_assembly)
        foreach(name IN ITEMS state labels grid boxes counter counter_ref)
            if(NOT provider_assembly MATCHES "[.]meta \"binary_global_import_types[.]${name}\"=\"b\" \"[^\"]+\" g[0-9]+")
                message(FATAL_ERROR "Missing complete metadata for ${name}")
            endif()
        endforeach()
        set(single_provider "${work}/provider.rxbin")
        file(WRITE "${work}/other.crexx" "options levelb\nnamespace other_globals expose Set grid\nSet: procedure = .void expose grid\n  grid = .string[5 to 7]\n  grid[5] = \"other\"\n  return\n")
        run_checked("compile other namespace" "${RXC}" ${options} -i "${BIN}" other.crexx)
        run_checked("assemble other namespace" "${RXAS}" ${asm_options} other.rxas)
        run_checked("shared pool" "${RXLINK}" -s -r other -r provider -o shared other.rxbin provider.rxbin)
        set(shared_provider "${work}/shared.rxbin")

        foreach(kind IN ITEMS source rxas rxbin shared)
            set(import_options)
            if(kind STREQUAL rxas)
                list(APPEND import_options --import-rxas)
            endif()
            set(work "${build}/${kind}")
            file(MAKE_DIRECTORY "${work}/imports")
            set(provider_binary "${single_provider}")
            if(kind STREQUAL source)
                file(WRITE "${work}/imports/provider.crexx" "${provider_source}")
            elseif(kind STREQUAL rxas)
                file(WRITE "${work}/imports/provider.rxas" "${provider_assembly}")
            else()
                if(kind STREQUAL shared)
                    set(provider_binary "${shared_provider}")
                endif()
                file(COPY "${provider_binary}" DESTINATION "${work}/imports")
            endif()
            file(WRITE "${work}/consumer.crexx" "${consumer_source}")
            run_checked("${mode}/${asm_mode}/${kind} compile consumer" "${RXC}" ${options}
                ${import_options} -s imports -i imports -i "${BIN}" consumer.crexx)
            set(expected "hello:value:42:17:7:31:37\n")
            check_runtime("${mode}/${asm_mode}/${kind}")

            foreach(access IN ITEMS "grid[-3, 1]" "grid[3, 1]" "grid[-2, 4]")
                file(WRITE "${work}/consumer.crexx" "options levelb\nnamespace binary_global_import_types\nmain: procedure = .int expose grid\n  say ${access}\n  return 0\n")
                expect_error("${kind} ${access}" OUT_OF_RANGE)
            endforeach()
            foreach(extra_index IN ITEMS 1 0)
                file(WRITE "${work}/consumer.crexx" "options levelb\nnamespace binary_global_import_types\nmain: procedure = .int expose grid\n  say grid[-2, 1, ${extra_index}]\n  return 0\n")
                expect_error("${kind} extra dimension ${extra_index}" ARRAY_DIMS_MISMATCH)
            endforeach()
            file(WRITE "${work}/consumer.crexx" "options levelb\nnamespace binary_global_import_types\nmain: procedure = .int expose grid\n  grid = .int[-1 to 1, 1 to 3]\n  return 0\n")
            expect_error("${kind} incompatible bounds" TYPE_MISMATCH)
        endforeach()

        # Old clear-only metadata can use the caller's explicit declaration.
        # Without one, both reads and writes must stop before code generation.
        foreach(kind IN ITEMS rxas rxbin)
            set(import_options)
            if(kind STREQUAL rxas)
                list(APPEND import_options --import-rxas)
            endif()
            foreach(contract IN ITEMS missing clear unknown empty malformed)
                set(work "${build}/${kind}-${contract}")
                file(MAKE_DIRECTORY "${work}/imports")
                set(metadata)
                if(contract STREQUAL clear)
                    set(metadata "  .meta \"legacy.values\"\n")
                elseif(contract STREQUAL unknown)
                    set(metadata "  .meta \"legacy.values\"=\"b\" \".unknown\" g0\n")
                elseif(contract STREQUAL empty)
                    set(metadata "  .meta \"legacy.values\"=\"b\" \"\" g0\n")
                elseif(contract STREQUAL malformed)
                    set(metadata "  .meta \"legacy.values\"=\"b\" \".int[\" g0\n")
                endif()
                set(legacy ".globals=1\ng0 .expose=legacy.values\nInit() .locals=1 .expose=legacy.init\n  .meta \"legacy.init\"=\"b\" \".void\" Init() \"\"\n${metadata}  ret\n")
                file(WRITE "${work}/legacy.rxas" "${legacy}")
                run_checked("assemble ${contract}" "${RXAS}" ${asm_options} legacy.rxas)
                file(COPY "${work}/legacy.${kind}" DESTINATION "${work}/imports")
                set(provider_binary "${work}/legacy.rxbin")
                foreach(statement IN ITEMS "say values[-1]" "values[-1] = 42")
                    file(WRITE "${work}/consumer.crexx" "options levelb\nnamespace legacy\nmain: procedure = .int expose values\n  call Init\n  ${statement}\n  return 0\n")
                    if(contract STREQUAL empty OR contract STREQUAL malformed)
                        expect_error("${kind}/${contract} ${statement}" SYNTAX_ERROR_IN_IMPORT_DECL)
                    elseif(statement STREQUAL "say values[-1]")
                        expect_error("${kind}/${contract} read" UNKNOWN_TYPE)
                    else()
                        # An untyped write infers the existing one-based array.
                        expect_error("${kind}/${contract} inferred write" OUT_OF_RANGE)
                    endif()
                endforeach()
                if(contract STREQUAL missing OR contract STREQUAL clear OR contract STREQUAL unknown)
                    file(WRITE "${work}/consumer.crexx" "options levelb\nnamespace legacy\nmain: procedure = .int expose values\n  values = .int[-1 to 1]\n  call Init\n  values[-1] = 42\n  say values[-1]\n  return 0\n")
                    run_checked("${kind}/${contract} explicit caller type" "${RXC}" ${options}
                        ${import_options} -s imports -i imports -i "${BIN}" consumer.crexx)
                    set(expected "42\n")
                    check_runtime("${kind}/${contract} legacy caller")
                endif()
            endforeach()
        endforeach()
    endforeach()
endforeach()
