foreach(required RXC BINDIR NAME SOURCE SOURCE_NODE MEMBER BUILD_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()

set(log "${BUILD_DIR}/${NAME}_source_tree.log")
execute_process(
        COMMAND "${RXC}" -d1 -i "${BINDIR}" -o "${NAME}_source_tree" "${SOURCE}"
        WORKING_DIRECTORY "${BUILD_DIR}"
        OUTPUT_FILE "${log}" ERROR_FILE "${log}"
        RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "${NAME} source-tree compile failed; see ${log}")
endif()
file(READ "${log}" output)
string(FIND "${output}" "--- STAGE_RAW ---" raw_start)
string(FIND "${output}" "--- STAGE_LEVELC_LOWERED ---" lowered_start)
string(FIND "${output}" "--- STAGE_FIXUP ---" lowered_end)
if(raw_start EQUAL -1 OR lowered_start LESS raw_start OR lowered_end LESS lowered_start)
    message(FATAL_ERROR "${NAME} source/canonical stages missing; see ${log}")
endif()
math(EXPR raw_length "${lowered_start} - ${raw_start}")
math(EXPR lowered_length "${lowered_end} - ${lowered_start}")
string(SUBSTRING "${output}" ${raw_start} ${raw_length} raw)
string(SUBSTRING "${output}" ${lowered_start} ${lowered_length} lowered)
string(FIND "${raw}" "${SOURCE_NODE} : " raw_node)
string(FIND "${lowered}" "MEMBER_CALL : \"${MEMBER}\"" member_node)
string(FIND "${lowered}" "${SOURCE_NODE} : " surviving_node)
if(raw_node EQUAL -1 OR member_node EQUAL -1 OR NOT surviving_node EQUAL -1)
    message(FATAL_ERROR "${NAME} source/canonical queue node mismatch; see ${log}")
endif()
if(NEEDS_PARSEPLAN)
    string(FIND "${raw}" "TEMPLATES :" template_node)
    string(FIND "${lowered}" "ASSEMBLER : \"parseplan\"" parse_node)
    if(template_node EQUAL -1 OR parse_node EQUAL -1)
        message(FATAL_ERROR "${NAME} lost its shared parse template route; see ${log}")
    endif()
endif()
