foreach(required SOURCE_DIR BUILD_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
if(NOOPT)
    set(mode noopt)
else()
    set(mode opt)
endif()
set(BUILD_DIR "${BUILD_DIR}/levelc_address_input_exact/${mode}")
file(MAKE_DIRECTORY "${BUILD_DIR}")
file(WRITE "${BUILD_DIR}/levelc-address-three-bytes.txt" "abc")
set(NAME levelc_address_input_exact)
set(SOURCE "${SOURCE_DIR}/${NAME}.rexx")
set(EXPECTED "${SOURCE_DIR}/${NAME}.expected")
include("${CMAKE_CURRENT_LIST_DIR}/levelc_queue_linked.cmake")
set(empty_file "${BUILD_DIR}/levelc-address-empty-output.txt")
if(NOT EXISTS "${empty_file}")
    message(FATAL_ERROR "Blank ADDRESS command did not create its output stream")
endif()
file(SIZE "${empty_file}" empty_size)
if(NOT empty_size EQUAL 0)
    message(FATAL_ERROR "Blank ADDRESS command wrote to its empty output stream")
endif()
set(nul_file "${BUILD_DIR}/levelc-address-nul-output.bin")
file(READ "${nul_file}" nul_bytes HEX)
if(NOT nul_bytes STREQUAL "00")
    message(FATAL_ERROR "ADDRESS output stream lost its embedded NUL byte")
endif()
