foreach(required RXC BINDIR SOURCE BUILD_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()

execute_process(
    COMMAND "${RXC}" -d1 -i "${BINDIR}" -o levelc_strictc_transfer_tree "${SOURCE}"
    WORKING_DIRECTORY "${BUILD_DIR}"
    OUTPUT_VARIABLE out ERROR_VARIABLE err RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "STRICTC transfer tree failed: ${out}${err}")
endif()

set(full "${out}${err}")
string(FIND "${full}" "--- STAGE_RAW ---" raw_start)
string(FIND "${full}" "--- STAGE_LEVELC_LOWERED ---" lowered_start)
if(raw_start EQUAL -1 OR lowered_start EQUAL -1)
    message(FATAL_ERROR "STRICTC source or lowered tree is missing")
endif()
math(EXPR raw_length "${lowered_start} - ${raw_start}")
string(SUBSTRING "${full}" ${raw_start} ${raw_length} raw)
string(SUBSTRING "${full}" ${lowered_start} -1 lowered)
foreach(instruction LEAVE ITERATE)
    if(NOT raw MATCHES "${instruction} :")
        message(FATAL_ERROR "Source tree lost ${instruction}")
    endif()
endforeach()
if(NOT lowered MATCHES "IMPORT :[^\n]*\n[ ]+LITERAL : \"rexxdostate\"")
    message(FATAL_ERROR "Lowered tree lacks shared DO runtime import")
endif()
if(NOT lowered MATCHES "FUNCTION : \"rexxdostate_invalid_transfer\"")
    message(FATAL_ERROR "Lowered tree lacks reached-only error call")
endif()
