delete from inst_name;
insert into inst_name VALUES('acopy','Acopy');
insert into inst_name VALUES('and','Logical AND');
insert into inst_name VALUES('append','Append to String');
insert into inst_name VALUES('appendchar','Append Character');
insert into inst_name VALUES('assertinitialized','Assertinitialized');
insert into inst_name VALUES('asserttype','Asserttype');
insert into inst_name VALUES('bappend','Binary Append');
insert into inst_name VALUES('bcf','Branch on Count if False');
insert into inst_name VALUES('bcheckrange','Binary Range Check');
insert into inst_name VALUES('bclear','Binary Clear');
insert into inst_name VALUES('bcmpb','Binary Byte Compare');
insert into inst_name VALUES('bcmps','Binary String Compare');
insert into inst_name VALUES('bconcat','Binary Concatenate');
insert into inst_name VALUES('bcopy','Binary Copy');
insert into inst_name VALUES('bct','Branch on Count if True');
insert into inst_name VALUES('bctnm','Branch on Count to Name');
insert into inst_name VALUES('bctp','Bctp');
insert into inst_name VALUES('beq','Branch on Equal');
insert into inst_name VALUES('bfill','Binary Fill');
insert into inst_name VALUES('bge','Branch on Greater Than or Equal');
insert into inst_name VALUES('bgetf32','Binary Float32 Read');
insert into inst_name VALUES('bgetf64','Binary Float64 Read');
insert into inst_name VALUES('bgeti16','Binary Signed 16-bit Read');
insert into inst_name VALUES('bgeti32','Binary Signed 32-bit Read');
insert into inst_name VALUES('bgeti64','Binary Signed 64-bit Read');
insert into inst_name VALUES('bgeti8','Binary Signed 8-bit Read');
insert into inst_name VALUES('bgets','Binary UTF-8 String Read');
insert into inst_name VALUES('bgetu16','Binary Unsigned 16-bit Read');
insert into inst_name VALUES('bgetu32','Binary Unsigned 32-bit Read');
insert into inst_name VALUES('bgetu8','Binary Unsigned 8-bit Read');
insert into inst_name VALUES('bgt','Branch on Greater Than');
insert into inst_name VALUES('bintos','Binary to String');
insert into inst_name VALUES('ble','Branch on Less Than or Equal');
insert into inst_name VALUES('blen','Binary Length');
insert into inst_name VALUES('blt','Branch on Less Than');
insert into inst_name VALUES('bmemmove','Binary Memory Move');
insert into inst_name VALUES('bmove','Binary Move');
insert into inst_name VALUES('bne','Branch on Not Equal');
insert into inst_name VALUES('bpoff','Breakpoint Off');
insert into inst_name VALUES('bpon','Breakpoint On');
insert into inst_name VALUES('br','Branch Unconditionally');
insert into inst_name VALUES('bresize','Binary Resize');
insert into inst_name VALUES('brf','Branch on False');
insert into inst_name VALUES('brt','Branch on True');
insert into inst_name VALUES('brtf','Branch on True');
insert into inst_name VALUES('brtpandt','Branch on Type And True');
insert into inst_name VALUES('brtpt','Branch on Type');
insert into inst_name VALUES('bsetf32','Binary Float32 Write');
insert into inst_name VALUES('bsetf64','Binary Float64 Write');
insert into inst_name VALUES('bseti16','Binary Signed 16-bit Write');
insert into inst_name VALUES('bseti32','Binary Signed 32-bit Write');
insert into inst_name VALUES('bseti64','Binary Signed 64-bit Write');
insert into inst_name VALUES('bseti8','Binary Signed 8-bit Write');
insert into inst_name VALUES('bsets','Binary UTF-8 String Write');
insert into inst_name VALUES('bsetu16','Binary Unsigned 16-bit Write');
insert into inst_name VALUES('bsetu32','Binary Unsigned 32-bit Write');
insert into inst_name VALUES('bsetu8','Binary Unsigned 8-bit Write');
insert into inst_name VALUES('bslice','Explicit Binary Slice');
insert into inst_name VALUES('btod','Btod');
insert into inst_name VALUES('btof','Btof');
insert into inst_name VALUES('btoi','Btoi');
insert into inst_name VALUES('btos','Btos');
insert into inst_name VALUES('bupdate','Binary Overlay Update');
insert into inst_name VALUES('call','Call Procedure');
insert into inst_name VALUES('chancancel','Cancel Channel Operation');
insert into inst_name VALUES('chanclose','Close Channel');
insert into inst_name VALUES('chanopen','Open Channel');
insert into inst_name VALUES('chanstart','Start Channel Operation');
insert into inst_name VALUES('chanwait','Wait For Channel Completion');
insert into inst_name VALUES('cnop','No Operation');
insert into inst_name VALUES('concat','String Concat');
insert into inst_name VALUES('concchar','Concatenate Characters');
insert into inst_name VALUES('copy','Copy Register');
insert into inst_name VALUES('dadd','Dadd');
insert into inst_name VALUES('dcall','Dynamic Call Procedure');
insert into inst_name VALUES('dcopy','Dcopy');
insert into inst_name VALUES('ddiv','Ddiv');
insert into inst_name VALUES('dec','Decrement Register');
insert into inst_name VALUES('dec0','Decrement Register 0');
insert into inst_name VALUES('dec1','Decrement Register 1');
insert into inst_name VALUES('dec2','Decrement Register 2');
insert into inst_name VALUES('decplnm','Decplnm');
insert into inst_name VALUES('delattrs','Delattrs');
insert into inst_name VALUES('delattrs1','Delattrs1');
insert into inst_name VALUES('deq','Deq');
insert into inst_name VALUES('deqbr','Deqbr');
insert into inst_name VALUES('deref','Deref');
insert into inst_name VALUES('dextr','Dextr');
insert into inst_name VALUES('dgt','Dgt');
insert into inst_name VALUES('dgtbr','Dgtbr');
insert into inst_name VALUES('dgte','Dgte');
insert into inst_name VALUES('didiv','Didiv');
insert into inst_name VALUES('dlt','Dlt');
insert into inst_name VALUES('dltbr','Dltbr');
insert into inst_name VALUES('dlte','Dlte');
insert into inst_name VALUES('dmod','Dmod');
insert into inst_name VALUES('dmult','Dmult');
insert into inst_name VALUES('dne','Dne');
insert into inst_name VALUES('dpow','Dpow');
insert into inst_name VALUES('dropchar','Drop Character');
insert into inst_name VALUES('dsex','Dsex');
insert into inst_name VALUES('dsub','Dsub');
insert into inst_name VALUES('dtob','Dtob');
insert into inst_name VALUES('dtof','Dtof');
insert into inst_name VALUES('dtoi','Dtoi');
insert into inst_name VALUES('dtos','Dtos');
insert into inst_name VALUES('endlife','Endlife');
insert into inst_name VALUES('erase','Erase');
insert into inst_name VALUES('exit','Exit program');
insert into inst_name VALUES('fadd','Add Float');
insert into inst_name VALUES('fclearerr','Fclearerr');
insert into inst_name VALUES('fclose','Fclose');
insert into inst_name VALUES('fcopy','Copy Float');
insert into inst_name VALUES('fdiv','Divide Float');
insert into inst_name VALUES('feof','Feof');
insert into inst_name VALUES('feq','Float Equals');
insert into inst_name VALUES('ferror','Ferror');
insert into inst_name VALUES('fextr','Fextr');
insert into inst_name VALUES('fflush','Fflush');
insert into inst_name VALUES('fformat','Format String from Float');
insert into inst_name VALUES('fgt','Float Greater Than');
insert into inst_name VALUES('fgtbr','Fgtbr');
insert into inst_name VALUES('fgte','Float Greater Than or Equal');
insert into inst_name VALUES('fidiv','Fidiv');
insert into inst_name VALUES('flt','Float Less Than');
insert into inst_name VALUES('fltbr','Fltbr');
insert into inst_name VALUES('flte','Float Less Than or Equal');
insert into inst_name VALUES('fmod','Fmod');
insert into inst_name VALUES('fmult','Float Multiply');
insert into inst_name VALUES('fndblnk','Find Blank');
insert into inst_name VALUES('fndnblnk','Find Nth Blank');
insert into inst_name VALUES('fne','Float Not Equal');
insert into inst_name VALUES('fopen','Fopen');
insert into inst_name VALUES('fpow','Power of Float');
insert into inst_name VALUES('freadb','Freadb');
insert into inst_name VALUES('freadbyte','Freadbyte');
insert into inst_name VALUES('freadcdpt','Freadcdpt');
insert into inst_name VALUES('freadline','Freadline');
insert into inst_name VALUES('fsex','Sign Exchange Float');
insert into inst_name VALUES('fsub','Subtract Float');
insert into inst_name VALUES('ftob','Float to Boolean');
insert into inst_name VALUES('ftod','Ftod');
insert into inst_name VALUES('ftoi','Float to Int');
insert into inst_name VALUES('ftos','Float to String');
insert into inst_name VALUES('fwrite','Fwrite');
insert into inst_name VALUES('fwriteb','Fwriteb');
insert into inst_name VALUES('fwritebyte','Fwritebyte');
insert into inst_name VALUES('fwritecdpt','Fwritecdpt');
insert into inst_name VALUES('getabufs','Getabufs');
insert into inst_name VALUES('getandtp','Getandtp');
insert into inst_name VALUES('getattrs','Getattrs');
insert into inst_name VALUES('getbyte','Get Byte');
insert into inst_name VALUES('getenv','Getenv');
insert into inst_name VALUES('getnumcas','Getnumcas');
insert into inst_name VALUES('getnumdgts','Getnumdgts');
insert into inst_name VALUES('getnumfrm','Getnumfrm');
insert into inst_name VALUES('getnumfuz','Getnumfuz');
insert into inst_name VALUES('getnumstd','Getnumstd');
insert into inst_name VALUES('gettp','Get Type');
insert into inst_name VALUES('hexchar','Get Hex Char from String');
insert into inst_name VALUES('iadd','Integer Add');
insert into inst_name VALUES('iand','Integer AND');
insert into inst_name VALUES('ichkrng','Ichkrng');
insert into inst_name VALUES('icopy','Integer Copy');
insert into inst_name VALUES('idiv','Integer Divide');
insert into inst_name VALUES('ieq','Integer Equals');
insert into inst_name VALUES('igt','Integer Greater Than');
insert into inst_name VALUES('igtbr','Igtbr');
insert into inst_name VALUES('igte','Integer Greater Than or Equal');
insert into inst_name VALUES('ilt','Integer Less Than');
insert into inst_name VALUES('iltbr','Iltbr');
insert into inst_name VALUES('ilte','Integer Less Than or Equal');
insert into inst_name VALUES('imod','Integer Modulo');
insert into inst_name VALUES('imult','Intger Multiply');
insert into inst_name VALUES('inc','Increment Integer Register');
insert into inst_name VALUES('inc0','Increment Register R0');
insert into inst_name VALUES('inc1','Increment Register R1');
insert into inst_name VALUES('inc2','Increment Register R2');
insert into inst_name VALUES('ine','Integer Not Equal');
insert into inst_name VALUES('inot','Invert All Bits of Integer');
insert into inst_name VALUES('insattrs','Insattrs');
insert into inst_name VALUES('insattrs1','Insattrs1');
insert into inst_name VALUES('ior','Bitwise OR of two integers');
insert into inst_name VALUES('ipow','Power of Integer');
insert into inst_name VALUES('irand','Random Integer');
insert into inst_name VALUES('isex','Integer Sign Exchange');
insert into inst_name VALUES('ishl','Integer Shift Left');
insert into inst_name VALUES('ishr','Integer Shift Right');
insert into inst_name VALUES('isinitialized','Isinitialized');
insert into inst_name VALUES('istype','Istype');
insert into inst_name VALUES('isub','Integer Subtract');
insert into inst_name VALUES('itob','Itob');
insert into inst_name VALUES('itod','Itod');
insert into inst_name VALUES('itof','Integer to Float');
insert into inst_name VALUES('itos','Integer to String');
insert into inst_name VALUES('ixor','Bitwise Exclusive OR of two Integers');
insert into inst_name VALUES('link','Link');
insert into inst_name VALUES('linkarg','Linkarg');
insert into inst_name VALUES('linkattr','Link Attributes');
insert into inst_name VALUES('linkattr1','Linkattr1');
insert into inst_name VALUES('linkref','Linkref');
insert into inst_name VALUES('linktoattr','Linktoattr');
insert into inst_name VALUES('linktoattr1','Linktoattr1');
insert into inst_name VALUES('load','Load');
insert into inst_name VALUES('loadsettp','Load and Set Type');
insert into inst_name VALUES('metadecodeinst','Metadecodeinst');
insert into inst_name VALUES('metalinkpreg','Metalinkpreg');
insert into inst_name VALUES('metaloadcalleraddr','Metaloadcalleraddr');
insert into inst_name VALUES('metaloaddata','Metaloaddata');
insert into inst_name VALUES('metaloadedeprocs','Metaloadedeprocs');
insert into inst_name VALUES('metaloadedmodules','Metaloadedmodules');
insert into inst_name VALUES('metaloadedprocs','Metaloadedprocs');
insert into inst_name VALUES('metaloadfoperand','Metaloadfoperand');
insert into inst_name VALUES('metaloadinst','Metaloadinst');
insert into inst_name VALUES('metaloadioperand','Metaloadioperand');
insert into inst_name VALUES('metaloadmodule','Metaloadmodule');
insert into inst_name VALUES('metaloadpoperand','Metaloadpoperand');
insert into inst_name VALUES('metaloadsoperand','Metaloadsoperand');
insert into inst_name VALUES('minattrs','Minattrs');
insert into inst_name VALUES('mkref','Mkref');
insert into inst_name VALUES('move','Move');
insert into inst_name VALUES('mtime','Microseconds Time');
insert into inst_name VALUES('not','Not');
insert into inst_name VALUES('null','Null');
insert into inst_name VALUES('numeng','Numeng');
insert into inst_name VALUES('numsci','Numsci');
insert into inst_name VALUES('or','Logical OR');
insert into inst_name VALUES('padstr','Pad a String');
insert into inst_name VALUES('poschar','Position of Char');
insert into inst_name VALUES('readline','Read a Line');
insert into inst_name VALUES('refvalid','Refvalid');
insert into inst_name VALUES('req','Req');
insert into inst_name VALUES('ret','Return');
insert into inst_name VALUES('rgt','Rgt');
insert into inst_name VALUES('rgte','Rgte');
insert into inst_name VALUES('rlt','Rlt');
insert into inst_name VALUES('rlte','Rlte');
insert into inst_name VALUES('rne','Rne');
insert into inst_name VALUES('rseq','Rseq');
insert into inst_name VALUES('rxhash','Rxhash');
insert into inst_name VALUES('rxvers','Rxvers');
insert into inst_name VALUES('sappend','Append a String');
insert into inst_name VALUES('say','Write on Console');
insert into inst_name VALUES('sayx','Write on Console without Linefeed');
insert into inst_name VALUES('sconcat','Concatenate String');
insert into inst_name VALUES('scopy','Copy String');
insert into inst_name VALUES('seq','String Equals');
insert into inst_name VALUES('setattrs','Setattrs');
insert into inst_name VALUES('setbyte','Set Byte');
insert into inst_name VALUES('setnumcas','Setnumcas');
insert into inst_name VALUES('setnumdgts','Setnumdgts');
insert into inst_name VALUES('setnumfrm','Setnumfrm');
insert into inst_name VALUES('setnumfuz','Setnumfuz');
insert into inst_name VALUES('setnumstd','Setnumstd');
insert into inst_name VALUES('setobjtype','Setobjtype');
insert into inst_name VALUES('setobjuninit','Setobjuninit');
insert into inst_name VALUES('setortp','OR the Register Type Flag');
insert into inst_name VALUES('setref','Setref');
insert into inst_name VALUES('settp','Set Register Type Flag');
insert into inst_name VALUES('settpmask','Settpmask');
insert into inst_name VALUES('sget','String Constant Extract');
insert into inst_name VALUES('sgt','String Greater Than');
insert into inst_name VALUES('sgte','String Greater Than or Equal');
insert into inst_name VALUES('sigbr','Sigbr');
insert into inst_name VALUES('sigbrv','Sigbrv');
insert into inst_name VALUES('sigcall','Sigcall');
insert into inst_name VALUES('sigcalla','Sigcalla');
insert into inst_name VALUES('sigcallbr','Sigcallbr');
insert into inst_name VALUES('sighalt','Sighalt');
insert into inst_name VALUES('sigignore','Sigignore');
insert into inst_name VALUES('signal','Signal');
insert into inst_name VALUES('signalf','Signalf');
insert into inst_name VALUES('signalt','Signalt');
insert into inst_name VALUES('sigpop','Sigpop');
insert into inst_name VALUES('sigpush','Sigpush');
insert into inst_name VALUES('sigret','Sigret');
insert into inst_name VALUES('sigshalt','Sigshalt');
insert into inst_name VALUES('slt','String Less Than');
insert into inst_name VALUES('slte','String Less Than or Equal');
insert into inst_name VALUES('sne','String Not Equal');
insert into inst_name VALUES('sockaccept','Sockaccept');
insert into inst_name VALUES('sockbind','Sockbind');
insert into inst_name VALUES('sockblocking','Sockblocking');
insert into inst_name VALUES('sockclose','Sockclose');
insert into inst_name VALUES('sockconnect','Sockconnect');
insert into inst_name VALUES('sockconnecttls','Sockconnecttls');
insert into inst_name VALUES('sockerror','Sockerror');
insert into inst_name VALUES('sockkeepalive','Sockkeepalive');
insert into inst_name VALUES('socklisten','Socklisten');
insert into inst_name VALUES('socklocal','Socklocal');
insert into inst_name VALUES('socknew','Socknew');
insert into inst_name VALUES('socknodelay','Socknodelay');
insert into inst_name VALUES('sockpeer','Sockpeer');
insert into inst_name VALUES('sockpending','Sockpending');
insert into inst_name VALUES('sockrecv','Sockrecv');
insert into inst_name VALUES('sockrecvb','Sockrecvb');
insert into inst_name VALUES('socksend','Socksend');
insert into inst_name VALUES('socksendb','Socksendb');
insert into inst_name VALUES('sockshutdown','Sockshutdown');
insert into inst_name VALUES('sockstarttls','Sockstarttls');
insert into inst_name VALUES('sockstatus','Sockstatus');
insert into inst_name VALUES('socktimeout','Socktimeout');
insert into inst_name VALUES('srcfprocsel','Srcfprocsel');
insert into inst_name VALUES('srcmethodsel','Srcmethodsel');
insert into inst_name VALUES('stob','Stob');
insert into inst_name VALUES('stobin','String to Binary');
insert into inst_name VALUES('stod','Stod');
insert into inst_name VALUES('stof','String to Float');
insert into inst_name VALUES('stoi','String to Int');
insert into inst_name VALUES('strchar','String to Char');
insert into inst_name VALUES('strlen','String Length');
insert into inst_name VALUES('strlower','Lowercase String');
insert into inst_name VALUES('strpos','Strpos');
insert into inst_name VALUES('strupper','Uppercase String');
insert into inst_name VALUES('substcut','Set Substring and Cut Off');
insert into inst_name VALUES('substring','Explicit String Slice');
insert into inst_name VALUES('swap','Swap Registers');
insert into inst_name VALUES('time','Get Time');
insert into inst_name VALUES('transchar','Translate Characters');
insert into inst_name VALUES('triml','Trim String from Left');
insert into inst_name VALUES('trimr','Trim String from Right');
insert into inst_name VALUES('trunc','Truncate');
insert into inst_name VALUES('typeof','Typeof');
insert into inst_name VALUES('unlink','Unlink Register');
insert into inst_name VALUES('unlinkattr','Unlinkattr');
insert into inst_name VALUES('unlinkattr1','Unlinkattr1');
insert into inst_name VALUES('unref','Unref');
insert into inst_name VALUES('xtime','Put extended Time properties into OP1');
insert into inst_name VALUES('call1','Call Procedure With One Argument');
insert into inst_name VALUES('call2','Call Procedure With Two Arguments');
insert into inst_name VALUES('call3','Call Procedure With Three Arguments');
insert into inst_name VALUES('call4','Call Procedure With Four Arguments');
insert into inst_name VALUES('parsewords3','Parse Three Fields');
insert into inst_name VALUES('parsepos2','Parse Prefix And Word');
insert into inst_name VALUES('parsewords3d','Parse And Discard Tail');
insert into inst_name VALUES('parseplan','Execute Frozen Parse Plan');
insert into inst_name VALUES('jumps','String Jump Table');
insert into inst_name VALUES('jumpb','Binary Jump Table');
insert into inst_name VALUES('jumpbs','Binary Slice Jump Table');
insert into inst_name VALUES('jumpi','Integer Jump Table');
insert into inst_name VALUES('jumpr','Rexx String Jump Table');
insert into inst_name VALUES('jumpn','Numeric String Jump Table');
insert into inst_name VALUES('bineq','Binary Equals');
insert into inst_name VALUES('binne','Binary Not Equals');
insert into inst_name VALUES('steminit','Initialize Native Stem');
insert into inst_name VALUES('stemget','Get Native Stem Value');
insert into inst_name VALUES('stemset','Set Native Stem Value');
insert into inst_name VALUES('stemreset','Reset Native Stem');
insert into inst_name VALUES('stemget2','Get Compound Native Stem Value');
insert into inst_name VALUES('stemset2','Set Compound Native Stem Value');
insert into inst_name VALUES('stemsize','Native Stem Size');
insert into inst_name VALUES('stemkeyat','Native Stem Key At Index');
insert into inst_name VALUES('stemvalueat','Native Stem Value At Index');
