insert into inst_name VALUES('appendchar','Append Character');
insert into inst_name VALUES('amap','Map to Arg');
insert into inst_name VALUES('and','Logical AND');
insert into inst_name VALUES('append','Append to String');
insert into inst_name VALUES('bcf','Branch on Count if False');
insert into inst_name VALUES('bct','Branch on Count of True');
insert into inst_name VALUES('bctnm','Branch on Count to Name');
insert into inst_name VALUES('beq','Branch on Equal');
insert into inst_name VALUES('bge','Branch on Greater Than or Equal');
insert into inst_name VALUES('bgt','Branch on Greater Than');
insert into inst_name VALUES('ble','Branch on Less Than or Equal');
insert into inst_name VALUES('blt','Branch on Less Than');
insert into inst_name VALUES('bne','Branch on Not Equal');
insert into inst_name VALUES('bpoff','Breakpoint Off');
insert into inst_name VALUES('bpon','Breakpoint On');
insert into inst_name VALUES('br','Branch Unconditionally');
insert into inst_name VALUES('brf','Branch on False');
insert into inst_name VALUES('brt','Branch on True');
insert into inst_name VALUES('brtpandt','Branch on Type And True');
insert into inst_name VALUES('beq','Branch on Equal');
insert into inst_name VALUES('brtpt','Branch on Type');
insert into inst_name VALUES('brtf','Branch on True');
insert into inst_name VALUES('cnop','No Operation');
insert into inst_name VALUES('concchar','Concatenate Characters');
insert into inst_name VALUES('concat','String Concat');
insert into inst_name VALUES('call','Call Procedure');
insert into inst_name VALUES('copy','Copy Register');
insert into inst_name VALUES('dec','Decrement Register');
insert into inst_name VALUES('dec0','Decrement Register 0');
insert into inst_name VALUES('dcall','Dynamic Call Procedure');
insert into inst_name VALUES('dec2','Decrement Register 2');
insert into inst_name VALUES('dec1','Decrement Register 1');
insert into inst_name VALUES('divf','Divide Float');
insert into inst_name VALUES('divi','Divide Integer');
insert into inst_name VALUES('dllparms','DLL Parameter Fetch');
insert into inst_name VALUES('dropchar','Drop Character');
insert into inst_name VALUES('exit','Exit program');
insert into inst_name VALUES('fadd','Add Float');
insert into inst_name VALUES('fcopy','Copy Float');
insert into inst_name VALUES('fdiv','Divide Float');
insert into inst_name VALUES('feq','Float Equals');
insert into inst_name VALUES('fformat','Format String from Float');
insert into inst_name VALUES('fgt','Float Greater Than');
insert into inst_name VALUES('fgte','Float Greater Than or Equal');
insert into inst_name VALUES('flt','Float Less Than');
insert into inst_name VALUES('flte','Float Less Than or Equal');
insert into inst_name VALUES('fmult','Float Multiply');
insert into inst_name VALUES('fndblnk','Find Blank');
insert into inst_name VALUES('fndnblnk','Find Nth Blank');
insert into inst_name VALUES('fne','Float Not Equal');
insert into inst_name VALUES('fpow','Power of Float');
insert into inst_name VALUES('fsex','Sign Exchange Float');
insert into inst_name VALUES('fsub','Subtract Float');
insert into inst_name VALUES('ftob','Float to Boolean');
insert into inst_name VALUES('ftoi','Float to Int');
insert into inst_name VALUES('ftos','Float to String');
insert into inst_name VALUES('feq','Float Equals');
insert into inst_name VALUES('getstrpos','Get String Position');
insert into inst_name VALUES('gmap','Map Global');
insert into inst_name VALUES('gettp','Get Type');
insert into inst_name VALUES('getbyte','Get Byte');
insert into inst_name VALUES('hexchar','Get Hex Char from String');
insert into inst_name VALUES('iadd','Integer Add');
insert into inst_name VALUES('igt','Integer Greater Than');
insert into inst_name VALUES('iand','Integer AND');
insert into inst_name VALUES('icopy','Integer Copy');
insert into inst_name VALUES('idiv','Integer Divide');
insert into inst_name VALUES('ieq','Integer Equals');
insert into inst_name VALUES('igt','Integer Greater Than');
insert into inst_name VALUES('igte','Integer Greater Than or Equal');
insert into inst_name VALUES('iand','Integer AND');
insert into inst_name VALUES('igte','Integer Greater Than or Equal');
insert into inst_name VALUES('ilt','Integer Less Than');
insert into inst_name VALUES('ilte','Integer Less Than or Equal');
insert into inst_name VALUES('imod','Integer Modulo');
insert into inst_name VALUES('imult','Intger Multiply');
insert into inst_name VALUES('inc','Increment Integer Register');
insert into inst_name VALUES('inc0','Increment Register R0');
insert into inst_name VALUES('inc1','Increment Register R1');
insert into inst_name VALUES('ine','Integer Not Equal');
insert into inst_name VALUES('inot','Invert All Bits of Integer');
insert into inst_name VALUES('ior','Bitwise OR of two integers');
insert into inst_name VALUES('ipow','Power of Integer');
insert into inst_name VALUES('irand','Random Integer');
insert into inst_name VALUES('isex','Integer Sign Exchange');
insert into inst_name VALUES('ishl','Integer Shift Left');
insert into inst_name VALUES('ishr','Integer Shift Right');
insert into inst_name VALUES('isub','Integer Subtract');
insert into inst_name VALUES('itof','Integer to Float');
insert into inst_name VALUES('itos','Integer to String');
insert into inst_name VALUES('ixor','Bitwise Exclusive OR of two Integers');
insert into inst_name VALUES('inc2','Increment Register R2');
insert into inst_name VALUES('linkattr','Link Attributes');
insert into inst_name VALUES('load','Load');
insert into inst_name VALUES('loadsettp','Load and Set Type');
insert into inst_name VALUES('link','Link');
insert into inst_name VALUES('metaloadedm','');
insert into inst_name VALUES('map','Map to Var Name');
insert into inst_name VALUES('metadecodei','');
insert into inst_name VALUES('metaloadcal','');
insert into inst_name VALUES('metaloaddat','');
insert into inst_name VALUES('metaloadedp','');
insert into inst_name VALUES('metaloadfop','');
insert into inst_name VALUES('metaloadins','');
insert into inst_name VALUES('metaloadiop','');
insert into inst_name VALUES('metaloadmod','');
insert into inst_name VALUES('metaloadpop','');
insert into inst_name VALUES('metaloadsop','');
insert into inst_name VALUES('move','Move');
insert into inst_name VALUES('mtime','Microseconds Time');
insert into inst_name VALUES('metalinkpre','');
insert into inst_name VALUES('nsmap','Map to Namespace');
insert into inst_name VALUES('null','Null');
insert into inst_name VALUES('not','Not');
insert into inst_name VALUES('opendll','Open Dynamic Link Library');
insert into inst_name VALUES('or','Logical OR');
insert into inst_name VALUES('padstr','Pad a String');
insert into inst_name VALUES('pmap','Map to Parent Var');
insert into inst_name VALUES('poschar','Position of Char');
insert into inst_name VALUES('ret','Return');
insert into inst_name VALUES('rseq','');
insert into inst_name VALUES('readline','Read a Line');
insert into inst_name VALUES('sappend','Append a String');
insert into inst_name VALUES('say','Write on Console');
insert into inst_name VALUES('sayx','Write on Console without Linefeed');
insert into inst_name VALUES('sconcat','Concatenate String');
insert into inst_name VALUES('scopy','Copy String');
insert into inst_name VALUES('seq','String Equals');
insert into inst_name VALUES('setortp','OR the Register Type Flag');
insert into inst_name VALUES('setstrpos','Set String Charpos');
insert into inst_name VALUES('settp','Set Register Type Flag');
insert into inst_name VALUES('sgt','String Greater Than');
insert into inst_name VALUES('sgte','String Greater Than or Equal');
insert into inst_name VALUES('slt','String Less Than');
insert into inst_name VALUES('slte','String Less Than or Equal');
insert into inst_name VALUES('sne','String Not Equal');
insert into inst_name VALUES('stof','String to Float');
insert into inst_name VALUES('stoi','String to Int');
insert into inst_name VALUES('strchar','String to Char');
insert into inst_name VALUES('strlen','String Length');
insert into inst_name VALUES('strlower','Lowercase String');
insert into inst_name VALUES('strupper','Uppercase String');
insert into inst_name VALUES('substcut','Set Substring and Cut Off');
insert into inst_name VALUES('substr','Substring');
insert into inst_name VALUES('substring','Set remaining String');
insert into inst_name VALUES('swap','Swap Registers');
insert into inst_name VALUES('time','Get Time');
insert into inst_name VALUES('transchar','Translate Characters');
insert into inst_name VALUES('triml','Trim String from Left');
insert into inst_name VALUES('trimr','Trim String from Right');
insert into inst_name VALUES('trunc','Truncate');
insert into inst_name VALUES('unlink','Unlink Register');
insert into inst_name VALUES('unmap','Unmap Register');
insert into inst_name VALUES('xtime','Put extended Time properties into OP1');
