name: Local Build CREXX on Linux arm64

on:
  workflow_dispatch:

jobs:
  build-linux-local:
    name: Build on self-hosted Linux (manual)
    runs-on: [self-hosted, linux]

    steps:
      - name: Determine Release Name
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "RELEASE_ID=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref }}" == refs/heads/master ]]; then
            echo "RELEASE_ID=release_candidate" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref }}" == refs/heads/develop ]]; then
            echo "RELEASE_ID=dev_snapshot" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref }}" =~ ^refs/heads/feature/.*$ ]]; then
            echo "RELEASE_ID=${GITHUB_REF#refs/heads/feature/}" >> "$GITHUB_ENV"
          else
            echo "Skip release"
          fi

      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Configure + Build Release (MinSizeRel)
        shell: bash
        run: |
          cmake -S . -B "${{ runner.temp }}/release" -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel
          cmake --build "${{ runner.temp }}/release"

      - name: CTest Release
        shell: bash
        run: |
          ctest --test-dir "${{ runner.temp }}/release" --output-on-failure --no-tests=error --parallel 1

      - name: Collect executables
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "${{ runner.temp }}/exe/bin"
          mkdir -p "${{ runner.temp }}/exe/examples"

          # Copy everything from release bin to staging bin
          cp "${{ runner.temp }}/release/bin/"* "${{ runner.temp }}/exe/bin/"

          # examples
          cp tests/demo/* "${{ runner.temp }}/exe/examples/"

          # Docs
          cp LICENSE README.md SECURITY.md INSTALL-RUN.md "${{ runner.temp }}/exe/"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: CREXX-Linux-local
          path: |
            ${{ runner.temp }}/exe
