name: Local Build CREXX for Windows arm64

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Local Build for Windows
    runs-on: [self-hosted, windows]

    steps:
      - name: Update Toolchain (MSYS2)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
            openssl:p
            pkgconf:p


      - name: Determine Release Name
        shell: msys2 {0}
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "RELEASE_ID=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref }}" == refs/heads/master ]]; then
            echo "RELEASE_ID=release_candidate" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref }}" == refs/heads/develop ]]; then
            echo "RELEASE_ID=dev_snapshot" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref }}" =~ ^refs/heads/feature/.*$ ]]; then
            echo "RELEASE_ID=${GITHUB_REF#refs/heads/feature/}" >> "$GITHUB_ENV"
          else
            echo "Skip release"
          fi

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1 

      - name: Build Release
        shell: msys2 {0}
        run: |
          cmake -S . -G Ninja -B "${{ runner.temp }}/release" -DCMAKE_BUILD_TYPE=MinSizeRel  -DCREXX_FORCE_SYSTEM_OPENSSL=ON
          cmake --build "${{ runner.temp }}/release"

      - name: CTest Release
        shell: msys2 {0}
        run: |
          ctest --test-dir "${{ runner.temp }}/release" --output-on-failure --no-tests=error --parallel 1

      - name: Collect executables
        shell: msys2 {0}
        run: |
          set -euo pipefail
          mkdir -p "${{ runner.temp }}/exe/bin"
          mkdir -p "${{ runner.temp }}/exe/examples"

          # Copy everything from release bin to staging bin
          cp "${{ runner.temp }}/release/bin/"* "${{ runner.temp }}/exe/bin/"

          # examples
          cp tests/demo/* "${{ runner.temp }}/exe/examples/"
          	  
          # Docs
          cp LICENSE README.md SECURITY.md INSTALL-RUN.md "${{ runner.temp }}/exe/"

      - name: Upload Executable
        if: env.RELEASE_ID
        uses: actions/upload-artifact@v5
        with:
          name: CREXX-Windows
          path: |
            ${{ runner.temp }}/exe
